### ISSUE TITLE
Additional torrent settings (PeX and DHT)

### ISSUE THREAD

**Issue by 0xAB51NTH** [ThaUnknown/miru#100]
**Is your feature request related to a problem? Please describe.**
Peer discovery (PeX) and decentralized network (DHT) might lead to issues of privacy leakage where one might use the DHT in order to check what someone else is downloading. (Also I just hate them) And I think that user should have option to turn it OFF/ON.

**Describe the solution you'd like**
A nice and based button in torrent settings for both of those settings soo they can be turned off

**Additional context**
a very good mockup
![mockup](https://user-images.githubusercontent.com/47013267/158205022-ede1455f-5285-43db-8005-be2aa3c910b9.png)

**Comment by ThaUnknown** [comment]
819a2b1e98fd05b9c91ec1bfbe6c1a15f7224223
