### ISSUE TITLE
Anilist login

### ISSUE THREAD

**Issue by rubanunes** [ThaUnknown/miru#101]
Logged in with Anilist without problem. Proceed to click on the avatar. Turns back to "Login with Anilist" without the ability to do so.

**To Reproduce**
1. Click "Login with Anilist"
2. Fill everything
3. Click on the account avatar on the app
4. Turns to default icon and "Login with Anilist" popup

**Expected behavior**
Don't know, probably my watching list.

**Comment by ThaUnknown** [comment]
I can't reproduce this :&

**Comment by ThaUnknown** [comment]
I think the issue here is that you're returning to the AL page, rather than just clicking the prompted login button, sometimes you need to click it twice because of AL shizzle.

**Comment by Waaiez** [comment]
https://files.catbox.moe/e8f58m.mkv

I think this might be the issue they're having.

You are able to log into Anilist at first.
However when you click your profile picture, Miru will log you out of Anilist
Trying to click the log in button doesn't do anything

I've been working around this by revoking access to Miru in Anilist Apps settings and then clicking the log in button which will then show me that initial authorize screen and Miru will log in like normal

**Comment by ThaUnknown** [comment]
too, my screen recorder

I'll look at this

**Comment by Muril-o** [comment]
It's not that the anilist token is not working or anything related to revoked access, its simply the page (more specifically the sidebar module and the home page module) not reloading itself after the token is sent to the URLSearchParams and stored in localStorage.
Simply reloading the modules or setting the parameters after the token is stored should fix the issue.

> It's not that the anilist token is not working or anything related to revoked access, its simply the page (more specifically the sidebar module and the home page module) not reloading itself after the token is sent to the URLSearchParams and stored in localStorage
Also btw as a quick fix for it instead of revoking anilist access you could simply Ctrl+Shift+R and everything should work as intended

**Comment by rubanunes** [comment]
Oh sorry forgot about the ticket... So I did not need to double press login. It just straight logged in. So clicking my avatar logs out right? No way to see my watching list?

**Comment by Muril-o** [comment]
> It just straight logged in. So clicking my avatar logs out right?

Yes, clicking your avatar logs you out, and after you enter your credentials once on the anilist page it caches on the browser so you don't need to login again.
> No way to see my watching list?

The watching list is working just fine here (and yes I only have one anime on my watching list)

https://user-images.githubusercontent.com/40826732/158513427-b06dbb2f-4a14-49e4-903d-3163e06e7d28.mp4
