### ISSUE TITLE
Exit out of player completely

### ISSUE THREAD

**Issue by BNX070** [ThaUnknown/miru#102]
There is currently no way to exit from the player or stop downloading completely except by starting a new torrent or exiting the app, also relaunching the app brings the last played torrent back up instead of the home page causing it to rebuffer.

It would be great if there was an X button to close the current stream entirely also please add an option in settings to turn off PIP mode.

**Comment by BNX070** [comment]
Alright, I get all of that and yes it makes sense but instead can you not make it so all of what you mentioned above occurs in the background without having the player running/constantly displayed? If possible add a small bar at the top displaying that seeding is taking place in the background. Cos having the player constantly up is a bit of a sore.

**Comment by traviss64** [comment]
I don't see the X on the player. Neither is normal mode nor in PiP mode.
