### ISSUE TITLE
Renderer process crashing after electron node integration is re-initiated

### ISSUE THREAD

**Issue by Muril-o** [ThaUnknown/miru#105]
**Describe the bug**
Electron renderer process is crashing after electron target URL is updated 'n' times.
Every 'n'-th time mainWindow URL is updated, electron renderer crashes.
The 'n' times depends wether you have a video playing or not, and as far as I can see it also depends if you're using the development enviroment or not.
For me 'n' is 3 times on developer enviroment (no video loaded) and 2 times on compiled (distributed) package with a video already loaded. And of course 'n' does not count the first page redirect to index.html renderer.

**To Reproduce**
1. Open app.
2. Update target URL:
2.1. Press Ctrl+Shift+R 'n' times.
2.2. You can also anilist login 'n' times.
4. No matter the interval you do it, it will always crash on the 'n'-th time.
5. Watch renderer process crash (blank screen + devtools disconnect).

**Expected behavior**
Redirects to the targeted URL sucessfully without crashing the renderer.

**Screenshots**`
Blank screen after renderer crash
![image](https://user-images.githubusercontent.com/40826732/158615919-31f88989-d6f8-4f7d-a9e3-875f44cf62c6.png)

**Desktop (please complete the following information):**
 - OS: Windows, Linux
 - Version 0.6.2

**Additional context**
It's weird how it crashes the renderer every 'n'-th time in a fixed manner, maybe it's limited to 4 window redirects somewhere in electron and we are forgetting to close the target url after it finishes its job, but I don't have clues about what could be causing it, might need to research more.

Put this inside the [createWindow function](https://github.com/ThaUnknown/miru/blob/67a1332e09a4225cf0ca772ed56f84e1b637ce85/src/index.js#L30) for checking the error.

`mainWindow.webContents.on("render-process-gone", function() {
    console.log("render-process-gone");
  });
mainWindow.webContents.on("update-target-url", function(event, url) {
    console.log("update-target-url", url);
  });`

Can also enable `ELECTRON_ENABLE_LOGGING` flag for additional debug.
After doing both you should get:

`[1] update-target-url
[1] Renderer process crashed - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information.
[1] render-process-gone`

**Comment by ThaUnknown** [comment]
it's likely node integration causing it, which means #103 will likely fix it, not a priority as the user shouldnt ever need to reload the window

**Comment by ThaUnknown** [comment]
this isn't even the URL changing causing it, it happens when some native node functions are run, which makes me even more convinced it's the node integration

**Comment by ThaUnknown** [comment]
95e8c8e6cb66508a82edc17897e6c3412f98ff4b

**Comment by ThaUnknown** [comment]
confirmed to have been the node integration, fixed in 1.0.0 full release
