### ISSUE TITLE
Video not playing

### ISSUE THREAD

**Issue by dk000111** [ThaUnknown/miru#109]
**Describe the bug**
When the play option is clicked or when the episodes are clicked ,app is redirected to homepage instead of playing the video

**Comment by dragow0lf** [comment]
yup, have same issue

**Comment by ThaUnknown** [comment]
invalid issue template

to clarify, by home page do you mean the vice player, or the give menu?

**Comment by dk000111** [comment]
give menu / list of anime page

**Comment by dragow0lf** [comment]
When you click on Any of the following
[image: image.png]

[image: image.png]

You get sent back to this page
[image: image.png]
Also, as you can see from this image, The new releases tab take an
indefinite time to load

**Comment by ThaUnknown** [comment]
#110

**Comment by dragow0lf** [comment]
I'm logged into anilist but it still doesn't play the video

**Comment by ThaUnknown** [comment]
download the latest version from the [releases tab](https://github.com/ThaUnknown/miru/releases)

**Comment by dk000111** [comment]
I don't but I'm facing same issue even in latest build

**Comment by dragow0lf** [comment]
yup, same issue still in latest build
