### ISSUE TITLE
Trailers dont work

### ISSUE THREAD

**Issue by BlackcatCXII** [ThaUnknown/miru#118]
**Describe the bug**
Doesn't show tráiler when i click on trailer botton .

**To Reproduce**
1. Go to 'anime'
2. Click on 'Trailer'

**Expected behavior**
To se the trailer of selected anime.

**Desktop (please complete the following information):**
 - OS: Windows|
 - Version v0.12.2

**Comment by ThaUnknown** [comment]
oh yeaaaaah... I knew I forgot something

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/miru/commit/ac265701179f4eff171fa449bb05ead6bcc91564
fixed
