### ISSUE TITLE
Android version of miru ?

### ISSUE THREAD

**Issue by cutterchop** [ThaUnknown/miru#119]
hello, I am a new user, the moment I started the app it looked like it has a lot of potential, and with its current look and feature, the feature here being that it uses torrents unlike tons of other apps, it will gain lots of people if it was ported to android, so my request would be if you can work on making it compatible on android please take a look and thanks for your hard work 👍

**Comment by ThaUnknown** [comment]
invalid issue

**Comment by cutterchop** [comment]
> invalid issue

feature request - invalid ?

**Comment by BNX070** [comment]
> > invalid issue
> 
> feature request - invalid ?

As in it's not a related issue, this app won't be ported to android. Keep issues/enhancements related to the PC app.
