### ISSUE TITLE
Custom Installation

### ISSUE THREAD

**Issue by SecondBeta** [ThaUnknown/miru#120]
**Is your feature request related to a problem? Please describe.**
A custom installation step in the installer

**Describe the solution you'd like**
When Miru is being set up an option to specify a download location.

**Additional context**
N/A

**Comment by ThaUnknown** [comment]
the issue template isnt there for you to remove it, but to fill it out.

**Comment by SecondBeta** [comment]
Mb oomfie, fixed

- nagi

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/miru/commit/8e40e85b335ae54baa19a9ffa2187538fd143d71
