### ISSUE TITLE
No next episode

### ISSUE THREAD

**Issue by Trucklover96** [ThaUnknown/miru#123]
**Describe the bug**
when i watch one piece it doesnt have episode list and doesnt have a next episode

**To Reproduce**
1. Just go to the one piece anime scroll down and you will see that there isnt an episode list

**Expected behavior**
I would expect for there to be a list of episodes and when i finish one episode the next plays

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version [1.0.2]

![Miru 3_4_2022 10_00_31 μμ](https://user-images.githubusercontent.com/98049345/161443811-a7718ac3-c29e-4cb8-9f48-57555ee757cd.png)

**Comment by ThaUnknown** [comment]
fill out the issue template correctly.
edit this and i'll re-open it.
for now: invalid issue template

**Comment by ThaUnknown** [comment]
one piece is kinda wack, as there isn't a reliable way of getting how many episodes it has, I'll look at some possibilities
