### ISSUE TITLE
Debrid support

### ISSUE THREAD

**Issue by oOflyeyesOo** [ThaUnknown/miru#125]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add debrid services, which is useful where nyaa is blocked. Has cloud services, and many other useful features. Be great for low seeded torrents that may take a bit to buffer.

**Additional context**
Real debrid, premiumize, and alldebrid are the top ones.

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/miru/blob/master/docs/faq.md#can-i-change-what-tracker-torrents-are-found-from

**Comment by oOflyeyesOo** [comment]
Now of them are sketchy and very popular in the steaming community. I have used them for well over a decade. Everyone who uses Kodi streaming apps are using debrid these days.

**Comment by ThaUnknown** [comment]
I might add an extensions API sometime in the future, but for now this is a no. Feel free to PR functionality for this and then I'll implement an extensions API with this as the first extension.
