### ISSUE TITLE
Simkl support

### ISSUE THREAD

**Issue by oOflyeyesOo** [ThaUnknown/miru#126]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Simkl has a much better API than anilist. Very community driven, and sometimes as better naming for search potential.

**Additional context**

**Comment by ThaUnknown** [comment]
Simkl's API isn't any better than AniList. Additionally it's just an aggregator for other DB's like MAL, IDMB etc. It has ~2/3rds of the entries that AniList does. Additionally their terms of service require any app using their API to be a big ass fucking banner saying "use Simkl". Some of it's features are also behind paywalls, and this app is meant to be 100000% free. I do not see how this can bring any new functionality, or improve existing functionality in this app
