### ISSUE TITLE
I can't get Miru to start

### ISSUE THREAD

**Issue by jim4067** [ThaUnknown/miru#130]
**Describe the bug**
I cannot get Miru to start. I cloned the repo to have a local version but what I get is a black window. I have visited [locahost:](http://localhost:3001/) trying to debug it but I also get nothing.

This is a screenshot of my dev-tools panel in Chrome.

![Screenshot_20220409182543](https://user-images.githubusercontent.com/30603522/162580563-1ae84642-9fae-4d41-84fc-12b995899355.png)

I am running Linux Deepin 20.5 based on Debian 10

Is this a dependencies issue?

**Comment by ThaUnknown** [comment]
this is an electron app, not native app

**Comment by jim4067** [comment]
Haven't worked with electron before so including that I should first build the app before running it would be awesome.

**Comment by ThaUnknown** [comment]
say, like this?
https://github.com/ThaUnknown/miru#building-and-development

**Comment by jim4067** [comment]
okay. 😂  I did look at thta but i thought building and running a dev server were different. Because i work in react when doing dev on something i just `install` and `start` the app

If I want to deploy the app then I can build it.

I didn't know you had to build it first and then run it. I figured this out after looking at the logs. It's a cool app 💪🏾 .
