### ISSUE TITLE
Open AniList login request in an external browser

### ISSUE THREAD

**Issue by R3D4CTED** [ThaUnknown/miru#131]
When AniList login is clicked, it currently opens within the app, and requires a complete login process. The URL could be opened in an external browser to merely just approve the access request, reducing time and effort.

**Comment by ThaUnknown** [comment]
fill out the issue template in the future

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/miru/commit/aa16c10dcf0e3072c8e1b66bd4b4766bcc6a4759
