### ISSUE TITLE
Watch together

### ISSUE THREAD

**Issue by ThaUnknown** [ThaUnknown/miru#136]
**Is your feature request related to a problem? Please describe.**
Watch together lobbies.

**Describe the solution you'd like**
WebRTC

**Additional context**
https://github.com/ZsomborBenedek/watch-together-chrome

**Comment by null15** [comment]
You're working on adding a watch together feature? That would be dope

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/miru/commit/369c698a76b420b3ec5af229f9f49221de7a9c37
