### ISSUE TITLE
Disable auto update toggle

### ISSUE THREAD

**Issue by yg5757** [ThaUnknown/miru#142]
**Is your feature request related to a problem? Please describe.**
annoying when auto updates
**Describe the solution you'd like**
An option to opt out of auto updating as the app is forced to auto update. Some people simply want to stay on the version they are on.

**Comment by ThaUnknown** [comment]
no, this is a really bad idea, i don't have reliable testing or anyone to QC this app, as such it happens often that it's pushed with bugs which need to be fixed no matter what

**Comment by melnation-com** [comment]
Can we have the choice to disable auto-update until we want to? often new is what makes it stop working, like currently I'm on 4.5.5 but the change log only goes up to 4.5.4, 

It's the same thing what I do with Jdownloader 2, and Tachiyomi, I disable autupdates on Jdownloader 2 and just use a fork version of Tachiyomi cause the vanilla version is like a semi-nightly version that always push out new stuff.

**Comment by melnation-com** [comment]
> no, this is a really bad idea, i don't have reliable testing or anyone to QC this app, as such it happens often that it's pushed with bugs which need to be fixed no matter what

Can we have the choice to disable auto-update until we want to? often new is what makes it stop working, like currently I'm on 4.5.5 but the change log only goes up to 4.5.4, but videos just never players, the consistent solution I do is download 1 version older, in this case from 4.5.5 to 4.5.4.

It's the same thing what I do with Jdownloader 2, and Tachiyomi, I disable autupdates on Jdownloader 2 and just use a fork version of Tachiyomi cause the vanilla version is like a semi-nightly version that always push out new stuff.
