### ISSUE TITLE
RSS Error

### ISSUE THREAD

**Issue by Hyper3557** [ThaUnknown/miru#146]
Hey, so basically this always shows itself and I am not able to play any anime episode. Please help!

Search Failed

Failed Fetching RSS
Typeerror: Failed to fetch

^^This is the above error.

**Comment by Hyper3557** [comment]
Nvm it got fixed.

**Comment by Hexality** [comment]
![image](https://github.com/ThaUnknown/miru/assets/17398632/4864cf13-6dfd-4a99-9312-4ef557ce01e2)

**Comment by Hexality** [comment]
![image](https://github.com/ThaUnknown/miru/assets/17398632/3ce8bc30-e014-47d2-81a0-ff6a86c12340)

**Comment by ThaUnknown** [comment]
those arent valid RSS URLs
