### ISSUE TITLE
Dub Missing

### ISSUE THREAD

**Issue by Hyper3557** [ThaUnknown/miru#147]
Hey, so basically I wanted to watch dubbed anime + download dubbed anime but all I see is subbed anime.

**Comment by ThaUnknown** [comment]
invalid issue template, fill it out correctly, next time i'll just close the issue without replying

this app doesn't support dubs by default, as it uses torrents, which i do not source myself, of which there are very few

TLDR: not many dub torrents, so dubs arent likely to be found
