### ISSUE TITLE
display playback speed

### ISSUE THREAD

**Issue by Hikandy** [ThaUnknown/miru#149]
**Is your feature request related to a problem? Please describe.**
Right now, when we change the playback speed using the keybind, it doesn't show which playback speed are we choosing, say i want to change it to 1.5x, there's no way of knowing if I'm at 1.5x or 1.6x or 1.7x etc

**Describe the solution you'd like**
a small pop up display of the playback speed when we change it

**Comment by ThaUnknown** [comment]
now displays in `i` menu
