### ISSUE TITLE
Multiple App features

### ISSUE THREAD

**Issue by cutterchop** [ThaUnknown/miru#150]
**Is your feature request related to a problem? Please describe.**
Feature 1 The app shows us a black player on startup, it's very annoying when roaming around and nothing is playing 

Feature 2 Have the app show us the what is currently playing Eg - Name - episode 
Sometimes when binge-watching someone might forget where they reached etc

Feature 3 regarding pop-out mode, have the option to lock the player the reason why I ask for this is because sometimes a person would be roaming around there PC and might accidentally close the pip or might accidentally press on it and go back to player, the lock mode will make the whole play not clickable when the crusor is passed through 

**Describe the solution you'd like**
Have an X button to remove it as it's very annoying, just like when the app has the video player on pop-out mode there is an x button
the x button will serve to remove it when nothing is playing and to turn off an anime when roaming the app 

**Additional context**

Context for black player on app for feature 1 
![image](https://user-images.githubusercontent.com/31880937/163710660-d5807253-896f-4075-b52d-8cbf77c756a6.png)
Context of what could be a solution 
![image](https://user-images.githubusercontent.com/31880937/163709151-067dd639-3d5f-49df-9945-a310e74314e4.png)
extra solution ?
have an option to remove pip?

The context for feature 2
Placement of title and episode
![image](https://user-images.githubusercontent.com/31880937/163710695-0de24236-7b69-4cfa-aa2e-0858f6f5878a.png)

Context for feature 3
![image](https://user-images.githubusercontent.com/31880937/163710963-21815cc5-803f-4538-8059-0236204b06f6.png)

**Comment by cutterchop** [comment]
just like when you pop it out 
![image](https://user-images.githubusercontent.com/31880937/163710435-c8ec4d9c-b1da-4051-8266-694db1489138.png)

also one more suggestion lets assume someone is playing a game and grinding It would be nice if you have a lock button for the pip so that we don't accidently close it off

**Comment by Seekherr** [comment]
Agreed.

**Comment by ThaUnknown** [comment]
fill out the issue template correctly, 1 change per issue
#1
https://github.com/ThaUnknown/miru/blob/master/docs/faq.md#can-i-close-the-miniplayer
#2 WIP
#3 not possible

**Comment by cutterchop** [comment]
> fill out the issue template correctly, 1 change per issue #1 https://github.com/ThaUnknown/miru/blob/master/docs/faq.md#can-i-close-the-miniplayer #2 WIP #3 not possible

thanks for responding and sorry ill make sure next time I follow such format, can you please tell me your opinion about removing the pip completely from settings, as in it wont display a black screen once you launch the app
