### ISSUE TITLE
Add SKIP OPENING LENGTH option and keybind

### ISSUE THREAD

**Issue by Currential** [ThaUnknown/miru#152]
**Is your feature request related to a problem? Please describe.**
I would like to skip the intro sequences for each episode.

**Describe the solution you'd like**
Add a SKIP OPENING LENGTH (Default 85 seconds) option to the settings menu. Have this set to a keybind that can be used skip the opening, and another keybind to go back OPENING LENGTH duration.

**Additional context**
This functionality can be seen in the MAL-Sync extension found in the chrome store.

**Comment by Kirdow** [comment]
Isn't this already a thing bound to S and R?

**Comment by Currential** [comment]
That's on me for not noticing. Thanks for letting me know.
