### ISSUE TITLE
Error on media with no episodes or airing schedules

### ISSUE THREAD

**Issue by Stophelz** [ThaUnknown/miru#154]
When logged into AniList cant click on anything expect the "logout" for AniList

2. Click on Login with AniList
3. Try click on anything, Home page, Airing Schedule ect

Cant click on anything expect the logout from AniList button, nothing happens when clicking on anime or any page.

![image](https://user-images.githubusercontent.com/103955013/163846279-64ce5387-9a3a-4114-9b06-0bd34d0666cb.png)

 - OS: Windows
 - Version 21H2

**Comment by ThaUnknown** [comment]
this isnt caused by log in with anilist

**Comment by ThaUnknown** [comment]
why are you running it in development mode anyways?

**Comment by Stophelz** [comment]
uuuuhhh.. its because I didnt read everything and i didnt know what i was doing. Sorry i wasted your time, all is good now, love the app. apologies
