### ISSUE TITLE
[feature] - Multi languages subs

### ISSUE THREAD

**Issue by Olyno** [ThaUnknown/miru#155]
**Is your feature request related to a problem? Please describe.**

Adding a way to add other language than English for subs. Currently, it looks like we can't.

**Describe the solution you'd like**

*No idea sorry*

**Additional context**

**Comment by ThaUnknown** [comment]
This is something widely outside of my reach too, i recommend you set the home screen releases RSS to erai [via settings], and disable "auto play torrents" in rss settings, then look for erai/multi-sub releases, but finding multi-sub releases isnt always easy, and they dont exist for all torrents

**Comment by Olyno** [comment]
Alright, thank you for the advice, I will have a look!
