### ISSUE TITLE
[enhancement] - Automatic torrent pause

### ISSUE THREAD

**Issue by Olyno** [ThaUnknown/miru#156]
**Is your feature request related to a problem? Please describe.**

When we started a video, the torrent still downloading, and don't pause at any time, causing internet difficulties.

**Describe the solution you'd like**

It's good when the video is playing, but I think it would be better to pause the download if the user just pause the video player to avoid any more internet troubles.

**Additional context**

**Comment by ThaUnknown** [comment]
you can go to settings and reduce the download speed to something under your max internet connection
i do not want an option of "pause torrent" as it exposes the torrents too much to the user, making him worry about it
one of the design principles of this app is to abstract away torrents as much as possible, so the user can use the app without even knowing it uses torrents

**Comment by Olyno** [comment]
I don't think that's what I meant. The purpose of this enhancement would be to automatically pause the torrent download when the user is not watching the anime. In no way the user has to worry about the torrent part, it's just an internal feature. Creating a parameter is something that can be done, but is not mandatory for this feature

**Comment by ThaUnknown** [comment]
defining "the user is not watching" is difficult to be honest, the user might tab out for it to buffer etc
