### ISSUE TITLE
Bug with PopoutWindow

### ISSUE THREAD

**Issue by BlackcatCXII** [ThaUnknown/miru#158]
**Describe the bug**
double video making it slow and cant unpause from the popout Window.

**To Reproduce**
1. Go to 'anime episode'
2. Click on 'pause'
3. Click on  'Popout Window'  2 times
4. Unpause the episode

**Expected behavior**
for the popout window to appear right away and to be able to unpause from the popup player.

**Screenshots**
when I click the popout button the first time
![image](https://user-images.githubusercontent.com/75856980/164143896-d1999fc7-cebd-4ac6-8d5e-f4cb3a5966be.png)
when I click it a second time and press play
![image](https://user-images.githubusercontent.com/75856980/164144100-1fd0de01-bd7d-4cc1-8945-45f318352a2d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: v1.7.0

**Additional context**
I got confused when I pressed the popout bottom for the first time since it went blank I pressed it again thinking it would work and then I pressed play and got the problem from the screenshot also cant unpause from pop-out window

**Comment by cutterchop** [comment]
Watch him say I can't do anything about it and blame it on Bill gates or say invalid

Also the new watch2gether feature barely works but not worth reporting, knowing that the dev is an shit

**Comment by ThaUnknown** [comment]
good catch, it's because at least 1 frame needs to be played for the PiP to actually show, and when u cancel it, it still thinks it needs to wait for 1 frame to play
