### ISSUE TITLE
[Feature Request]: Add a toast regarding dual audio releases and add some explanation to FAQ

### ISSUE THREAD

**Issue by Muril-o** [ThaUnknown/miru#163]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

1. Right now theres nothing that explains why audio is not being played in the FAQ.
2. I know there are exclusion checks for the search URL containing the non supported codecs but dual audio releases are not excluded, and should really not be excluded. Right now there's nothing that notifies the user about the lack of audio.

### Proposed Solution

1. Add "Why is audio not playing?" to the FAQ explaning that the audio codec is not supported and to select a different torrent by disabling Autoplay torrents, and possibly Trusted only to find more torrents that don't have dual audio on it.
2. Add a toast notification for when a dual audio release starts with "No audio? - Try disabling Autoplay torrents and Trusted only in RSS Settings and select a torrent that doesn't contain dual audio."

**Comment by Muril-o** [comment]
I can PR this on the weekend if no one has done it by then.

**Comment by ThaUnknown** [comment]
multi audio is supported, and works, it's the codec that's not supported

could just detect the audio tracks and if their length is 0 say no audio detected

**Comment by ThaUnknown** [comment]
c723415b1aea792b4c241919ed14cf4dc3ad826b
