### ISSUE TITLE
[Feature Request]: multiple RSS feeds

### ISSUE THREAD

**Issue by bananaboy139** [ThaUnknown/miru#164]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

I want to keep subsplease for airing anime, but for older anime with better releases I'd prefer to have special releases, I know I can keep a torrent folder, but this doesn't allow for multiple people to easily share their release choice.

### Proposed Solution

having suppot for several RSS feeds would allow for people to share feeds so that 1 (or multiple) person (or people) can curate the releases, and the rest would automatically have it.

It'd be nice to also have an override order, so that if 2 feeds have the same anime, 1 would automatically take over (I saw a feature suggestion for choosing releases, this isn't a replacement for that, just an automation). 
(similar to the Minecraft resourcepack management system).

**Comment by ThaUnknown** [comment]
I assume by "release feed" you mean the thing on the home screen, not the thing that finds torrents when you click "play" [as that cannot be changed](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md#can-i-change-what-tracker-torrents-are-found-from)

I think a way better option would be in settings to have a "table" or list with 2 fields, "Name" and "URL" which you can freely extend/modify, which would add more rows to the home screen

this was something i was debating, but i havent come up with a decent UI implementation for it just yet x)

**Comment by bananaboy139** [comment]
what about having a button to add and remove torrents on the main anime page (for simple quick changes), then saving the information in a database and having an easy way to edit the database outside of the app (all it would need to save is the anilist ID and the torrent info or magnetlink, I think. That would allow for "power users" to efficiently modify their database without clogging up the UI).
json probably wont be good for this, but just to give you an idea:

`
{
	"20661": {
		"ARID": "{some magnet link}",
		"Some other release name": "{some other magnetlink}"
	},
	"1535": {
		"some release name": "{some magnetlink}"
	}
}
`
I still think it's important for the app to easily fetch someone else's database, it would make life a lot easier.

**Comment by ThaUnknown** [comment]
that's not related to this issue
