### ISSUE TITLE
[Feature Request]: A way to get rid of the anime from the bottom-right side of the screen when done watching it.

### ISSUE THREAD

**Issue by therealsbeve** [ThaUnknown/miru#165]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

There is no way to remove the anime from the bottom-right side of the screen while you're not watching it and so its always there and it blocks the view of the home page. 

![image](https://user-images.githubusercontent.com/84506246/165680983-2f2416ca-f1d4-4626-9ec6-dea577d4e722.png)

### Proposed Solution

Add a button to allow the anime to be removed from view

**Comment by ThaUnknown** [comment]
hm, need to add "read faq" to the checklist,..
no. read faq
