### ISSUE TITLE
[Bug]: Home Page genre list not showing correctly

### ISSUE THREAD

**Issue by BlackcatCXII** [ThaUnknown/miru#167]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v2.1.0

### What operating system version are you using?

Windows

### Expected Behavior

For anime to be in their corresponding genres on the home page.
From trending and below

### Actual Behavior

They all just show cowboy bebop and Trigun.

### Screenshots

![image](https://user-images.githubusercontent.com/75856980/167027428-e8d47861-645c-4b5a-b9b3-476b6ac42881.png)

**Comment by ThaUnknown** [comment]
uh oh, what did you do to cause this? did you use search options or filtering?

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/miru/commit/789c4bd1447e491055cbd7cebfc2a2ffd068bcff
