### ISSUE TITLE
[Feature Request]: horizontal scroll on home page

### ISSUE THREAD

**Issue by danbulant** [ThaUnknown/miru#168]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

I have a laptop with touchpad - when there's a horizontal list of videos, I'd like to scroll them and select the anime I want (instead of having to open the category and then scroll.

### Proposed Solution

Allow horizontal scroll on the home page (i.e. each row should have small scrollbar, or even an invisible one)

**Comment by ThaUnknown** [comment]
I'm kinda torn on this.....
I don't really want this, as I want to load as little content on the main screen at once as possible, in reality this only loads 5 media, which comes out to <0.5MB of data in total. Here's why:
- I don't want to hit CF's burst limiter/protection
- I dont want to hit AniList's rate limit [which already happens too often]
- when torrenting, the client is likely to saturate the user's bandwidth, which means loading anything on the home page takes longer, by extension if there's more data that gets loaded, it will take a lot longer to load that data, making the app less responsive, reducing UX

instead, lets do what I usually prefer doing:
- lets find the underlying issue:
  - why do you want to scroll more? does the suggestions interest you? are the suggestions insufficient? do you already expect what's there and want something new that you haven't seen before? do you expect more content? are the cards too big and take up too much space?
- work up a possible list of solutions
- choose a solution which has the least negative impact, while solving the underlying issue as much as possible

**Comment by ThaUnknown** [comment]
hopefully mitigated this a bit in fd49d2b4d29eb20a5813529c42bf2649c509e511, tell me if this feels better after using it for a while

**Comment by danbulant** [comment]
There's not really an issue, it's just that I want to see more of the content quicker, without having to click on the title/more button.

The cards are sized ok, I don't think they're too big or small.

A possible solution is to load the additional content only on scroll - it loads the first 5 media (my laptop fits 3 and 3/4 with closed menu), and then loads additional only on scroll (or if we want to be more responsive, on hover).

Also, it seems the home page isn't cached - when switching tabs, it always loads the content. If we cache the content for a short while or show cached content, while revalidating the content in the background (could be 3 phases: <2 min cache, <15 min show cached but revalidate, always fetch new)? 

I'm not sure how hard that'd be to implement, depends on how data fetchings works. I'm willing to work on it a bit (used svelte a lot) as well.

**Comment by ThaUnknown** [comment]
stale
