### ISSUE TITLE
[Bug]: Search seems to be failing more often.

### ISSUE THREAD

**Issue by hp561** [ThaUnknown/miru#170]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v2.2.0

### What operating system version are you using?

MacOS

### Expected Behavior

When I try to play an episode, I should expect a list of torrents to choose from to play.

### Actual Behavior

I get a red toast message that says "Search failed. Couldn't find torrent...."

### Screenshots

<img width="217" alt="image" src="https://user-images.githubusercontent.com/26675991/167273877-9b598a52-77ea-4a95-abd6-82942a783ce2.png">

**Comment by Muril-o** [comment]
I'm sorry if I'm insulting your intelligence by asking this, but did you actually read the FAQ when you marked:
> I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md#why-is-anime-x-not-playing) for a solution that fixes this problem, without success.

Just to be sure, because people these days seem not to know how to read for some reason.

**Comment by hp561** [comment]
> I'm sorry if I'm insulting your intelligence by asking this, but did you actually read the FAQ when you marked:
> 
> > I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md#why-is-anime-x-not-playing) for a solution that fixes this problem, without success.
> 
> Just to be sure, because people these days seem not to know how to read for some reason. If you did read it, can I get a screenshot of your RSS settings inside the app?

 My apologies. My trusted only setting got  re-enabled somehow, I thought I had disabled it.

**Comment by Muril-o** [comment]
It's okay, no worries, glad it's working now.
