### ISSUE TITLE
[Feature Request]: Change preview window size

### ISSUE THREAD

**Issue by d4ilyrun** [ThaUnknown/miru#171]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

It is currently not possible to dynamically change the size of the preview window when watching in the side, and the current window might be a bit too small on bigger display resolutions.

### Proposed Solution

I don't really know much about electron, but being able to dynamically update the popup window's size using the mouse scroll could make browsing the anime suggestions or even the settings while watching an episode a lot more practical, and bring a more enjoyable experience overall.

**Comment by ThaUnknown** [comment]
Recently I downscaled the UI as per community vote on the discord.
I intentionally didn't increase the miniplayer size as many people said it's in the way too much.

Here's what I'm considering:
- scaling up the miniplayer
- making it draggable in the same way as mini player of discord streams
  - you can drag it around anywhere
  - always bounces to the nearest edge with a fancy animation

**Comment by Muril-o** [comment]
How about a keybind like PgUp PgDown (or any keybind really) to resize the miniplayer.

**Comment by ThaUnknown** [comment]
One of the corners will be draggable, and have a min/max resize value i guess? something like how chromium handles PiP windows, where they cant be smaller than X and cant be bigger than X

**Comment by d4ilyrun** [comment]
> * making it draggable in the same way as mini player of discord streams
>   
>   * you can drag it around anywhere
>   * always bounces to the nearest edge with a fancy animation

Oh nice !
It would be great 😄

**Comment by ThaUnknown** [comment]
![ezgif-5-e053696df5](https://user-images.githubusercontent.com/6506529/169651830-753655e3-7b86-4c86-bde2-48f6d8f107c8.gif)
was quite fun to make
https://github.com/ThaUnknown/miru/commit/2c2145de9185f9ed5288814127757fba3bda0cc4
