### ISSUE TITLE
[Feature Request]: Proxy support

### ISSUE THREAD

**Issue by Rioluuu** [ThaUnknown/miru#172]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

I want to route all of Mirus traffic through a proxy server in order to improve privacy while using the application.

### Proposed Solution

Add an option to use a (HTTP/S) proxy server for all traffic in the settings.

**Comment by ThaUnknown** [comment]
there's close to no valid reason for re-routing https traffic, i assume you mean you'd want to re-route bittorrent traffic, in that case file an request for it on `webtorrent`'s repo, or actually +1 the few years old issue for it they have which is stale
