### ISSUE TITLE
[Feature Request]: Screenshots

### ISSUE THREAD

**Issue by Laesx** [ThaUnknown/miru#173]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

I'd like to be able to do screenshots and save them to a folder, just like any video player does.

### Proposed Solution

mpv's implementation is quite nice, just a key to save that screenshot without subs (the raw video) and then shift + that key to save it with subs, although I suspect in the way you render subs might make it so a screenshots with subs be kinda difficult to do, I'm not sure, but basic screenshot funcionality would be pretty useful.

**Comment by ThaUnknown** [comment]
screenshotting with subs is easy, see for example the PiP which burns in video with subtitles losslessly real-time, but saving them is the hard part, i'd like to put them in the clipboard, but there might not be a way of doing that unless electron exposes an API for it

**Comment by Laesx** [comment]
At least for my use case, just saving the file to a folder sounds fine and not too hard to do right? I just have quite the big autismo and I'm too used to doing screenshots as I watch, to make stitches too.

**Comment by ThaUnknown** [comment]
https://www.electronjs.org/docs/latest/api/clipboard#clipboardwriteimageimage-type
https://www.electronjs.org/docs/latest/api/native-image#nativeimagecreatefromdataurldataurl

**Comment by ThaUnknown** [comment]
![image](https://user-images.githubusercontent.com/6506529/172051786-21b08f9d-13d5-40e6-8a34-1195b670c5fb.png)
https://github.com/ThaUnknown/miru/commit/00474cdc3e280ed118f52f464df10569e25fef87

default keybind is X, you can change it in the keybinds UI which u can open with ` when in the video player, or by clicking on the top right

this wont be deployed for a few days, but the functionality is there
