### ISSUE TITLE
[Feature Request]: Should retry nyaa at launch multiple times

### ISSUE THREAD

**Issue by AstroVarun** [ThaUnknown/miru#179]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

This might just be a "me" problem but my nyaa.si is partially blocked, basically, it loads nyaa.si in browser but only after refreshing it like 2-3 times. This makes the error pop up every time in Miru.

### Proposed Solution

Retrying to reach nyaa.si multiple times at launch until connected. But, it should not keep retrying endlessly and should stop at some point (maybe after some tries like 5 tries?).

**Comment by ThaUnknown** [comment]
no, this app doesn't make one request to nyaa and it magically works, this will fail over and over again in different places
the fix isnt "try again" but "get a VPN", if you read the popup you get when this happens, YOUD KNOW HOW TO FIX THIS
