### ISSUE TITLE
[Bug]: RSS and unable to login Nyaa! error message

### ISSUE THREAD

**Issue by Iresh007** [ThaUnknown/miru#180]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v2.3.0

### What operating system version are you using?

Windows

### Expected Behavior

The app should run the anime without any problem 

### Actual Behavior

Once I open the app I get the error message that I have provided as a screenshot. Even I open any anime I get the same error message and nothing opens

### Screenshots

![image](https://user-images.githubusercontent.com/64339611/171990280-6dcd310a-5276-4a90-bbc7-8b7a206dc252.png)

**Comment by ThaUnknown** [comment]
read what it says on the "nyaa blocked"

**Comment by Iresh007** [comment]
> read what it says on the "nyaa blocked"

That site is not opening
wiki.privacy.moe/en/tutorials/unblock

**Comment by ThaUnknown** [comment]
> 

its wiki.piracy.moe/en/tutorials/unblock

**Comment by Iresh007** [comment]
> > 
> 
> its wiki.piracy.moe/en/tutorials/unblock

Ya I have tried all the steps in this link but still same issue
also updated to version 2.4.2
But same issue
Any solution

**Comment by ThaUnknown** [comment]
you most definetly did not try DPI block, i'm certain of that because that fixes the issue, you can also try using cloudflare warp
