### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by shshnk13** [ThaUnknown/miru#181]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v2.3.0

### What operating system version are you using?

Windows

### Expected Behavior

I expected to watch anime.

### Actual Behavior

But, when I click on an episode of any anime.
It shows - RSS Error

### Screenshots

![Screenshot (223)](https://user-images.githubusercontent.com/97552013/171998982-a77d4b42-faec-4aa8-b649-0469c207a560.png)

**Comment by ThaUnknown** [comment]
closing as you havent read the FAQ even tho you stated you had. some anime simply wont be found because its too old
