### ISSUE TITLE
[Bug]: Minimizing Picture in picture mode doesn't work when nothing is playing

### ISSUE THREAD

**Issue by Atkoset** [ThaUnknown/miru#187]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

V2.4.2-1 (AUR build)

### What operating system version are you using?

Linux

### Expected Behavior

When in full screen and I press the picture in picture mode (when nothing is playing.) then I expect it to still go into picture in picture mode. 

-Linux x86_64 Manjaro
-Kernel 5.18
-KDE 5.15

### Actual Behavior

When pressing picture in picture from maximized and full screen (when nothing is playing.) then it doesn't change to picture in picture.

**Comment by ThaUnknown** [comment]
Picture in Picture cannot be minimised, that's quite literally its main selling point, this issue is invalid as this behavior is quite literally not possible, and the issue title is completely separate from the issue description
