### ISSUE TITLE
[Feature Request]: Clipboard anilist anime link when user clicks on title

### ISSUE THREAD

**Issue by Muril-o** [ThaUnknown/miru#190]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Right now there is no way to copy a link from inside the app to easily share with other people, or to open it in the default browser.

### Proposed Solution

- Clicking the anime title on ViewAnime page would copy the anilist link for that anime to the clipboard.
- Ctrl + click could open the anilist page for that anime in the default browser.

**Comment by ThaUnknown** [comment]
I'm not a fun of hidden ghost functionality, as such I'm not a fan of how keybinds are currently implemented, how playing back torrents manually is implemented and how the user has no initial knowledge, so I'd rather not implement it in this way, instead have explicit buttons for "sharing" anime via miru, which would copy <miru://anime/[alid]> into their clipboard, which they then can paste into say discord, someone can click and it opens that anime in miru, and also have an external open icon, like W2G has for user profiles, which would open said anime on AL

**Comment by ThaUnknown** [comment]
I think there's another underling issue here. You want to open in it browser, because the app lacks some functionality, or is uncomfortable to navigate in some way, so you end up wanting to open it in browser? I think that's the reason here. Is there anything lacking from the viewAnime page in that sense?

**Comment by Muril-o** [comment]
> because the app lacks some functionality

Yes. All of these required me to manually open the anilist page on browser in a way or another, ones more frequently than others:
- I didn't like the anime, wanna drop it.
You cannot drop an anime from inside the app.
- Let's say I liked the anime and wanna read the manga/LN after watching an episode.
I cannot add manga/LN to my list, or view if anime has a manga/LN.
- I wanna check if this character has the same VA as another character from another anime (happens more frequently than you think).
You can't view characters and their respective VAs.
- I wanna see if my friends are watching the anime so I can hop on discord and discuss with them.
I cannot see which friends are watching/have ptw the anime.
- I finished an anime and wanna know what to watch next.
No recommendations inside viewAnime.

> is uncomfortable to navigate in some way
Also yes.
- If I'm in a viewanime page open I cannot easily search for another anime without having to quit viewAnime and go back to Home Page to search, this adds a few clicks and is annoying to the point I simply don't use anything anilist related on Miru, specially when you can't press ESC to quit an animeView unless you select the animeView page with mouse.
- I can't go to Home Page and start typing right away to search something.
- Having to type the year when searching by season. If I'm gonna use the mouse to manually click the season box, might as well stay with the mouse instead of switching to keyboard.
![image](https://user-images.githubusercontent.com/40826732/177359371-9ae7a53b-58ab-4b1c-b64e-984c50d799d2.png)
Could have an option in settings to switch from typing to dropdown.

**Comment by ThaUnknown** [comment]
YES YES YES
> I didn't like the anime, wanna drop it.

you can, but I guess it's not.... how you expect it to be, it just removes it from the list, needs more work
> LN

nah....
> character

not sure tbh

> friends watching

yes! will do.
> recommendations

yes yes yes! issue is AL themselves recommendations have issues, but I'll add it regardless

Navigation:
This is how I interpret the issues you're having and how I'd solve them
> navigation

I'd like to keep in an overlay, its not the best, but I honestly don't know of a better way to design it without backwards state handling.... yucky! I'll resolve the ESC stuff
> hope page typing

autofocus... yes will do!

> year

this one is harder to solve, as i use only built-in form stuff, but I have an idea on how to do it
I think navigating this entire thing with only keyboard via tab and arrows would be nice too, so i'll add that too

does this seem okay? or would you still think something is unreasonable or doesn't solve the underling feature?

**Comment by Muril-o** [comment]
> does this seem okay? or would you still think something is unreasonable or doesn't solve the underling feature?
lgtm

**Comment by ThaUnknown** [comment]
27ac5cf0e8e483d508fef489e5d2eb01db2e2e84
