### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Dhyvik** [ThaUnknown/miru#192]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v2.7.0

### What operating system version are you using?

Windows

### Expected Behavior

failed feetching rss

### Actual Behavior

when i am trying to watch anime its showing failed fetching rss

### Screenshots

![Screenshot (35)](https://user-images.githubusercontent.com/99262398/175809907-b0ded7c6-c420-465b-ad5f-ae68bc856d30.png)

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/miru/blob/master/docs/faq.md#why-is-anime-x-not-playing
