### ISSUE TITLE
[Bug]: arabic subtitles not showing properly 

### ISSUE THREAD

**Issue by ml7os305** [ThaUnknown/miru#207]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v3.1.2

### What operating system version are you using?

Windows

### Actual Behavior

arabic subtitles appears as square pls fix it

### Screenshots

![image](https://user-images.githubusercontent.com/111669272/185772352-19e7c78b-3613-432a-9229-65b3ae3201c7.png)

**Comment by ThaUnknown** [comment]
this is the fault of the torrent, not miru. they provided no fonts for the video, and you're watching it in Chinese, I recommend you switch to English
