### ISSUE TITLE
[Other]: Cant install via pacman (Arch Steam Deck).

### ISSUE THREAD

**Issue by Senseal** [ThaUnknown/miru#213]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

im probably being stupid here as this is my first time using an arch distro but I cant seem to install the app with the pacman package manager.

here is what i get out of terminal  

`(127)(A+)(root@Senseals-Deck deck)# pacman -S miru-bin
error: target not found: miru-bin
`

I am running it in root and I have enabled Read/Write in terminal as that is disabled on the steam deck.

### Proposed Solution

you tell me im probably just being stupid here

**Comment by Muril-o** [comment]
> im probably being stupid here as this is my first time using an arch distro

Yes, [miru-bin](https://aur.archlinux.org/packages/miru-bin) is an [AUR](https://wiki.archlinux.org/title/Arch_User_Repository) package.
The arch package manager (pacman) doesn't support AUR packages by default for obvious reasons as stated [here](https://bbs.archlinux.org/viewtopic.php?pid=828238#p828238):
> - It's too dangerous for users who don't understand the concept of AUR.
> - It is USER SUPPLIED CONTENT, with no form of quality control or review process. As opposed to official packages provided by distribution devs, and *trusted* users.
> - It would be improper to officially provided automated methods to install user content that could do anything to your system. Use of the 'makepkg' tool is official, but it's a totally different process to reinforce the distinction between the 2 types of 'packages'
> - Finally, the AUR is Arch specific. pacman is not distribution specific. The pacman developers will not accept distribution specific features.

You need an [AUR helper](https://wiki.archlinux.org/title/AUR_helpers) such as [paru](https://github.com/morganamilo/paru#installation) or [yay](https://github.com/Jguer/yay#source) to install AUR packages such as [miru-bin](https://aur.archlinux.org/packages/miru-bin).

You can technically clone the miru-bin package from the AUR and build it yourself too, which is the safest way (but won't provide automatic updates). I suggest you read more about what [AUR](https://wiki.archlinux.org/title/Arch_User_Repository) is and what [AUR helpers](https://wiki.archlinux.org/title/AUR_helpers) are.

I'll still provide you a nobrainer terminal so you can just execute these and run miru, but I highly suggest you reading more about the above info.

```bash
sudo pacman -S --needed base-devel
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si
paru -S miru-bin
```
