### ISSUE TITLE
[Bug]: Nothing loads inside on Miru - graphql requests to anilist 429

### ISSUE THREAD

**Issue by xTheEc0** [ThaUnknown/miru#224]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v3.1.21 Windows x64

### What operating system version are you using?

Windows

### Expected Behavior

Miru opens -> Anime info loads

### Actual Behavior

Blank objects

### Screenshots

![image](https://user-images.githubusercontent.com/24303281/201525177-3235bfb9-858b-446c-b7e7-f595ddb0fd8e.png)
![image](https://user-images.githubusercontent.com/24303281/201525196-5064c48b-65ee-488f-a56d-f5d6c7d2f5e4.png) ![image](https://user-images.githubusercontent.com/24303281/201525209-60461550-e387-46c9-8932-647c75f4ae7a.png)

**Comment by ThaUnknown** [comment]
as per #announcements channel, AniList is dying, they are having some server issues and are rate limiting everything to shit
