### ISSUE TITLE
[Bug]: Trying to play any JJK episode playes the movie instead 

### ISSUE THREAD

**Issue by EnokiUN** [ThaUnknown/miru#227]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v3.3.6

### What operating system version are you using?

Linux

### Expected Behavior

For it to open the requested JJK episode

### Actual Behavior

It plays JJK 0, the movie

**Comment by ThaUnknown** [comment]
settings > auto-play torrents > off
then select movie manually
