### ISSUE TITLE
[Feature Request]: Customizable sub fonts

### ISSUE THREAD

**Issue by Y3flamex** [ThaUnknown/miru#228]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

When i was watching serial experiments lain, i had to watch in dub because the font was hard to read. 

### Proposed Solution

Add a fonts section to the subtitles settings

**Comment by ThaUnknown** [comment]
@Y3flamex this needs to be a bit more specific, was it the font, or was it the subtitle styling?

**Comment by sleepntsheep** [comment]
+1, the default font doesn't support my language

**Comment by ThaUnknown** [comment]
> +1, the default font doesn't support my language

this is the releaser's fault, not Miru's, they include fonts which don't have specific glyphs, NCRaws is a notable example

**Comment by Y3flamex** [comment]
> @Y3flamex this needs to be a bit more specific, was it the font, or was it the subtitle styling? aka was it the letter shape, or stuff like letter size, width, spacing and outline

it was the font itself, letter shape

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/miru/commit/a19920729fe52247a5bf8adfefff770aa3bd3289

**Comment by ThaUnknown** [comment]
this implements custom default fonts, but it will rarely actually be used, you really gotta find a fucked up torrent for it to use a custom default font
