### ISSUE TITLE
[Feature Request]: Disable Updates

### ISSUE THREAD

**Issue by MataMercer** [ThaUnknown/miru#232]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

This app keeps breaking for me in various ways every recent update. I would like to stay on a stable version without being forced to update.

### Proposed Solution

Add a toggle in settings to disable automatic updates.

**Comment by ThaUnknown** [comment]
then report the issues that break, I will never disable automatic updates
