### ISSUE TITLE
[Feature Request]: DirectInput support

### ISSUE THREAD

**Issue by Y3flamex** [ThaUnknown/miru#233]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Miru is great, its completely replaced any other anime app i have on my laptop. But i have a home media station in my living room so i cant use it unless i use a keyboard and mouse which takes away a lot of the convenience

### Proposed Solution

Dinput support would allow you to select items on the home screen without the need for a keyboard and mouse 
![image](https://user-images.githubusercontent.com/89700409/210182975-40c4bda4-f7e0-47c0-ad03-2a6423008eca.png)
highlighting could be like this

**Comment by ThaUnknown** [comment]
so you mean navigating with only a keyboard?

**Comment by ThaUnknown** [comment]
@Y3flamex you're gonna need to elaborate a bit more, I can't find much about Dinput/DirectInput support for web, so I'm not sure what to look for, is it like smart tv remotes? like google cast remote?

**Comment by Y3flamex** [comment]
sorry for the wait! I mean navigation with a remote, or more commonly a gamepad like a ps4 controller; both which use Dinput. Its supported on websites like https://gamepad-tester.com/

**Comment by ThaUnknown** [comment]
shiiiit, this is gonna be hard, as browser's don't have baked in support for this

**Comment by ThaUnknown** [comment]
https://user-images.githubusercontent.com/6506529/211029868-abef5f43-7b89-421a-ac8d-7d6ae9758c12.mp4

I've implemented some rudimentary keyboard navigation support using the tab key, no clue if this actually helps with navigating with a remote, check if this works [v3.5.5]

I don't think I'll go much further than this, as gamepad and remote controllers have full 360 analog navigation, which means you need to fucking calculate the angles at which the user wants to move, and honestly it's way too much work for me to implement something like that, I'd spend like 2 months just for like 2 users to be able to use it, kinda not worth it

Tell me if this works in any way, if it does I'll also add it to the video player

**Comment by Y3flamex** [comment]
yea it works perfectly!

**Comment by ThaUnknown** [comment]
> yea it works perfectly!

any chance u could go into more detail? can you like go up/down/left/right etc? or is it just "go next" "go next" "go next" like on my video?

**Comment by Y3flamex** [comment]
> > yea it works perfectly!
> 
> 
> 
> any chance u could go into more detail? can you like go up/down/left/right etc? or is it just "go next" "go next" "go next" like on my video?
> 
> 
> 
> ofc I'm talking about gamepad/remote navigation not keyboard navigation
> 
> 
> 
> also if you could tell me how the fuck u ran miru on a tv or whatever, that would be nice, could add that to the list of supported features and capabilities 

i ran miru on tv by having a desktop in my living room, i didnt port it sadly though i bet that if i had any experience it wouldnt be hard to port to android 

its just go next, like discord does it, it would be cool if you could add another way to choose

**Comment by ThaUnknown** [comment]
this is mostly implemented with keyboard navigation using tab/shift+tab
