### ISSUE TITLE
[Bug]: Fails to load pages

### ISSUE THREAD

**Issue by MataMercer** [ThaUnknown/miru#234]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

3.5.2

### What operating system version are you using?

Windows

### Expected Behavior

App should load anime series  data on pages

### Actual Behavior

Content on pages is constantly buffering and there is an unauthorized message in the corner. This started happening after updating. Reinstalling the app does not fix it.

**Comment by ThaUnknown** [comment]
relog from anilist i guess

**Comment by MataMercer** [comment]
I can't get to the login page. Clicking the log in button does nothing. I don't have an account to begin with.

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/miru/commit/00cb3deca093373a8fe48bbc3b1dd040de1d944c
the update will be out in ~5-10 minutes
