### ISSUE TITLE
[Bug]: Subtitles styling incorrectly

### ISSUE THREAD

**Issue by CrepeTF** [ThaUnknown/miru#235]
### Preflight checklist

- [x] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

3.5.3

### What operating system version are you using?

Windows

### Expected Behavior

VLC player subtitles comparison
![image](https://user-images.githubusercontent.com/70870719/210286973-6f53ea83-c7b1-4afd-b085-07879b7b909f.png)

### Actual Behavior

Miru subtitles
![image](https://user-images.githubusercontent.com/70870719/210286992-66f99114-6cb1-4755-bb28-f2a79384998e.png)

We copy and pasted the magnet link into Miru and found that the styling of the subtitles were amiss.
Nyaa.si link: view/1541115

Enabling "Find missing fonts" did not fix this issue.

**Comment by ThaUnknown** [comment]
what the fuck lol

**Comment by CrepeTF** [comment]
I assume it can't load the styling due to some reason and it just defaults to that

**Comment by ThaUnknown** [comment]
nah, when exporting the subtitles and rendering them standalone it works fine, its just something fucked with the subtitle streaming implementation

its funny because the typesetting works, but normal dialogue doesnt

**Comment by ThaUnknown** [comment]
wow, its incredible this went unnoticed for so long!
https://github.com/ThaUnknown/miru/commit/63d088710d77b06321ecbfc3f6b0f62fe9dd3c69
