### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by rubanunes** [ThaUnknown/miru#237]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

3.5.3

### What operating system version are you using?

Windows

### Expected Behavior

Click on Login with AL should open something.

### Actual Behavior

Clicking makes no action. Expected a page on a browser but get nothing.

**Comment by ThaUnknown** [comment]
![image](https://user-images.githubusercontent.com/6506529/210670151-d90ff393-072f-4459-adea-09366c855fe6.png)
this is definitely an issue with your operating system or browser config, not an issue with Miru,

**Comment by rubanunes** [comment]
Yeah thanks. Same browser but different installation path did that. Just checked Win default app and resolved that. Thanks
