### ISSUE TITLE
[Bug]: Miru loads wrong series

### ISSUE THREAD

**Issue by DoktorAco** [ThaUnknown/miru#238]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v3.5.3

### What operating system version are you using?

Windows

### Expected Behavior

If I click on watch Demon Slayer Mugen Train Arc it will load Demon Slayer Mugen Train Arc.

### Actual Behavior

If I click on watch Demon Slayer Mugen Train Arc it loads Demon Slayer Season 1

**Comment by ThaUnknown** [comment]
this is common, disable autoplay torrents in settings and select a release manually
