### ISSUE TITLE
[Bug]: Discord RPC not working

### ISSUE THREAD

**Issue by alsoGAMER** [ThaUnknown/miru#240]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v3.5.5

### What operating system version are you using?

Linux

### Actual Behavior

Discord RPC is not working and as far as the discord client is concerned, miru isn't even trying to set any activity.

**Comment by ThaUnknown** [comment]
> miru isn't even trying to set any activity

I wonder what you based that assumption on

If it's a release that's named like shit like some MTBB releases miru wont resolve it and wont put any metadata, also try restarting discord and miru

**Comment by alsoGAMER** [comment]
> I wonder what you based that assumption on

I checked discords' developer tools console, if there's an application that is interacting with the client via the ipc server or the websocket url, it logs everything that application is sending to the client, and Miru sent literally nothing.

**Comment by ThaUnknown** [comment]
then try wit ha different torrent

**Comment by alsoGAMER** [comment]
I restarted Miru and discord once more and now it's working properly, i don't know what caused the issue in the first place, but it seems like it fixed themself.
![image](https://user-images.githubusercontent.com/35269770/211172448-761ec17a-7274-4847-8ce3-86a84cea8a2c.png)

Sorry for wasting your time, keep up with the amazing work!
