### ISSUE TITLE
[Feature Request]:  Advanced filtering

### ISSUE THREAD

**Issue by br34kp0int** [ThaUnknown/miru#241]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Filtering by multiple genres for people who want to watch new anime. I can see that there are multiple genres in many animes.

### Proposed Solution

There is an advanced filtering menu in Anilist.

![image](https://user-images.githubusercontent.com/115947512/211366979-a2a0fe3c-a568-4f55-b93a-3d2495c9abc1.png)

**Comment by ThaUnknown** [comment]
yeah I thought about it and uuuuh I kinda cant be bothered xd that advanced search is rarely ever needed anyways
