### ISSUE TITLE
[Feature Request]: Allow text selection of anime title (for copy)

### ISSUE THREAD

**Issue by grey-C47** [ThaUnknown/miru#242]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Currently, you cannot copy the title or anything else from an anime's page. If you want to send the title to a friend or google it, you have to use the "Open" button and then copy it from the webpage you've directed to (or type it by hand..).

### Proposed Solution

Allow seleciton of text at least on the anime's page, the most important to me would be the title but synopsis and details would be nice (alternative titles notably).

Anyway, thank you for making this program, it's great.

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/miru/commit/d119243ad2a54b1e6a1792fd00bc88d66d2fc56f
