### ISSUE TITLE
[Bug]: Unable to find/load anime due to (potentially?) a "♀" symbol in title

### ISSUE THREAD

**Issue by xTheEc0** [ThaUnknown/miru#245]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v3.7.0

### What operating system version are you using?

Windows

### Expected Behavior

Attempting to play `Eiyuu-ou, Bu wo Kiwameru Tame Tenseisu: Soshite, Sekai Saikyou no Minarai Kishi♀` from app loads torrent/video

### Actual Behavior

It fails to find it (even with auto-play off)
![image](https://user-images.githubusercontent.com/24303281/212767263-7a35be53-9da8-48fe-81ad-278bd8352d1a.png)

possibly because the torrent names don't have the 'sex' symbol ?
torrent name example: 
`[Erai-raws] Eiyuu Ou, Bu o Kiwameru Tame Tenseisu - Soshite, Sekai Saikyou no Minarai Kishi - 02 [1080p][Multiple Subtitle] [ENG][POR-BR][SPA-LA][SPA][ARA][FRE][GER][ITA][RUS]`

at the moment i worked around this by pasting magnet url into miru

### Screenshots

![image](https://user-images.githubusercontent.com/24303281/212767607-fac489b7-af4f-43ab-8a77-19a2a0d96271.png)

**Comment by ThaUnknown** [comment]
fixed by submitting synonyms to anilist
