### ISSUE TITLE
[Feature Request]: Progress Counter

### ISSUE THREAD

**Issue by LoyTakian** [ThaUnknown/miru#246]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Currently I don't have much time to watch anime everyday, so usually I check if there's new episodes every other week.
Because of that I have an extensive list in my "Currently Watching" category and would love to see how many episodes are left in all series for me to watch, without the need for opening every anime page and checking manually.

### Proposed Solution

So I would love to see some kind of **Progress Bar/Counter** like the former Aniwatch and Animix had.
Here's a screenshot of how it looked like in Aniwatch:
![image](https://user-images.githubusercontent.com/21325868/212782435-3bee07ee-b941-4750-861f-d0689b5dc488.png)

And here is a "sketch" of how it would look like in the Miru app:
![image](https://user-images.githubusercontent.com/21325868/212781422-dd1a3414-494a-4bde-bb55-40a5e40b0be9.png)

It would save me a lot of time and make my experience way better!

Thank you.

**Comment by ThaUnknown** [comment]
good idea, but I dont think thats how I'd show the progress, I'll think about how to make it look nice

**Comment by ThaUnknown** [comment]
![image](https://user-images.githubusercontent.com/6506529/231759975-e73e82f7-2cf0-44f8-a964-4140c9cf0924.png)
![image](https://user-images.githubusercontent.com/6506529/231762667-d5a3ecfb-bd94-4e40-818a-8b3b509ce688.png)
