### ISSUE TITLE
[Bug]:  Settings : Player : Playback Settings > Autoplay Next Episode toggles "Find Missing Fonts" instead

### ISSUE THREAD

**Issue by meesterexx** [ThaUnknown/miru#247]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

3.7.0

### What operating system version are you using?

Windows

### Expected Behavior

Toggling Autoplay Next Episode should turn it's switch on or off

### Actual Behavior

Toggling Autoplay Next Episode toggles Find Missing Fonts switch instead. Find Missing Fonts switch appears to work as it should, So, visibly, I can't enable or disable autoplay next episode, it's stuck on whatever it's current setting is. My existing install on my desktop is stuck on autoplay off. I did a new install on my mini pc and it is stuck on autoplay on.

**Comment by ThaUnknown** [comment]
ah yeah this is already fixed, i just havent released the new version XD

**Comment by meesterexx** [comment]
That was fast, Thanks!!

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/miru/commit/c474ecd44715a23b13de9f258b907265308d7fe1
