### ISSUE TITLE
[Bug]: NieR has no episodes

### ISSUE THREAD

**Issue by xTheEc0** [ThaUnknown/miru#248]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v3.7.2

### What operating system version are you using?

Windows

### Expected Behavior

The 3 (currently) released episodes of NieR are viewable.

### Actual Behavior

App says 'Continue 0'
There is no episode list at the bottom.

My guess is because parsing got messed because of the 'Ver1.1a' ?

### Screenshots

![image](https://user-images.githubusercontent.com/24303281/213942228-500fd56f-efab-4b48-a056-720153fd4049.png)
![image](https://user-images.githubusercontent.com/24303281/213942239-5b80bf86-e751-4623-96cc-0f0aea79525b.png)

**Comment by ThaUnknown** [comment]
heh, anilist bug, don't think I can do anything about it as that flat out just renders anilist data, so it's reporting 0 episodes

**Comment by ThaUnknown** [comment]
yeah this is an anilist bug that I can't do anything about, as nier doesn't have a count of total episodes, and doesn't have any planed episodes so I can't know how many episodes it actually has
