### ISSUE TITLE
[Feature Request]: Better text selection

### ISSUE THREAD

**Issue by Temanor** [ThaUnknown/miru#249]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

I originally posted this in the feedback channel on discord, but deleted it because of a typo just to realize I had to wait 6 hours to post it again.

Text selection selects the whole text and does not allow you to only select parts of it
Not a big deal, but it would be nice to see implemented.

### Proposed Solution

Letting users select certain parts of a text instead of the whole thing.

https://user-images.githubusercontent.com/91745601/214164938-6fc4830f-b0c4-4876-8075-775f7dbfb00c.mp4

**Comment by ThaUnknown** [comment]
I don't really feel the need to do this, I feel like people will more often want to copy the entire text, rather than just 1 part of it, and even if they do want to do that in some rare case they can just paste it say to discord and remove the parts they don't want

**Comment by Temanor** [comment]
That would be very unnecessary, but I don't know how long it would take to fix this, so I am not going to argue.
