### ISSUE TITLE
[Bug]: Picture in Picture Red on Mouse Hover

### ISSUE THREAD

**Issue by domainus** [ThaUnknown/miru#250]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v3.7.2

### What operating system version are you using?

Windows

### Expected Behavior

Picture in Picture displays an overlay showing controls to pause, fast forward, go back, and exit picture in picture

### Actual Behavior

When mousing over to view the controls, it displays red, however, you can still interact with the buttons to pause, close, ffw, etc.
![mirupip](https://user-images.githubusercontent.com/83792502/214748014-a4ab1116-7b6a-462c-9f69-103de0deca60.gif)
.

**Comment by ThaUnknown** [comment]
this is an electron bug which i can't fix

**Comment by ThaUnknown** [comment]
this was fixed
