### ISSUE TITLE
[Bug]: Floating player loading on first launch

### ISSUE THREAD

**Issue by po5** [ThaUnknown/miru#256]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v3.7.2

### What operating system version are you using?

Linux

### Expected Behavior

When launching miru for the first time, there should be no loading icons once the app is ready.

### Actual Behavior

When launching miru for the first time, the floating player in the bottom right corner keeps loading until a video is played.
It should be empty, or appear only when relevant.

### Screenshots

![image](https://user-images.githubusercontent.com/42466980/217385372-30806453-dd3c-4016-89b8-a6a21a871edc.png)

**Comment by Muril-o** [comment]
I believe this was introduced on v3.1.13 in the autoplay fix.
5f022b3209d72b2e64ce179237f2926cce966c5f
