### ISSUE TITLE
[Feature Request]: Add default subtitle track/audio track option in settings.

### ISSUE THREAD

**Issue by wilyub** [ThaUnknown/miru#260]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

I want to turn off subtitles by default.

### Proposed Solution

Add an option in player settings that lets you select a track number for subtitles/audio as the default option for the player.

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/miru/commit/547100a8359ef216ed5b7b8224a4e8f497904867
