### ISSUE TITLE
[Bug]: There is a duplicate (empty) 'New Releases' tab on main page

### ISSUE THREAD

**Issue by xTheEc0** [ThaUnknown/miru#261]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v3.8.1

### What operating system version are you using?

Windows

### Expected Behavior

No dupe UI

### Actual Behavior

Dupe UI

### Screenshots

It tries loading it
![image](https://user-images.githubusercontent.com/24303281/228055874-626ac926-f8bc-48cb-b066-f5d1babb22b3.png)

But fails, and then theres just empty header
![image](https://user-images.githubusercontent.com/24303281/228055958-06e0f1f2-221c-4e71-8db7-3f0559068201.png)

**Comment by ThaUnknown** [comment]
I [hope] this is caused by user error, visit settings to remove the duplicate RSS feed, the URL is likely invalid

**Comment by xTheEc0** [comment]
Can be closed, as it was skill issue.
Or do you want to keep this as reminder to improve some UI/UX, that each RSS feed creates new 'New Releases', and if it's entered wrong it will fail to load but still show an element etc?
