### ISSUE TITLE
[Feature Request]: Change DNS server Internally

### ISSUE THREAD

**Issue by uzuto** [ThaUnknown/miru#265]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

nyaa.si is blocked in many countries like mine, to unblock it we have to use **VPN** _(What most people do)_ but for those who can't afford VPN _(like me)_ rely on **DPI circumventation + DNS utilities.**

### Proposed Solution

As Miru is based on Electron, changing **_DNS server internally like browsers_** will be a great help and people won't have to mess with their system settings.

**Comment by ThaUnknown** [comment]
browsers don't allow you to set a custom DNS, only a custom DoH aka dns over http[s], which is the only thing I'm willing to implement

**Comment by ThaUnknown** [comment]
blindly implemented in https://github.com/ThaUnknown/miru/commit/4da32544930166c4de0d1f27c81395f0a5bb5f5e tell me if this even works, the initial "nyaa blocked" screen might still appear

DoH is in RSS settings, the entire settings UI needs a revamp

**Comment by uzuto** [comment]
Works fine! Thanks.
