### ISSUE TITLE
[Feature Request]: Allow seek interval for arrow keys to be changed from 2 seconds

### ISSUE THREAD

**Issue by justaguyonthehub** [ThaUnknown/miru#266]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

In most of my video players I prefer to have the arrow keys seek by 5 seconds. Only while using Miru do I have to remember to hold the arrow keys to seek instead of tapping, because of the short 2 second seek interval.

### Proposed Solution

Please allow for the changing of the interval used when seeking with the arrow keys. Ideally, by setting the amount of time skipped using milliseconds.

**Comment by ThaUnknown** [comment]
Miru had this, and I removed it as I deemed it unnecessary, 5s skips too much dialogue, so for single presses it skipped too much, and if you wanted to skip more than 5s you'd be better off using the seekbar or the S [intro skip] key to seek 1min 30s, if you feel this is required then follow up, but if you want to rush tru anime like that i recommend you watch it at x2 speed or smth `[` and `]` keys to increase playback speed

**Comment by justaguyonthehub** [comment]
I don't use it to skip ahead, I use it to go back whenever I feel like I didn't read and/or listen to the dialogue properly. I'm a pretty fast reader so usually I'm able to read the subtitle quickly then listen to the dialogue, but sometimes the subtitle has more words in it than usual and I need to go back a line, or maybe I feel like I _read_ the subtitle and I _heard_ what the character said, but I didn't really take it into my brain (or something.) Sometimes I just go back because I heard a Japanese word that I want to look up.

Anyway, my issue is that 2 seconds is not enough to go back a whole line of dialogue. Usually it's only a couple of words at most. When I press back (5s), I want to hear the beginning of the line, and sometimes a line is so long I press it twice (10s). It is the same in all the websites I use, and all my offline my players on my both my PC and my phone. Miru breaks this, because I end up pressing back once, only to realize that I have to spam it to go back further. Like I said, I want to end up at the beginning of the line, not at the last word I just heard.

Overall, even if you disagree with my reasoning and you like keeping it at 2s, I don't really see an issue with letting the user choose how far they want to skip forwards and backwards, and I don't think the option would take up too much space in the options tab.

I hope you reconsider adding this feature because Miru is now the main way I watch currently airing shows, and this little discrepancy has been bugging me for a few months now. Thanks for your continued development.

(Sidenote: I also use my PC with my PS4 controller through Steam input, and I have my bumpers set as Left and Right arrow; I never really touch the seekbar.)

**Comment by that1cutie** [comment]
Please let the user choose their preference instead of removing that possibility altogether
