### ISSUE TITLE
[Bug]: Error parsing Peertube feeds

### ISSUE THREAD

**Issue by RasheedAZ** [ThaUnknown/miru#273]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v3.10.4

### What operating system version are you using?

Linux

### Expected Behavior

Expect to see videos from the RSS feeds as they contain torrent links. For example:

https://tilvids.com/feeds/videos.xml?accountId=252

https://framatube.org/feeds/videos.xml?accountId=8178
 

### Actual Behavior

Displays an error message: "Ooops! Looks like there's nothing here."

### Screenshots

![Screenshot from 2023-05-12 08-34-03](https://github.com/ThaUnknown/miru/assets/16827461/0fd839e8-02e4-402d-b587-220386800b21)
![Screenshot from 2023-05-12 08-34-44](https://github.com/ThaUnknown/miru/assets/16827461/0fb4f16b-c05e-433d-9f1b-eb6a59a7a376)

**Comment by ThaUnknown** [comment]
you put URL in the title, and title in the URL, swap them mate

**Comment by ThaUnknown** [comment]
those feeds are for some video sites, they dont provide magnet or torrent links

**Comment by RasheedAZ** [comment]
> you put URL in the title, and title in the URL, swap them mate

Oh sorry. I thought "Subs" meant subtitle source or something.

**Comment by RasheedAZ** [comment]
> 

![Screenshot from 2023-05-12 08-45-56](https://github.com/ThaUnknown/miru/assets/16827461/2bd656e0-d246-48df-832a-0e96c7bcd561)

**Comment by RasheedAZ** [comment]
> those feeds are for some video sites, they dont provide magnet or torrent links
> 
> sorry they do have torrent links, but not in the standard torrent RSS format, so it wont work

Would be great if you could support it if possible when you get time as there's no Peertube desktop client yet. Also, it might exclude Miru from being considered an app solely for streaming pirated content which may be illegal in many places.

Thanks.
