### ISSUE TITLE
[Feature Request]: Bring playback speed adjuster upto 4x

### ISSUE THREAD

**Issue by ASTA-GIT** [ThaUnknown/miru#275]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Please add playback speed adjuster right now there is no option to adjust that, anime can be only watched in 1x.

### Proposed Solution

i've no idea how this works but please bring this feature

![image](https://github.com/ThaUnknown/miru/assets/133566765/a80828d7-9f25-4bc3-9e8b-99626116011e)

**Comment by ThaUnknown** [comment]
you can adjust speed with [ and ] and reset with \, if you open the keybinds UI in the player with \` or on the top right `?` button you can rebind those keys
