### ISSUE TITLE
[Bug]: Discord invite embed not joinable

### ISSUE THREAD

**Issue by CrepeTF** [ThaUnknown/miru#277]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v3.10.4

### What operating system version are you using?

Windows

### Expected Behavior

Should be able to join Miru lobby through "game invite" embed on discord

### Actual Behavior

The join button is greyed out and cannot be pressed even when not in another lobby.

### Screenshots

![uoooohhh](https://github.com/ThaUnknown/miru/assets/70870719/620d2e4d-b4a3-4ae3-966e-aaa8481013c9)

**Comment by ThaUnknown** [comment]
fixed in 3.10.5 ty for the report

**Comment by CrepeTF** [comment]
Seems the issue popped back up again
