### ISSUE TITLE
[Bug]: error: Nothing matches io.github.thaunknown.miru in remote flathub

### ISSUE THREAD

**Issue by abhinvsainii** [ThaUnknown/miru#283]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

3.11.6

### What operating system version are you using?

Linux

### Expected Behavior

install

### Actual Behavior

![Screenshot 2023-06-03 9 19 28 PM](https://github.com/ThaUnknown/miru/assets/130820050/082f3ae8-2ac5-4371-a421-f9ad923b50f9)

### Screenshots

![Screenshot 2023-06-03 9 19 28 PM](https://github.com/ThaUnknown/miru/assets/130820050/d3d119ae-188a-4400-abdd-ae08e82a2e9b)

**Comment by Muril-o** [comment]
I cannot reproduce this.
![image](https://github.com/ThaUnknown/miru/assets/40826732/ced255a9-1067-467c-9120-96aa286be9b0)

Which architecture are you on?
