### ISSUE TITLE
[Bug]: Anime suddenly drops to 0 peers, 0 download and 0 upload

### ISSUE THREAD

**Issue by Grafcube** [ThaUnknown/miru#284]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v3.11.6

### What operating system version are you using?

Linux

### Expected Behavior

Video plays normally.

### Actual Behavior

After some amount of time, the peers, download and upload indicator shows 0 (even on a currently popular anime) and shortly after that it starts buffering indefinitely. The workaround I found was to use CTRL+R to refresh and then search and play the anime again. This is only a temporary fix since the issue reappears after some time.

This occurs even on an ISP that does not do DPI.

### Screenshots

![image](https://github.com/ThaUnknown/miru/assets/34889224/09149c8c-c7e0-4eb6-ac99-794d0c0c9ea1)

**Comment by ThaUnknown** [comment]
hm, all I can suggest is to open the hidden process devtools by running `IPC.emit('devtools')` in `ctrl+shift+i` console when the console is popped out:
![image](https://github.com/ThaUnknown/miru/assets/6506529/83307bd4-557f-41c9-a65c-d1f17829899f)
that will open the hidden console:
![image](https://github.com/ThaUnknown/miru/assets/6506529/2e860914-ce51-4be3-8b4b-242d82e13a7b)
if there are no errors there then this is an issue with your network connectivity:
webtorrent doesn't recover from a network reset, so if your network resets or changes you will need to restart the torrent like you mentioned by reloading the window

**Comment by Grafcube** [comment]
This error showed up at the exact moment the indicators showed 0
```
Uncaught Error: ENOSPC: no space left on device, write
```
![image](https://github.com/ThaUnknown/miru/assets/34889224/996b205a-647b-41a6-add4-90d2aa178863)

**Comment by ThaUnknown** [comment]
your C drive ran out of space, lol, go to settings, torrents and change download folder

**Comment by ThaUnknown** [comment]
![image](https://github.com/ThaUnknown/miru/assets/6506529/f1a7579c-6810-4d93-8ac3-3b0667577539)

**Comment by Grafcube** [comment]
Well, that seems to have done the trick (the video hasn't been playing long so if it happens again I'll post here).

But that's strange, I have plenty of free space on my drive :thinking: where are torrents normally saved?

**Comment by ThaUnknown** [comment]
> Well, that seems to have done the trick (the video hasn't been playing long so if it happens again I'll post here).
> 
> But that's strange, I have plenty of free space on my drive 🤔 where are torrents normally saved?

on linux its `/tmp` by default
