### ISSUE TITLE
[Bug]: Fix discord icon and RPC control in settings.

### ISSUE THREAD

**Issue by kyngs** [ThaUnknown/miru#287]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v4.1.2

### What operating system version are you using?

Linux

### Expected Behavior

Here's how it looks on commit a13f4b3b9e93fd9f1f331b2ee7cdea3b21a8e306
![image](https://github.com/ThaUnknown/miru/assets/38181667/11af334a-e17a-4224-baff-a9c0876ea0e8)

### Actual Behavior

Apparently, the icon has somehow changed since my original PR:
Here's how it looks now on the latest commit (98beb4e8e48a04f94372f2c67f4686fd9a7a4a64)
![image](https://github.com/ThaUnknown/miru/assets/38181667/876253d4-6321-41db-a28b-e1c69cb86b30)
changed

PS: I know that I'm not running the latest stable version of the app, but I couldn't create the issue without checking it.

**Comment by kyngs** [comment]
Also, there are no window decoration buttons (close, minimize, maximize), but I guess that's an issue on its own.

**Comment by kyngs** [comment]
It appears that the discord RPC feature is not working anymore. Toggling the switch does change the local storage state, however, currently, it has no effect.

**Comment by ThaUnknown** [comment]
im using material-symbols not material-icons now as icons is deprecated, and it doesnt have a discord logo anymore

lack of window controls sounds like a linux issue, idk why

i didnt touch the discord controls

**Comment by kyngs** [comment]
> im using material-symbols not material-icons now as icons is deprecated, and it doesnt have a discord logo anymore
hm
> lack of window controls sounds like a linux issue, idk why
weird
> i didnt touch the discord controls
perhaps by accident? see the commit i linked above

**Comment by ThaUnknown** [comment]
ah whoops i fucked that discord commit, very oops

**Comment by kyngs** [comment]
By the looks of it, I guess you had a merge conflict and rejected the changes from remote?

Anyways, do you think you'll be able to fix it?

**Comment by ThaUnknown** [comment]
yes but not soon

**Comment by kyngs** [comment]
:(

**Comment by kyngs** [comment]
Closed due to #290
