### ISSUE TITLE
[Bug]: Video blank screen, audio still plays

### ISSUE THREAD

**Issue by Hew-ux** [ThaUnknown/miru#288]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v3.11.6

### What operating system version are you using?

Linux

### Expected Behavior

Video plays normally.

### Actual Behavior

Video plays, but only as a blank screen. Audio is still played correctly.
This behaviour was exhibited on Fedora 38 (with rpmfusion on and codecs downloaded) using the flatpak install of Miru.
This seems to happen to any anime watched, I've tested three or so different ones including [this](https://anilist.co/anime/550/YuGiOh/watch) and [this](https://anilist.co/anime/151801/MASHLE-MAGIC-AND-MUSCLES/).
Settings are all default, as far as I'm aware.
Edit: I've done some more testing and have found certain anime do play correctly *if* the only thing you do is start Miru and then immediately click on one of the anime on the home page. If you click into the details of the anime or manually paste in a torrent link, it exhibits the blank screen. Some anime though, like the Yugioh example, will always fail to play no matter which method is used. Because of that, I suspect that this issue is only affecting *certain* video formats and not others.

### Screenshots

![image](https://github.com/ThaUnknown/miru/assets/67527064/ebf6e828-9612-4cfc-89eb-d264cca7c304)

**Comment by ThaUnknown** [comment]
this a case of "linux issue" tracking down which is a massive pain, and waste of time, it sounds like for some reason the in-browser video decoder fails, you might be able to check why specifically if you go to dev tools [Ctrl + shift + i] then ..., more tools > media and look for any decoder errors

**Comment by Hew-ux** [comment]
![image](https://github.com/ThaUnknown/miru/assets/67527064/ac551d18-b8f1-4182-9020-0f8b77b699f3)
![image](https://github.com/ThaUnknown/miru/assets/67527064/f65f69fb-f65c-4aa4-b275-f7882a317e76)

`DEMUXER_ERROR_COULD_NOT_OPEN: FFmpegDemuxer: open context failed` seems to be the related error. This may just be an incompatible format to the decoder used. Let me know if you want to open any of those drop-downs.

In the meantime, I'm going to try reinstalling and clearing program files.

**Comment by ThaUnknown** [comment]
I don't know what to tell you

this isn't Miru's fault, as you can see in the first screenshot you don't have a video decoder, and since you screenshotted console, not the media event log I have no clue why, it could be that it picks a hardware decoder and your amazing linux distro doesn't handle hw accell media decoding, or something along those lines, if I was you i'd google `chromium/chrome video playback sometimes not working`

**Comment by Hew-ux** [comment]
Well, I did as you instructed me. If there's more info I can get for you, or a way to export the logs more directly, let me know. I've tried looking in Miru's logs folder, but the only file in their is `main.log` which repeats the following line repeatedly:

```
[2023-06-19 18:19:43.141] [warn]  APPIMAGE env is not defined, current application is not an AppImage
```

I'm not saying it's anything in particular's fault. I'm just trying to track down the issue. If it's not of interest though, I would be okay with it if you wanted to close this issue.

I tried installing Chrome and testing a few video sites like Youtube and Vimeo; their media played correctly. I will also reiterate, there are some anime in Miru which play their videos fine in certain circumstances.

**Comment by ThaUnknown** [comment]
if you're bored enough you could try compiling miru without these flags: https://github.com/ThaUnknown/miru/blob/master/src/main/main.js#L7-L18

I don't really know anything about that warning you sent, once Miru is bundled, all the black magic is electron's doing, and I simply "hand over control" to how electron handles bundling and installing, so it doesn't tell me much

some media plays fine, but from what I understood only sometimes? so the same media that played once, can sometimes not play another time? if that happens then it's gg? that sounds like some decoding error which fails on hardware side [I assume] or a driver layer that fails

if video doesn't play at all AND audio also doesn't play then I think I fixed it in v4, but if video doesn't show, but audio plays and the time progress increases then yeah it's not something I can easily track or fix, for comparison, that's like creating a video tag say: `<video src='myfile.mp4'>` on some website, then a user opens that website and says "the video no workey", that's pretty much what's happening here, I'm really not sure what I can say in that case as Miru doesn't really do *much* in terms of video handling, I leave it all to chromium, with the exception of [Look's patches](https://github.com/Muril-o/electron-chromium-codecs)

**Comment by Hew-ux** [comment]
I got an error saying "ELIFECYCLE  Command failed." If it would be possible for you to compile a version of Miru without those flags you mentioned, I'd be glad to test it.

I also attempted to run Miru on my old Windows 7 install, to see if I could reproduce the issue there, but an error window appears saying "Entry Point Not Found. The procedure entry point GetPackageFamilyName could not be located in the dynamic link library KERNEL32.dll".

**Comment by ThaUnknown** [comment]
the electron version I'm using doesn't support win7 so it had no right to work

**Comment by Muril-o** [comment]
@Hew-ux can you check if the issue is still present on latest 4.2.3?

**Comment by Hew-ux** [comment]
@Muril-o Updated to the now current version (4.2.8) and the behaviour is slightly different. Now, an error message appears saying that the video is an incompatible format, and it will not attempt to play it (before, it would still play with audio, but with a blank video screen). It's a more graceful way of handling the error.

I've tried running the provided commands to compile Miru again but received the same ` ELIFECYCLE  Command failed.` error.

At this point, I think it's just a bad/old video format and that it will not play in a modern browser. It does work fine if I download it to disk locally and play it with VLC player. I'm content with closing this for now.

**Comment by ThaUnknown** [comment]
the issue could be with the torrent storage itself, if you were using flatpak or some distro with /tmp limitations, you could try changing the torrent file storage in settings and see if the issue persists

**Comment by Hew-ux** [comment]
I've tried changing the temp location to my home folder, but the issue stays the same.

**Comment by Kurineko** [comment]
I'm having the same issue on my computer windows 11 and the lastest version of the app
