### ISSUE TITLE
[Bug]: Window decoration (close, minimize, maximize) doesn't show on Linux.

### ISSUE THREAD

**Issue by kyngs** [ThaUnknown/miru#291]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v4.1.3

### What operating system version are you using?

Linux

### Expected Behavior

The minimize/maximize/close icons appear.

### Actual Behavior

They're not there, I can only close the app by right-clicking its icon on the taskbar. Interestingly, I can still drag the window by clicking the upper part of it.

### Screenshots

![image](https://github.com/ThaUnknown/miru/assets/38181667/4fea378b-8f1d-466c-86dc-750f03329b91)

**Comment by ThaUnknown** [comment]
this is likely caused by: https://github.com/ThaUnknown/miru/blob/master/src/main/main.js#L135-L139

could u try fucking around with it, like setting it to only true, or smth like that on linux and PR? i dont have a linux machine :)

**Comment by ThaUnknown** [comment]
ah, this doesn't exist on linux. lol.

**Comment by kyngs** [comment]
I will try some googling and tinkering today and will see whether it works.

**Comment by kyngs** [comment]
One solution would be to use the native frame, however, that doesn't look quite well.

![image](https://github.com/ThaUnknown/miru/assets/38181667/2242f401-45de-49a0-95e8-614505b105de)

**Comment by kyngs** [comment]
Well, apparently there's not other way: https://github.com/electron/electron/issues/23665
Gotta love electron!

**Comment by ThaUnknown** [comment]
try changing the color of the bar to the same dark as the others, but only on linux and PR it, and i'll merge, linux simply has to cope

**Comment by kyngs** [comment]
> try changing the color of the bar to the same dark as the others, but only on linux and PR it, and i'll merge, linux simply has to cope

That unfortunately won't be possible, because Electron does not provide any control over it. 
![image](https://github.com/ThaUnknown/miru/assets/38181667/006802bd-68d9-4e8e-b8d5-11f9e315d2b9)

**Comment by ThaUnknown** [comment]
so we need a custom title bar just for linux, wooo
