### ISSUE TITLE
[Feature Request]: Opt-out of auto-updates

### ISSUE THREAD

**Issue by titorgla** [ThaUnknown/miru#293]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

I have an old thinkpad that i used miru for, and updates 4.1.3 -> 4.1.8 has impacted performance a lot compared to pre-4 miru

I have decided to switch back to 3.11.6 hoping that would fix my issues but the moment i opened miru it would auto-update back to 4.1.8 (latest release as of writing)

![Screenshot from 2023-07-09 11-52-13](https://github.com/ThaUnknown/miru/assets/88099383/30b3e34e-ce45-4e67-8223-ae7411962d38)

### Proposed Solution

Please provide an option to opt out of auto-updates, Ideally a toggle would be nice, I'd suggest update channels but i don't know how feasible that would be.

**Comment by ThaUnknown** [comment]
this is an absolutely-not-happening type case, I'm a solo developer and I rapidly push updates, which often are broken, if some1 stays on that broken update their experience will plummet, I'd much rather have you report what actually is lagging than not update, I assume the scrolling is lagging for you? I'll add an option to disable it, tho I did make it a lot faster on latest version
