### ISSUE TITLE
[Feature Request]: Add a Plan to Watch section

### ISSUE THREAD

**Issue by Casamenta** [ThaUnknown/miru#294]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

There is no Plan to Watch section, which pulls your plan to watch from anilist etc.

### Proposed Solution

Add a Plan to watch section or in the filters bar add tracking options where you can see your completed, plan to watch etc.

**Comment by ThaUnknown** [comment]
"your list"
