### ISSUE TITLE
[Bug]: Playing ED instead of episodes

### ISSUE THREAD

**Issue by Bartek200219** [ThaUnknown/miru#295]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

4.1.12

### What operating system version are you using?

Windows

### Expected Behavior

When i click Episode 1 of Tawawa On Monday Miru should play Episode 1

### Actual Behavior

When i click Episode 1 of Tawawa On Monday Miru plays ED

### Screenshots

![Miru_2023-07-12_00-57-36](https://github.com/ThaUnknown/miru/assets/37016424/32dedebb-5ff5-4201-bf59-107fd09c02de)

**Comment by ThaUnknown** [comment]
leave it to Yuri to have a making scheme so fucked that it can't be parsed, I already tilted out eds and ops but I'll look into it
