### ISSUE TITLE
[Feature Request]: Clear appdata

### ISSUE THREAD

**Issue by Bartek200219** [ThaUnknown/miru#296]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

After series of updates Miru stop behaving correctly like Not playing/searching torrents and some anilist error popups, so i had to delete appdata folder. It happend to me twice over half a year of usage.

### Proposed Solution

Below restore defaults should be a button to clear all of appdata.

**Comment by ThaUnknown** [comment]
this is a bad hack for an unspecified issue, report the individual issues not just "wah no worked"
