### ISSUE TITLE
[Feature Request]: Arabic subtitle selection  

### ISSUE THREAD

**Issue by Rukhkh** [ThaUnknown/miru#298]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Version 4.1.12
OS: Linux

there is no Arabic subtitle in the `preferred Subtitle Language `
![Screenshot_20230715_004255](https://github.com/ThaUnknown/miru/assets/73662336/728775ff-6b73-4720-8936-f7e94bc131e5)

### Proposed Solution

adding Arabic subtitle selection

**Comment by ThaUnknown** [comment]
very simple reason, miru wont find any torrents with arabic subtitles so there's no reason to prefer arabic subtitles

**Comment by Rukhkh** [comment]
Erai-raws [Multi-Sub] has Arabic subtitles

**Comment by ThaUnknown** [comment]
I remember why I didn't add this, because there are about 40 arabic language codes, i added `ara` but don't expect it to work 100% of the time

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/miru/commit/0b92faf27eff6e8bcd939aebf859f3cb1d3e1fe6

**Comment by Rukhkh** [comment]
thank  you so much
