### ISSUE TITLE
[Feature Request]: Import and Export Settings

### ISSUE THREAD

**Issue by titorgla** [ThaUnknown/miru#299]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

I work with multiple instances of miru on different machines and having to set custom feeds, playback settings, torrent settings, etc for each one is a bit of time consuming

### Proposed Solution

An option to quickly import and export settings in Miru would help me a lot

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/miru/commit/985af2a0df4bb210cdac7d3d44c5952b670f6d2d

**Comment by titorgla** [comment]
thanks!
