### ISSUE TITLE
[Bug]: sometimes, a line of subtitles either redisplays/keeps displaying the previous line or completely fails to show up

### ISSUE THREAD

**Issue by akyraisconfused** [ThaUnknown/miru#301]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v4.2.2

### What operating system version are you using?

Windows

### Expected Behavior

subtitles to be displayed as they should.

### Actual Behavior

sometimes a line either displays the previous line again or completely fails to show up. rewinding to before the said line appears makes the correct line show up. enabling "Fast Subtitle Rendering" _seems_ to have helped a little bit but it still happens quite often.

**Comment by ThaUnknown** [comment]
this only happens on either the very first subtitle of the file, or on seek, this is stupidly common when streaming video with embedded subtitles, and every player has this issue, most can get away with it by preloading more data, I can't do that, but as you're watching those issues don't really arise

Fast Subtitle Rendering is completely unrelated, it disables blur on rendering, and has nothing to do with subtitle extraction

**Comment by akyraisconfused** [comment]
for me it happens at least thrice per episode, and while watching regularly without seeking. but as i said rewinding to just before it happens makes the correct line display, so if it's difficult/not possible to fix i can live with it. since rest of the app is worth dealing with a mild annoyance as such ^-^

**Comment by ThaUnknown** [comment]
this could happen when your internet can't keep up with the video's bitrate, causing buffering, which is effectively the same as seeking
