### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by nakadzima9** [ThaUnknown/miru#303]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Will support for Russian subtitles be added in the app settings?

### Proposed Solution

I don't know, maybe I should somehow switch the RSS feed to torrents with support for Russian subtitles?

**Comment by ThaUnknown** [comment]
this isn't a feature request
