### ISSUE TITLE
[Feature Request]:  Confirm sign-out

### ISSUE THREAD

**Issue by I-JMC** [ThaUnknown/miru#304]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Log out is too close to Home, which made me Log out several times

### Proposed Solution

Logout confirmation

**Comment by ThaUnknown** [comment]
I mean.... just dotn click it?....

**Comment by I-JMC** [comment]
Or ask a confirmation if you really want to log out

**Comment by ThaUnknown** [comment]
now that's a shout
