### ISSUE TITLE
[Bug]: Doesn't play

### ISSUE THREAD

**Issue by Bartek200219** [ThaUnknown/miru#311]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

4.3.3

### What operating system version are you using?

Windows

### Expected Behavior

After clicking continue watching episode should play

### Actual Behavior

Nothing is playing, nothing is downloading, restart doesn't fix problem. 

### Screenshots

![Miru_2023-08-07_20-58-17](https://github.com/ThaUnknown/miru/assets/37016424/c54b33dc-1ad3-48be-8dc6-feb3d705f0b6)

**Comment by ThaUnknown** [comment]
this is likely due to ISP/VPN blocks, I recommend you either not use the VPN you currently use as many block torrenting, or use a VPN like AIRVPN or NordVPN if you don't currently use one

**Comment by Bartek200219** [comment]
I don't use vpn and i don't have any restrictions, because if i delete %appdata%/miru it works again and in https://github.com/ThaUnknown/miru/issues/296 you wanted me to report individual issues so i did that
