### ISSUE TITLE
[Feature Request]: add Ukrainian subtitles.

### ISSUE THREAD

**Issue by m1nuzz** [ThaUnknown/miru#315]
### Preflight checklist

- [x] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Application does not have a choice of Ukrainian subtitles.

### Proposed Solution

Add an option to select Ukrainian language.

**Comment by ThaUnknown** [comment]
thats torrent dependent not app dependent, simply look for torrents with Ukrainian subtitles, afaik they dont exist tho

**Comment by m1nuzz** [comment]
> thats torrent dependent not app dependent, simply look for torrents with Ukrainian subtitles, afaik they dont exist tho

[Erai-raws] - releases torrents with Ukrainian subtitles
