### ISSUE TITLE
[Bug]:  Too sensitive touchpad on scrolling 

### ISSUE THREAD

**Issue by BassoMC1** [ThaUnknown/miru#318]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v4.3.6

### What operating system version are you using?

Windows

### Expected Behavior

Reasonable scrolling speed with touchpad.

### Actual Behavior

Too sensitive scrolling on touchpad

**Comment by cx622** [comment]
This is the same with my linux laptop.

**Comment by ThaUnknown** [comment]
09d386818a474af8c01e873d9dd7140b694c29d5
