### ISSUE TITLE
[Feature Request]:  Ui Update on the epsode lists 

### ISSUE THREAD

**Issue by BassoMC1** [ThaUnknown/miru#319]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Example if i want to watch one piece ep 900 you need to scrol down alot on the page

### Proposed Solution

make it only show 10 - 20 ep and add pages if it has more episodes.

**Comment by SoaringGecko** [comment]
Another solution could be to add a search bar for the episodes allowing you to search by ep number or name, though I feel this could bring it's own complications and problems.
