### ISSUE TITLE
[Bug]: not rendering Arabic subtitle correctly 

### ISSUE THREAD

**Issue by Hujair** [ThaUnknown/miru#322]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v4.3.11

### What operating system version are you using?

Windows

### Expected Behavior

can renders unicode characters for subtitles 

### Actual Behavior

doesn't render Arabic text for subtitles

**Comment by ThaUnknown** [comment]
it's up to the torrent releaser to include fonts for their releases, this simply means the releaser didn't include any such fonts
