### ISSUE TITLE
[Bug]: Changing the RSS to a custom one doesn't work.

### ISSUE THREAD

**Issue by Hexality** [ThaUnknown/miru#324]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v4.3.12

### What operating system version are you using?

Windows

### Expected Behavior

Load RSS correctly and get new releases from the RSS instead of relying on Subsplease and giving me the english subtitles instead.

### Actual Behavior

Fails to fetch url and falls back to Subsplease, even if I remove it from the RSS page.

### Screenshots

![image](https://github.com/ThaUnknown/miru/assets/17398632/03b01ec0-b7f9-4dcb-8cd7-82badd30e315)
![image](https://github.com/ThaUnknown/miru/assets/17398632/f9f852b3-34b0-4c8f-a5c6-5a3e67f680a1)

**Comment by Hexality** [comment]
And yes, I've restarted the app multiple times already trying different arrangements and RSS feed URLs.

**Comment by ThaUnknown** [comment]
those arent valid URLs, you're just typing in text, miru has some pre-defined ones which show up as text, but custom ones need to be an URL like its visible in the examples
![image](https://github.com/ThaUnknown/miru/assets/6506529/7bce8fc1-9f6f-4696-8e45-6c6fecd67fe9)

**Comment by Hexality** [comment]
interesting, however the url itself also was giving the same error as I stated there.

**Comment by ThaUnknown** [comment]
as i said, you probably used an incorrect url, i've been using custom RSS feeds myself and they work just fine
