### ISSUE TITLE
[Feature Request]: Watch History

### ISSUE THREAD

**Issue by 0xJsoul** [ThaUnknown/miru#325]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

I want to keep track of what I'm watching without Anilist

### Proposed Solution

A watch history built in the app for guests or for those who don't want to create an Anilist account

**Comment by ThaUnknown** [comment]
no
