### ISSUE TITLE
[Feature Request]: Ability to load external subtitles from either file, url or subtitle repository

### ISSUE THREAD

**Issue by Hexality** [ThaUnknown/miru#326]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Some animes may not have subtitles for a specific language embedded but may end up getting translated subs in the future.

[...]

### Proposed Solution

[...] So, it would be interesting if the app had a way to load external .ass/.srt directly from url or subtitle repository like [Erai-Raws Release Subtitles](https://www.erai-raws.info/subs/?dir=Sub) ([Sub release page](https://www.erai-raws.info/subtitles/)) and have also the option to adjust the subtitle sync right there on the subtitle selection.

This would allow people to load more well seedded releases like the ones from SubsPlease and yet have the subtitle available for selection.

**Comment by ThaUnknown** [comment]
a864d9217327cb822f8da90c262b1e6e29e20419
