### ISSUE TITLE
[Bug]: Anime does not update progress in anilist if not watched until the last second

### ISSUE THREAD

**Issue by Hexality** [ThaUnknown/miru#331]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v4.3.14

### What operating system version are you using?

Windows

### Expected Behavior

Update the episode progress after watching at least 50/80% of the episode (Ignoring if the anime episode was started from "Continue now" or by clicking on the episode itself)

### Actual Behavior

Doesn't update the episode count if the episode is not watched until the end or if the anime episode was started through the episode list itself.

### Screenshots

Episode watched up to the outro, and it didn't update the counter, clicking another anime or closing and reopening the app does not make it update, this makes the tracking unprecise.
![image](https://github.com/ThaUnknown/miru/assets/17398632/59aaa23c-e20f-4291-84af-a4c5c3a822aa)
![image](https://github.com/ThaUnknown/miru/assets/17398632/8f89b9aa-16c8-4c4c-b496-378765c837cf)

**Comment by ThaUnknown** [comment]
this is caused by the RSS feed used, only applies to this one anime

**Comment by Hexality** [comment]
no it doesn't apply only to this anime

**Comment by ThaUnknown** [comment]
[I can't reproduce this](https://anilist.co/activity/615765370)

**Comment by ThaUnknown** [comment]
additionally the ss you provided shows episode 9 as tracking, and 9/13 episodes being completed on the hovercard, which is why I said it's an edge case wish mushoku

**Comment by Hexality** [comment]
You literally misunderstood the card
If the tracking had worked, the "Continue now" would be greyed out, which
isn't the case.
I watched the 9th episode, yet it didn't sync with anilist in any moment.

It only was able to sync the episode after I watched it up to the last
second without skipping to the end.
