### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Dictator8644** [ThaUnknown/miru#332]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

please add feature to set default speed in player other than normal too
as 1.25x , 1.5x , 1.75x and 2x .

### Proposed Solution

it should be default we don't need to change speed for each episode

**Comment by ThaUnknown** [comment]
`[`, `]` and `\` do it

**Comment by Dictator8644** [comment]
but if i change speed to 1.3x in one episode i have to set it again in next episode 
please add i have to only set it once until i close app or change anime 

btw this is the only thing which bothers me else your app is just too good to be true
hats off to miru app team
thank you
