### ISSUE TITLE
[Feature Request]: Support for scraping in case of older or unseeded torrents

### ISSUE THREAD

**Issue by HiroDane** [ThaUnknown/miru#335]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Older anime which do not have well seeded torrents available are basically impossible to watch with this app. I could go to a different app which uses scraping but that wont have anilist integration or some other features. I would like to watch it all on Miru ideally.

### Proposed Solution

Add support for website scraping as an optional backup for unseeded torrents.

**Comment by ThaUnknown** [comment]
duplicate
