### ISSUE TITLE
[Feature Request]:  android version.

### ISSUE THREAD

**Issue by mhshadin** [ThaUnknown/miru#336]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Currently there is no android or mobile version of Miru available. It would be great to be able to use a convenient program like Miru on phones.

### Proposed Solution

I'm not a developer so I'm unable suggest a proper solution

**Comment by ThaUnknown** [comment]
duplicate
