### ISSUE TITLE
[Bug]: Arch version don't see/include needed codecs and freez after few sceonds

### ISSUE THREAD

**Issue by Jeremi360** [ThaUnknown/miru#339]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

4.4.1-1 - the newest in AUR repos

### What operating system version are you using?

Linux

### Expected Behavior

1. When I install miru using `yay -S miru-bin` its should also install needed codecs
2. When I open app in should see installed codecs
3. When I go to seetings it shouldn't freeze after few seconds

### Actual Behavior

1. Instaling miru using `yay -S miru-bin` only installs `xdg-utils` as its dependency
2. I open app it don't see that I have installed codecs
3. When I go to seetings it shouldn't freeze after few seconds

Ps. You are missing in FAQ anwser to what codecs are needed. 
Also popup with info about missing codces should give link to anwser in FAQ that says what codecs are needed. 

### Screenshots

**1.** actual behavior:
![image](https://github.com/ThaUnknown/miru/assets/1294815/250acefb-372c-4d04-9112-725b7b341522)

**2.** actual behavior:
![image](https://github.com/ThaUnknown/miru/assets/1294815/c58946ff-d0c1-4071-9bfb-1ebed2b19a1e)
![image](https://github.com/ThaUnknown/miru/assets/1294815/075d84e0-7851-4407-8d58-50ea68c571cd)

**Comment by ThaUnknown** [comment]
miru includes codecs in it's chromium build, or more specifically it uses chromium which has it's own internal build of ffmpeg which doesn't use os codecs

**Comment by Jeremi360** [comment]
> miru includes codecs in it's chromium build, or more specifically it uses chromium which has it's own internal build of ffmpeg which doesn't use os codecs

If that is a case then way I get pop-up that video codes are missing.
And I saw that when I tried to installed flatpak it installs openh265 for it.
But Flatpak won't even launch for me.
