### ISSUE TITLE
[Bug]: Video not playing

### ISSUE THREAD

**Issue by Aayewsh** [ThaUnknown/miru#343]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v4.4.8

### What operating system version are you using?

Windows

### Expected Behavior

When I open any anime, it buffers the video and then plays it once a certain length of video is downloaded.

### Actual Behavior

The buffering is happening as evident by the download speed at the top of the screen, but the video does not play. It's just a black screen.

### Screenshots

![Screenshot_195](https://github.com/ThaUnknown/miru/assets/145251423/24016b83-f24b-4104-ab9d-fb0b99cdbe99)

**Comment by ThaUnknown** [comment]
download speeds aren't necessairly buffering, if you download a torrent of 100 files, it might not necessarily download the 1 file you're watching as there might not be peers seeding the file, but this seems like a different issue, like a bug with the video player

could you try playing a video from any releases feed, a single episode and see if it ever starts playing?

**Comment by Aayewsh** [comment]
Tried playing several different videos. Same issue in all of them.

**Comment by ThaUnknown** [comment]
did you wait for them to download fully?

**Comment by Aayewsh** [comment]
Yeah, the episode seems to have downloaded fully, but it still doesn't play

**Comment by ThaUnknown** [comment]
okay, this is likely an issue with something on your device and not Miru, so let's debug this, open devtools [ctrl shift i], play a video, show the debug information from what files were selected by the player in the console, go into media tab and show the track state and debug information, screenshots would be preferable, here's a vid on how to do it, pretty much every new view i enter in devtools I'd want to see in those screenshots, with all the details and groups opened like i showed


https://github.com/ThaUnknown/miru/assets/6506529/f227f959-53d3-44e3-8659-e0c44f984a93

**Comment by Aayewsh** [comment]
I got the first part, but nothing showed up on the media tab when i opened it


![Screenshot_198](https://github.com/ThaUnknown/miru/assets/145251423/6c40ae67-0d96-46cb-b847-4886d0b3478a)
![Screenshot_199](https://github.com/ThaUnknown/miru/assets/145251423/e2b812cb-9565-4727-9f7a-0a03a40df3ac)
![Screenshot_200](https://github.com/ThaUnknown/miru/assets/145251423/ab46b344-268d-475b-aea8-f897abf01ca0)

**Comment by ThaUnknown** [comment]
thanks for the report, I see the issue, will fix ASAP

**Comment by Aayewsh** [comment]
Thanks a lot!!
