### ISSUE TITLE
[Feature Request]:  Notification

### ISSUE THREAD

**Issue by dinhokusanagi** [ThaUnknown/miru#348]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Currently, it is not available even the favorites and there is no way to organize anime in any way

### Proposed Solution

The app could run in the background and by putting the anime on favorites would receive a notification that a new episode was released

**Comment by ThaUnknown** [comment]
available in 5.1.6
