### ISSUE TITLE
[Bug]: Ongoings in "Continue Watching" tab appearing only if there's unwatched episodes

### ISSUE THREAD

**Issue by EnergoStalin** [ThaUnknown/miru#349]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v4.4.12

### What operating system version are you using?

Linux

### Expected Behavior

Ongioing appear in "Continue Watching" after watching first and the only aired episode

### Actual Behavior

It show's only when there's unwatched episodes

### Screenshots

Episodes watched 1/12(aired 6)
![image](https://github.com/ThaUnknown/miru/assets/49844515/f7154394-6de7-408a-a945-7c583671b9a3)

Episodes watched 1/12(aired 1)
![image](https://github.com/ThaUnknown/miru/assets/49844515/c45fc047-9190-41c3-8be5-4f1f877de1e8)
![image](https://github.com/ThaUnknown/miru/assets/49844515/7985d5d8-1694-4b57-a236-a667b903abf0)

**Comment by EnergoStalin** [comment]
The problem is here i think

https://github.com/ThaUnknown/miru/blob/916476aeb8c07b5026477bfde089eac53aa015f9/src/renderer/views/Home/Home.svelte#L45

If it's not a feature of course. Featuring what anime can be easily dropped after first episode)

**Comment by EnergoStalin** [comment]
Sorry i'm clueless i should've test it better.

**Comment by ThaUnknown** [comment]
this is a regression from "airing episodes you missed" which miru had at the start, which was then renamed but code wasnt updated x)

**Comment by EnergoStalin** [comment]
I think it can be separate tab like was stated in #347. Current behavior completely okay it just need a little bit of understanding. Or maybe it's just mass schizophrenia about purpose of this tab) Because it's indeed purely logical to have only anime with unwatched episodes here. And you can get all ongoings you planning to watch in "You List" tab with airing filter

**Comment by ThaUnknown** [comment]
> it just need a little bit of understanding

thats the issue, the app needs to be made with people that share 1 brain cell across their entire family in tree, which is why I re-opened this, because I myself realised at one point "hm shouldnt this have other stuff too?"

**Comment by ThaUnknown** [comment]
after thinking more about this, this is intended behavior, I don't see a point in "continue watching" of a show that u cant actually continue watching?

**Comment by EnergoStalin** [comment]
Yes. Like i said i'm happy with that
