### ISSUE TITLE
[Feature Request]: Seedboxes

### ISSUE THREAD

**Issue by CR1MS0N24** [ThaUnknown/miru#353]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

not really a problem and this might be a dumb question but can this be used with one if so is a vpn also needed.

### Proposed Solution

.

**Comment by ThaUnknown** [comment]
yeah quite the stupid question

the whole point of Miru is to run it on the device that's watching anime, without needing to host any servers

you could mount a network drive and set miru's download location to that mounted network/remote drive, which I guess would somewhat accomplish what you need, but you can't run Miru's download process on a VPS
