### ISSUE TITLE
[Feature Request]: Integrate Anime4k upscaler into MPV

### ISSUE THREAD

**Issue by ElGamerEduard** [ThaUnknown/miru#354]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

I have made a comparison between watching the best encode via streaming vs downloaded: https://slow.pics/c/ZUvkqkK4
In 4k displays there is a noticeable difference, a little bit of loss, maybe caused by the bitrate? idk

### Proposed Solution

I think a good solution to mitigate this (and increase overall quality) could be to implement the Anime4k upscaler in the native MPV as an option.
https://github.com/bloc97/Anime4K

**Comment by ThaUnknown** [comment]
no

miru also doesn't use mpv

**Comment by ElGamerEduard** [comment]
oh sorry, I misunderstood. But anyway, couldn't it be a nice addition? Since as I have read, it can be implemented in any programming language.

**Comment by Tama47** [comment]
@ElGamerEduard Just use [webtorrent-mpv-hook](https://github.com/mrxdst/webtorrent-mpv-hook). That way it allows for full customization of the player, the downside being that you need to copy/paste magnet links yourself.
