### ISSUE TITLE
[Feature Request]: Automatic subtitle track translation

### ISSUE THREAD

**Issue by EnergoStalin** [ThaUnknown/miru#355]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

I want miru have option to automatically translate subtitles.

This is definitely looks like edge case because seems no one besides me bothering about that except youtube which added built in on the fly translation but it still valuable for me i even have mpv [plugin](https://github.com/EnergoStalin/subtitle-translate-mpv) for this purpose. The main reason is for some anime subtitles releases not quickly enough or not at all in my or other's first language. So i believe having machine translation can be a nice addition to autoplay torrents if you don't much bother about translation quality because context can be easily missed by translator if supplying it line by line.

### Proposed Solution

I suggest porting and improving my mpv plugin functionality to miru because when i was writing this plugin there's was a lot of limitations to maintain portability which is wont be problem in miru's case.

In such case bare minimum what miru should have:
- Enable/Disable toggle
- Optional original x0.5 size subtitles rendering under translated subtitle line
	Because machine translation sucks sometimes and we still might want to have original line.

As for automatic enable behaviour don't think we need it. It was helpful when switching between episodes in mpv but in miru it can be done in another level.

I was used crow translate CLI as translation service because of limited lua runtime. But there's A LOT better options on js with normal runtime.

Additional useful features:
- Toggle to swap original/translated subtitles.
	Render x0.5 size translated in the bottom instead of original.
	Can be useful if watching in multilanguage company i.e. 2 english speakers and you want have translation for yourself as not primary for self checking.

So there's the feature.

**Comment by ThaUnknown** [comment]
yeaaaaaaaaah........ nooooo........... definitely not....

you can just pick a multi-sub release if one exists instead
