### ISSUE TITLE
[Bug]: Box at the end of the subtitle lines

### ISSUE THREAD

**Issue by s9991s** [ThaUnknown/miru#356]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v4.4.14

### What operating system version are you using?

Windows

### Expected Behavior

Subtitles with 2 lines to display without a box at the end of the first line

### Actual Behavior

On certain torrents (for example  view/1728103), when there is a subtitle with 2 lines there is a box at the end of the first line. If I manually download the torrent and play it in mpv, this doesn't happen. I attached a screenshot with miru on the left and mpv on the right. I've tried changing my default subtitle font and it didn't help. Maybe the box is something to do with how \n is handled, idk.

### Screenshots

![box](https://github.com/ThaUnknown/miru/assets/148172612/d5e75869-c6bb-475f-86f5-c304c75e47f3)

**Comment by ThaUnknown** [comment]
![image](https://github.com/ThaUnknown/miru/assets/6506529/43ccb9f6-6b22-43ba-abec-b6d272a64b5e)
can't reproduce on provided torrent

**Comment by s9991s** [comment]
It seems like it only happens if the font isn't set to default. To fix it I had to restore default settings so that the default subtitle font menu turned blank and then restart miru, and then the box stopped appearing (sidenote: if you reset the settings and the font menu turns blank, if you click on another tab in settings and then click back on the player tab then instead of the font being blank it displays whatever the first font is alphabetically, even though it isn't actually set to that). If I then change the default subtitle font to something else (I've tried Arial, Trebuchet MS, Agency FB) and restart miru, the box comes back.

**Comment by ThaUnknown** [comment]
ah, okay, so it's likely because there's some invisible char there at the end of the line, which Miru's built-in default font handles, but the custom fonts from your OS don't.

Realistically I don't think I can fix this? I might consider removing the default fonts option as it seems to cause a lot of issues for little benefits....

**Comment by ThaUnknown** [comment]
sorry this took a while x)

spotted like 3 other bugs thanks to this report
