### ISSUE TITLE
[Feature Request]: Disable and enable media key support

### ISSUE THREAD

**Issue by muuyo** [ThaUnknown/miru#357]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

I... admittedly use my computer in very odd ways, but:
If I happen to pause an episode of an anime, or otherwise just leave Miru in the background dormant and idle, its reaction to media keys can get really annoying. It seems that solving this [wouldn't be _too_ difficult](https://github.com/electron/electron/issues/21731), but I'm no maintainer on the project so I might be completely off base.

### Proposed Solution

I'd like to see a toggle in the settings that merely disables or enables hooking of media keys, since I tend to leave many programs open - such as Miru and Spotify at the same time.

**Comment by ThaUnknown** [comment]
I don't really see the point of this, media keys will prioritise the latest used program
