### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by iMikaplay** [ThaUnknown/miru#359]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v4.4.16

### What operating system version are you using?

Windows

### Expected Behavior

Maybe it's a bug, Autoplay torrent is not being efficient in choosing a preferable language, I think he could identify better.

### Actual Behavior

When Auto play torrent is turned on, it does not select the torrent with subtitles in the language I specified even though it has the language in the list, perhaps the problem is that it cannot identify which language is preferable in episodes with multi subs, if possible I would love it could be resolved.
PS: Some animes it can identify (Naruto classic for example) and select the language I want, and yes, I've already looked at the animes that don't work and have Portuguese subtitles in the app's torrent list.

### Screenshots

![image](https://github.com/ThaUnknown/miru/assets/148654110/b3a32e45-f533-4036-8568-290c4137d9fb)
![image](https://github.com/ThaUnknown/miru/assets/148654110/b5e0b63e-8f2e-4017-b71f-8d5e0e6790de)
![image](https://github.com/ThaUnknown/miru/assets/148654110/695e25e9-fa93-46c7-ac60-123bc70608cf)

**Comment by ThaUnknown** [comment]
preferred language is selected once a video is being played, which is why its in the player section, not torrent section, detecting languages from torrent's is currently close to impossible without dedicated servers for it, which would go against miru's model

**Comment by EnergoStalin** [comment]
Quick remark. Anidb api can be used to implement it somehow since they have [group stats](https://anidb.net/group/14642) with languages. There's even a good? [package](https://github.com/tsukeero/anidb-udp-client) for it. But it will require anidb account of course.
