### ISSUE TITLE
[Bug]:  Cannot be opened.

### ISSUE THREAD

**Issue by PedroVMota** [ThaUnknown/miru#360]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

4.4.14

### What operating system version are you using?

MacOS

### Expected Behavior

The program should open without any issues.

### Actual Behavior

Launch error.

"Miru.app" cannot be opened because the developer cannot be verified.
Mac-OS cannot verify that this app is free from malware

### Screenshots

I just installed today, and right after the installation a pop is showed that cannot be verified

**Comment by ThaUnknown** [comment]
https://www.google.com/search?q=macos+install+unverified+app
