### ISSUE TITLE
[Bug]:  "Pause when tabbing out" Feature not working as expected

### ISSUE THREAD

**Issue by iamargelh** [ThaUnknown/miru#369]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

4.4.19

### What operating system version are you using?

Windows

### Expected Behavior

Pause when tabbing out from application

### Actual Behavior

When tabbing out, Miru doesn't pause the playback due to Electron blame, seems to work only if losing focus trough "minimize button".

**Comment by ThaUnknown** [comment]
confirmed as an electron bug

**Comment by ThaUnknown** [comment]
this can't really be fully fixed without sacrifices, it works on android and smart TV's, but on desktop it will only work when minimizing
