### ISSUE TITLE
[Feature Request]: Home Page Categories

### ISSUE THREAD

**Issue by PESER** [ThaUnknown/miru#371]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Currently, if you go to your home page you get the first 3 options of New Releases, Continue Watching and Sequels You missed. All really useful categories, but it's lacking specifically "Current Season" which would allow you to track and check out everything that currently comes out. Also, the order of the categories doesn't really fit everyone's needs. 

### Proposed Solution

Add a category that presents all currently released shows this season with information on what season it is currently. 
Also possibly change the order of the categories to your liking as well as the ability to remove categories that don't interest you at all from the home page.

**Comment by PESER** [comment]
Update, technically there is "Popular this season" but I do think it should be renamed to "Current Season" and add the ability to pull it higher, possibly with the ability to rearrange depending on the new episodes released rather than popularity.

**Comment by ThaUnknown** [comment]
this already exists
