### ISSUE TITLE
[Feature Request]: Hide or Close the small video preview

### ISSUE THREAD

**Issue by PESER** [ThaUnknown/miru#372]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Currently when you finish the show you go to another page like the Home screen and you have a small window preview that needs to be constantly moved all over the place as it blocks certain areas on the app. 

### Proposed Solution

I propose either a complete ability to close that small window or the ability to hide it when the preview is not needed so that it doesn't obstruct the vision.

**Comment by ThaUnknown** [comment]
read
the
faq
