### ISSUE TITLE
[Discord Rich Presence]

### ISSUE THREAD

**Issue by madmaxgrey** [ThaUnknown/miru#373]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [x] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

4.4.19

### What operating system version are you using?

Windows

### Expected Behavior

Discord Presence turns off

### Actual Behavior

Turning off discord presence in settings does not disable. it continues to display what your watching etc... on discord

**Comment by ThaUnknown** [comment]
it did work, you just needed to restart the app for it to take effect, as the settings state, it was fairly easy to make it reactive tho, so it should now update within a few secodns

**Comment by madmaxgrey** [comment]
my issue is yes the RPC is working the way you want it, but i want it to never display on discord what so ever, when its enabled it shows what anime your watching when its disabled it still shows up on discord but with information about miru on how its a torrent, not hating on the reason its torrent, i just don't want miru to show on discord what so ever
