### ISSUE TITLE
[Bug]: Discord Rich Presence doesn't get fully disabled after disabling "Enable rich presence"

### ISSUE THREAD

**Issue by Hexality** [ThaUnknown/miru#376]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v4.5.2

### What operating system version are you using?

Windows

### Expected Behavior

Have Discord Rich Presence completely disabled

### Actual Behavior

Unwantedly continues to show the rich presence.

If we had the option to completely disable it before, then you should continue to have that feature.
I used to have it disabled cause I only want some specific things to show up in the reach presence, and after the update it simply started reappearing.

The law of multiple different contries enforce that you should have the option to disable features that might invade privacy, doesn't matter if its related to the software itself or whatever the person is using it for.
Note: this isn't a feature that only discord needs to have, the software that is connecting to the rich presence itself needs to have a toggle to disconnect from the rpc api.
### Screenshots

![image](https://github.com/ThaUnknown/miru/assets/17398632/144c3759-d007-4b25-9ee9-57323ce6d052)

**Comment by ThaUnknown** [comment]
this won't be changed, if you don't want any RPC status, disable RPC in discord

**Comment by Hexality** [comment]
I guess I'm forking.
