### ISSUE TITLE
when pressing on a episode it just shows searching episode in the torrent and never loads

### ISSUE THREAD

**Issue by demoniccoder1** [ThaUnknown/miru#378]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v4.52

### What operating system version are you using?

Windows

### Expected Behavior

when pressing on a desired episode of an anime loading the episode quickely

### Actual Behavior

when pressing on a desired episode of an anime it just shows searching in the torrent but never plays the episode

### Screenshots

![Screenshot 2023-11-24 210358](https://github.com/ThaUnknown/miru/assets/151945447/d92fceb6-3f1e-40ee-b31d-94e7ab3d2803)

**Comment by ThaUnknown** [comment]
it's possible your ISP is blocking your connection to nyaa

**Comment by demoniccoder1** [comment]
how can you fix that could you please tell me

**Comment by ThaUnknown** [comment]
https://thewiki.moe/getting-started/torrenting/

**Comment by ThaUnknown** [comment]
sry https://thewiki.moe/tutorials/unblock/

**Comment by ThaUnknown** [comment]
you can try using DOH in settings too

**Comment by demoniccoder1** [comment]
I tried to replace the DNS server but its not working

**Comment by ThaUnknown** [comment]
enable DoH in settings and try that, 
![image](https://github.com/ThaUnknown/miru/assets/6506529/aafca0ec-9f29-4d95-938c-11710f9cc7af)
I assume this just loads indefinitely?

**Comment by demoniccoder1** [comment]
yes

**Comment by ThaUnknown** [comment]
yeah your ISP likely blocks nyaa, I hope you are aware miru is a torrent client, and it might be illegal in some countries

**Comment by demoniccoder1** [comment]
yes i am aware of that i just enabled doh and am about to try again thanks for helping me actually i am a new laptop user as such i dont know much about its functions and how to use it properly thanks for your guidance

**Comment by ThaUnknown** [comment]
I'll add a timeout for this later today

**Comment by demoniccoder1** [comment]
![Screenshot 2023-11-24 220109](https://github.com/ThaUnknown/miru/assets/151945447/3f1b70e0-7627-4694-8b6d-5489525dbd8b)


now this is happening and the loading problem still hasnt been solved

**Comment by ThaUnknown** [comment]
hahah you changed the DOH URL to something invalid XD

**Comment by demoniccoder1** [comment]
how to fix that

**Comment by demoniccoder1** [comment]
so you are telling me to uninstall miru and download it again wright

**Comment by ThaUnknown** [comment]
pretty much, noone has used this feature before, because most people that run into connection issues like you simply use a VPN, so it was never tested, I'll fix all this soon

**Comment by demoniccoder1** [comment]
thanks for your help i will try installing it again and running it if that doesnt work i will wait for its new update to come out thanks

**Comment by demoniccoder1** [comment]
are you still here

**Comment by ThaUnknown** [comment]
both of these issues are fixed in v4.5.4

if you can't connect to nyaa your seeder counts might not be accurate, keep that in mind, I recommend using a VPN

**Comment by demoniccoder1** [comment]
Ok
