### ISSUE TITLE
[Bug]: Video Codec Unsupported when trying to playback anime

### ISSUE THREAD

**Issue by ItsCryptic** [ThaUnknown/miru#380]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

4.5.5

### What operating system version are you using?

Linux

### Expected Behavior

It should allow me to play back anime

### Actual Behavior

It does not allow me to playback anime

### Screenshots

![image](https://github.com/ThaUnknown/miru/assets/43621653/e75a470a-1779-4ef2-add0-52f28811fd9f)

**Comment by ThaUnknown** [comment]
wooooo weeeeee linux

this is an issue with your linux configuration, which can have as many issues, as changes you've made

how did you install miru, do you have space on your drive, does miru have access to `/tmp` or the custom directory you set in settings

**Comment by ItsCryptic** [comment]
Miru has full access to my system - I've installed it through Flatpak as I'm on fedora silverblue. I have enough space on my drive as well.

**Comment by ThaUnknown** [comment]
I don't maintain flatpak, try using the .deb or .AppImage available in the releases, and see if the issue persists

**Comment by EnergoStalin** [comment]
Is this immediately appear when miru starts? Then it's because miru, you or os(in `/tmp` case) deleted file what was last played and it cant be loaded on miru restart anymore. Error can be more helpful tho.

**Comment by ThaUnknown** [comment]
that's not the case, Miru re-scans `tmp` folders, if the file is missing it will re-download it

**Comment by EnergoStalin** [comment]
Oh my i double checked and it's indeed redownloading. I wonder why yesterday it isn't working. Because when checked it was like i described. Strange...
