### ISSUE TITLE
[Feature Request]: Continue Watching

### ISSUE THREAD

**Issue by ParanoidHitman** [ThaUnknown/miru#382]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Certainly! Here's a revised version of your statement with added clarity and a few additional details:

Currently, the app makes it challenging to explore and keep track of other anime series and their episodes. I often lose track of the episodes I've watched, which leads me to frequently open AniList for confirmation. A more seamless integration or feature within the app that helps in tracking episode progress would greatly enhance the user experience. This could include real-time updates on new episodes and a more user-friendly interface for managing and viewing my anime watchlist.

Certainly! Here's an enhanced version of your proposal with additional details:

### Proposed Solution

Drawing inspiration from popular platforms like Aniwatch, Aniwave, or even Netflix, our app could greatly benefit from introducing a 'Continue Watching' tab. This feature would provide a comprehensive history of the episodes a user has viewed. It would not only list the episodes but also save the exact minute where the user paused, creating a seamless viewing experience. By simply clicking on this tab, users could effortlessly resume watching from their exact stopping point, be it midway through an episode or at the beginning of a new one. Additionally, this tab could include personalized recommendations based on viewing history, enhancing user engagement and offering a more curated anime watching experience.

**Comment by ThaUnknown** [comment]
something like this?.... just log in with anilist....
![image](https://github.com/ThaUnknown/miru/assets/6506529/8d6053cc-1c6a-40a2-a252-11b4a977acd7)
![image](https://github.com/ThaUnknown/miru/assets/6506529/53ec9f36-58f2-45d4-99c3-0772bec1976b)
![image](https://github.com/ThaUnknown/miru/assets/6506529/178288a5-f783-4c20-9dc7-261c8367af3b)

also dont use AI to create issues or I'll ban you the next time
