### ISSUE TITLE
[Feature Request]: Could you please add a toggle for "NSFW" in the options, and a setting for "Preferred Title/Episode Language?

### ISSUE THREAD

**Issue by pinbuck** [ThaUnknown/miru#385]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

When searching for SFW titles, NSFW titles will pop up without an option to filter them out.

Second request is self explanatory. It's usually a bit of trouble trying to search for certain titles that aren't immediately on the front page with a picture.

### Proposed Solution

Adding an off by default toggle for a "Pornography" tag would solve this. It could be placed in the search's filter list, or  could be placed somewhere in Settings and defaulted to off.

A third option being Preferred Title/Episode Language option under the Language section. This could probably default to the system's language settings.

**Comment by ThaUnknown** [comment]
Miru already filters out porn, however it keeps 'ecchi' content, which is difficult to distinguish in "levels of NSFW", so I don't think it will get better than this
