### ISSUE TITLE
[Bug]: Video player is frozen

### ISSUE THREAD

**Issue by Aayewsh** [ThaUnknown/miru#388]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v4.5.5

### What operating system version are you using?

Windows

### Expected Behavior

Video starts playing whenever I click on any episode.

### Actual Behavior

The video player froze when I played the "Undead Unluck" anime episode. Even if I try to open another anime, the video player remains frozen. It's neither playing the episode nor downloading it.

### Screenshots

![Screenshot_244](https://github.com/ThaUnknown/miru/assets/145251423/eb3a01b0-9339-4b8d-bc33-c3a1442e23d6)

**Comment by ThaUnknown** [comment]
this because VAYR's video is corrupted, #387, this will permamently hang miru, you'll need to do:
- open devtools via `Ctrl + Shift + I`
- navigate to the console tab
- type in `localstorage.setItem('torrent', '')
restart miru

**Comment by Aayewsh** [comment]
The problem persists so I don't think this worked.

![image](https://github.com/ThaUnknown/miru/assets/145251423/15d516c2-10a7-4546-b8fe-66d5036ef8ea)

**Comment by ThaUnknown** [comment]
oops, i didnt format the message above correctly, try again, i'll release a new version of miru which fixes this today
