### ISSUE TITLE
[Feature Request]: Cache in RAM

### ISSUE THREAD

**Issue by aicynide** [ThaUnknown/miru#389]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

You mentioned it has mpv but mpv cache internet video in RAM not disk like your app

### Proposed Solution

Either let us download torrent in RAM or let us instantly delete torrent video from disk as soon as you stop playing the video

**Comment by ThaUnknown** [comment]
some torrents can be upwards of 100GB, this isn't a good idea.
