### ISSUE TITLE
[Feature Request]: Blur next episode's thumbnail on currently watching anime

### ISSUE THREAD

**Issue by khizka** [ThaUnknown/miru#392]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

New Releases tab and episode list sometimes has spoilers, even if it's not major ones, like just a character returning.

### Proposed Solution

A default enabled toggle on interface settings that blur any episode thumbnail that you didn't watch yet. I think it would need to check your Anilist for that, as I only find it useful if it's a currently watching anime.

**Comment by ThaUnknown** [comment]
blur is bad, and looks bad, instead i show a generic preview thumbnail from the anime's banner, which is spoiler free, looks better, accomplishes the goal
