### ISSUE TITLE
[Feature Request]: Prioritize Eri Raws torrents 

### ISSUE THREAD

**Issue by EliasTheGrandMasterOfMistakes** [ThaUnknown/miru#401]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

The majority of Torrent not have a good multi language support

### Proposed Solution

This can fix the subtitle problems, can be good is possible to create a list from some fansubs and raws for be the high priority:

Why:
Multi Language embedded subtitles.
Various Quality files.
H264 and H265 (the best if for use h264 because is more width adopted)

**Comment by EliasTheGrandMasterOfMistakes** [comment]
https://nyaa.si/?f=0&c=0_0&q=eri+raws

**Comment by EliasTheGrandMasterOfMistakes** [comment]
https://nyaa.si/?f=0&c=1_0&q=%5BMultiple+Subtitle%5D+ 
Using a multiple subtitles search is more good to, for have a list, this can be good for prioritize torrents with [Multiple Subtitle]  in name

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/miru/issues/403#issuecomment-1881712680

for seasonals simply set the home screen rss feed to erai

for older releases erai is rarely the best available release, you can simply disable auto-select torrents and pick erai yourself if its seeded

**Comment by EliasTheGrandMasterOfMistakes** [comment]
> [#403 (comment)](https://github.com/ThaUnknown/miru/issues/403#issuecomment-1881712680)
> 
> for seasonals simply set the home screen rss feed to erai
> 
> for older releases erai is rarely the best available release, you can simply disable auto-select torrents and pick erai yourself if its seeded

Thank You

**Comment by Eichen97** [comment]
yeah, this works, but if you select a chapter from the anime itself, you must have the auto-select option disabled.
which criteria follows to auto-select a torrent? could it be an option to preffer or to blacklist a specciffic option?
