### ISSUE TITLE
[Bug]: Cannot read properties of undefined (reading 'entries') on Your list

### ISSUE THREAD

**Issue by nodoggoi** [ThaUnknown/miru#405]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v4.5.9 Windows x64

### What operating system version are you using?

Windows

### Expected Behavior

A list of anime on my "Your List" section in the home screen

### Actual Behavior

Under "Your list" you get
**Ooops**
Looks like something went wrong!.
Cannot read properties of undefined (reading 'entries')

### Screenshots

![image](https://github.com/ThaUnknown/miru/assets/107820793/ad0c64ad-840d-4229-9f7c-e9afc6a11c1d)

**Comment by nodoggoi** [comment]
I also tried logging in and logging out. I checked AniList for any issues related to the list for Miru.

**Comment by ThaUnknown** [comment]
any chance u could link ur AL account?

**Comment by nodoggoi** [comment]
![image](https://github.com/ThaUnknown/miru/assets/107820793/636e6260-a559-4979-92c3-0e87c12cc7be)
It's linked and I still have the issue.
I'm going to try unlinking, and signing out again to see if it fixes.

**Comment by ThaUnknown** [comment]
no I meant give me the link to your al profile XD

**Comment by nodoggoi** [comment]
Here you go 
https://anilist.co/user/kouh/

**Comment by ThaUnknown** [comment]
ah, I see this is because you don't actually have anything on your list/planning, it should display:
![image](https://github.com/ThaUnknown/miru/assets/6506529/6bc09a48-4546-4ae8-8160-b85476921d64)
