### ISSUE TITLE
[Bug]: Interface > Sections and Order > Too many new releases.

### ISSUE THREAD

**Issue by DrFutzLoop** [ThaUnknown/miru#406]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

4.5.9

### What operating system version are you using?

Windows

### Expected Behavior

Only one listing for "new releases" as they all do the same thing

### Actual Behavior

Currently there are 5 options for new releases where only 1 is required.

### Screenshots

![image](https://github.com/ThaUnknown/miru/assets/155639424/ee9250e4-d433-4dfe-8f58-15fbe8a4eeab)
![image](https://github.com/ThaUnknown/miru/assets/155639424/4f684346-30e1-467b-ad99-2969dd089e79)

**Comment by ThaUnknown** [comment]
simply press the 
![image](https://github.com/ThaUnknown/miru/assets/6506529/321e2c51-0b94-4822-af73-409c04a50b05)
button

this likely happened because in older versions you added a fuckload of rss feeds
