### ISSUE TITLE
[Feature Request]: Setting to show time as total time in video instead of time left

### ISSUE THREAD

**Issue by LevisAlone** [ThaUnknown/miru#410]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Currently, there's no way to customize the time the player shows, so it will show as 19:03 / 4:36, I personally like to have the total time always visible.

### Proposed Solution

Add a setting or make it so you can click on the time the player shows (similar to say, how the YouTube mobile app implements this) to make the time display as 19:03 / 23:40 instead.

**Comment by ThaUnknown** [comment]
decided against this, I don't see much point in it
