### ISSUE TITLE
[Feature Request]: spawn custom video player process

### ISSUE THREAD

**Issue by ThaUnknown** [ThaUnknown/miru#415]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

people like their mpv setups

### Proposed Solution

allow some form of execution like `mpv %0` where %0 would be replaced by the HTTP URL of the media, then listen to when the process closes, and how long it's been open for to track watch progress

**Comment by EnergoStalin** [comment]
Must remind that using mpv ipc would be required for w2g. So i'd like to think that extended and abstracted version of my proposed player api implementation from draft [pr](https://github.com/ThaUnknown/miru/pull/390) would be particularly useful for wiring it both to user controls, mpv controls, and session controls. Of course if such support is planned in observable future.

**Comment by ThaUnknown** [comment]
not worth, I wouldn't target any specific player, or sync data, I'd simply spawn the process, and give it the playback URL, nothing more nothing less, simply times wouldn't be synced, only what files are played
