### ISSUE TITLE
[Bug]: Mouse and player controls won't hide when playback resumed from keyboard shortcut

### ISSUE THREAD

**Issue by fc1018** [ThaUnknown/miru#416]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v4.5.10

### What operating system version are you using?

Windows

### Expected Behavior

When spacebar is pressed to resume video playback that had been previously paused, the video should continue playing and UI player control elements should reappear and hide after a short delay.

### Actual Behavior

When spacebar is pressed to resume video, playback is resumed but UI elements remain unhidden permanently until mouse is moved again, after which the UI player control elements are hidden after a short delay. 

### Screenshots

UI Player Controls Visible:
![image](https://github.com/ThaUnknown/miru/assets/85690455/5b3e7935-c67c-4ca6-a889-78c937f5474b)
UI Player Controls Hidden:
![image](https://github.com/ThaUnknown/miru/assets/85690455/0159a091-5cfe-463e-b6d5-d1ab96a1ea12)

**Comment by fc1018** [comment]
Replicating is a little unreliable, I found that the expected behaviour occurs in full-screen mode but when in windowed and in focus sometimes using the spacebar to pause and resume causes the bug to happen.

**Comment by ThaUnknown** [comment]
I'd be surprised if you can reproduce this more than once

**Comment by fc1018** [comment]
I have found that by keeping it in windowed and focused, I can replicate it after pausing and resuming 2-3 times quite consistently. I've also had success in replicating the behaviour on macOS v4.5.10 as well following the same steps.
