### ISSUE TITLE
[Bug]: Torrent found not playing 

### ISSUE THREAD

**Issue by Bartek200219** [ThaUnknown/miru#418]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v4.5.10

### What operating system version are you using?

Windows

### Expected Behavior

Anime should play

### Actual Behavior

Anime doesn't play

### Screenshots

![image](https://github.com/ThaUnknown/miru/assets/37016424/3e57d9f8-a01e-40f4-ac84-31462bb984d6)
No matter what i choose to watch its the same, restart doesn't fix this. Even clearing appdata doesn't solve the problem

**Comment by ThaUnknown** [comment]
your ISP/VPN is likely blocking torrent connections, this isn't a Miru issue

**Comment by Bartek200219** [comment]
> your ISP/VPN is likely blocking torrent connections, this isn't a Miru issue

No, torrents work normally with qbittorrent

**Comment by ThaUnknown** [comment]
provide proper reproduction steps

**Comment by Bartek200219** [comment]
I cant reproduce it on clean setup
