### ISSUE TITLE
[Build Issue]: no entry for '/fsevents/2.3.3' in pnpm-lock.yaml

### ISSUE THREAD

**Issue by LovingMelody** [ThaUnknown/miru#419]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

master

### What operating system version are you using?

Linux

### Actual Behavior

Building with `pnpm install --frozen-lockfile --no-optional --ignore-script` fails with the following error:
```
no configure script, doing nothing
Running phase: buildPhase
no Makefile or custom buildPhase, doing nothing
Running phase: installPhase
Scope: all 5 workspace projects
Lockfile is up to date, resolution step is skipped
 ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY  Broken lockfile: no entry for '/fsevents/2.3.3' in pnpm-lock.yaml

This issue is probably caused by a badly resolved merge conflict.
To fix the lockfile, run 'pnpm install --no-frozen-lockfile'.
```

**Comment by ThaUnknown** [comment]
you need optional, you can't ignore scripts
