### ISSUE TITLE
[Bug]: Close the currently playing video

### ISSUE THREAD

**Issue by AISLVE** [ThaUnknown/miru#420]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v4.5.10

### What operating system version are you using?

MacOS

### Expected Behavior

I should have an accessible way of closing the currently playing episode

### Actual Behavior

No matter how much i try i can't seem to find a close button for the episode leading me to close and open the app in order to episode of another anime

**Comment by ThaUnknown** [comment]
faq
