### ISSUE TITLE
[Feature Request]: Have a more accessible button to switch episodes 

### ISSUE THREAD

**Issue by AISLVE** [ThaUnknown/miru#421]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Currently in the video player layout i see no way of changing my episode let's say from 10 to 14 i would have to manually skip episodes or open the anime's storyline page to play it again

### Proposed Solution

Add a button to be able to switch between episodes easily

**Comment by ThaUnknown** [comment]
menu > now playing > episode list
