### ISSUE TITLE
[Feature Request]: HakuNeko connectors support

### ISSUE THREAD

**Issue by vavavr00m** [ThaUnknown/miru#424]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

HakuNeko has many (over a thousand) [connectors](https://github.com/manga-download/hakuneko/tree/master/src/web/mjs/connectors) for manga/anime sources. HakuNeko is partly written in javascript while miru is partly in javascript.

### Proposed Solution

Is it possible to have support for connectors (.mjs) from HakuNeko and is the team behind Miru interested in implementing such in the future?

**Comment by ThaUnknown** [comment]
haruneko is a web scraper, miru is a torrent client, they are different things
