### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Vask42k** [ThaUnknown/miru#425]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v4.5.10

### What operating system version are you using?

Windows

### Expected Behavior

Have a clear screen without bleeding screen.

### Actual Behavior

Having Bleeding screen with white stips every where but when i move my mouse cursour it gets clear for certain time.

### Screenshots

![Miru screen bleed](https://github.com/ThaUnknown/miru/assets/74807599/485691ff-717e-4acf-8a7b-9eba46c18bb7)

**Comment by nlxdodge** [comment]
I have never experienced this, but this seems more like a GPU issue.
Can you try to re-install your graphics driver to see if that fixes the issue?

Alternatively, if you have it installed, try to start Windows Sandbox. Install Miru there and check if the problem persists. (Windows Sandbox is like a virtual machine).

Other than that I have no idea what might be the issue for something like this, maybe the owner of the repo knows more. I tried to look into the code for a couples minutes, but I am not sure where to even start.

**Comment by ThaUnknown** [comment]
it's likely you played around with the rendering settings under interface, which is the end result of this, set angle either to default or d3d9, if that doesn't fix it, buy a GPU which isn't dead
