### ISSUE TITLE
[Bug]: Continue watching section isnt working properly

### ISSUE THREAD

**Issue by Vansh0134** [ThaUnknown/miru#426]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v

### What operating system version are you using?

Windows

### Expected Behavior

It should show me the Ep of X anime i have watched

### Actual Behavior

But it just display's "Oops" 

### Screenshots

![image](https://github.com/ThaUnknown/miru/assets/121380410/9e52a473-7616-4ae9-812a-38ded9cf7516)

**Comment by ThaUnknown** [comment]
this simply means that there's no anime for you to continue watching, you're up to date on everything

**Comment by Vansh0134** [comment]
so i like watched a anime called mon no pichi till the ep 5 but it still shows "oops" @ThaUnknown

**Comment by ThaUnknown** [comment]
link your anilist account

**Comment by Vansh0134** [comment]
ah now it works thanks
