### ISSUE TITLE
[Feature Request]: A way to disable Miru putting anime we've watched using it into a serperate list.

### ISSUE THREAD

**Issue by MidnightKittenCat** [ThaUnknown/miru#427]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Miru keeps on adding anime I've watched with the app to an entirely different list.
![image](https://github.com/ThaUnknown/miru/assets/66114416/a52ba8d2-1f9b-4f37-911a-c4fcb1b94e5f)

I wanna be able to prevent this.

### Proposed Solution

Add an option so we can have it not put it into a custom list, rather have it be put into our watching or completed.

**Comment by ThaUnknown** [comment]
no

**Comment by LoneWolf993** [comment]
> no

That's quite inconsiderate

**Comment by i486** [comment]
I don't mind "Watched using Miru" list but there is no way to hide it from public profile.
