### ISSUE TITLE
[Feature Request]: Add visual for toggle for shows with english dub

### ISSUE THREAD

**Issue by widowshyper** [ThaUnknown/miru#429]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

No option to toggle anime that have english dub or when viewing an anime have it auto default to viewing the english dub version

### Proposed Solution

I like to watch all my anime with english dub and while english dub anime is avalible, it would be nice to have an auto select for english dub or a toggle to show which Anime have english dub episodes.

**Comment by ThaUnknown** [comment]
miru doesnt curate its own content, so it doesn't know ahead of time what releases and languages are available, doing those requests each time an anime is displayed, isn't possible
