### ISSUE TITLE
[Bug]: Auto Update Function On Mac Does Not Update Application

### ISSUE THREAD

**Issue by DracarisFire** [ThaUnknown/miru#433]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [x] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v4.5.8 Mac OS arm64

### What operating system version are you using?

MacOS

### Expected Behavior

Auto update triggers update or update prompt. 

### Actual Behavior

Love the app! I get the notification that a new version of Miru is available and that it is downloading but it never ticks over to trigger an update. I would expect another notification to pop up so I can proceed with an update but it never comes. Not a huge issue. I can grab it from Github but thought I would report it. Thanks

### Screenshots

<img width="1728" alt="Screenshot 2024-03-23 at 8 52 01 pm" src="https://github.com/ThaUnknown/miru/assets/152683055/533fe1d2-bb38-4894-b6d9-050b08c1a6bc">

**Comment by ThaUnknown** [comment]
honestly, no clue why this happens, I use some external dependency recommended by electron for updating, but it doesn't work on MacOS....

**Comment by ThaUnknown** [comment]
this should be fixed in 5.1.2, but since it's fixed in that version, we'll need to wait for 5.1.3 to verify if it was actually fixed

**Comment by ThaUnknown** [comment]
we're getting closer, in 5.1.4 it downloads the update but fails to install it, man I hate macos....

**Comment by ThaUnknown** [comment]
@DracarisFire hey I finally got time to find the root of the problem, apple requires people to pay money in order for apps to install other apps [auto-update], I'm not paying apple jack shit

The update popup is now not as annoying, and when you click the download button it simply opens miru's download page
