### ISSUE TITLE
[Bug]: Cannot link AniList account on Linux

### ISSUE THREAD

**Issue by YoruNoKen** [ThaUnknown/miru#434]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.0.0

### What operating system version are you using?

Linux

### Expected Behavior

After clicking on "Login with AniList", and authorizing the app on Chromium, it should log me in.

### Actual Behavior

After authorizing the app it asks me if I want to open it with `xdg-open`,  after clicking open, it returns an error.
`Could not read file miru://auth/#&access_token=eyJ0eX.........&token_type=Bearer&expires_in=31536000.`

### Screenshots

![image](https://github.com/ThaUnknown/miru/assets/69751661/1fcfe248-01b2-4ea2-bad0-e8f441282004)
after clicking open xdg-open:
![image](https://github.com/ThaUnknown/miru/assets/69751661/b3a46797-ba62-4197-9d96-1bc8fdef3b33)

**Comment by YoruNoKen** [comment]
For the record: I'm on Arch Linux, Plasma (X11) version 6.0.2

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/miru/issues/153#issuecomment-2015698234

**Comment by YoruNoKen** [comment]
Not sure what you mean? The "Unknown protocol" error disappeared after some time, now I get this error.

**Comment by ThaUnknown** [comment]
this is an issue with your specific linux install, not miru, since it's your config that's causing issues, fix it yourself, the issue i linked talks about similar issues, either do that, or use what miru provides for sign-in
