### ISSUE TITLE
[Bug]: When anilist account is logged in the continue watch and sequels you missed dont appear and uses like 50% of cpu and check for update not working

### ISSUE THREAD

**Issue by SuckyBuckyYT** [ThaUnknown/miru#435]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.0.2

### What operating system version are you using?

Windows

### Expected Behavior

the continue watching to work and check for update working

### Actual Behavior

says oops looks like there is nothing for the continue watch thing and check for updates just flickering the screen, i had originally downloaded this on 5.0.0 and i checked in the github there being 5.0.2 released so i went to the settings to check for updates but the screen just flickered a bit and did nothing? can u add like a bar to show that its checking for update because i didnt even know if it was checking, one more thing just after i had downloaded miru and made an anilist account the continue watch thing and others were working fine but after like 1 hour it broke i tried reinstalling but it didnt work

### Screenshots

![image](https://github.com/ThaUnknown/miru/assets/97747818/56ebf3f5-a61a-4aa7-9e6a-44b10a55ad2b)

**Comment by ThaUnknown** [comment]
that simply means there's nothing on your anilist lists, you cant continue watching stuff, if there's nothing on ur list...?

**Comment by SuckyBuckyYT** [comment]
yes but i go to anilist.co and i can see my continue watching that i watch in miru but not on the miru itself

**Comment by ThaUnknown** [comment]
anilist doesn't have a continue watching, it has a "currently watching", continue watching is stuff you're behind on that has released.

**Comment by SuckyBuckyYT** [comment]
yeah so i watch a new anime series like 2 eps nothing comes up why is that

**Comment by SuckyBuckyYT** [comment]
update: randomly started working again
