### ISSUE TITLE
[Feature Request]: I would love to see a fedora install for this <3

### ISSUE THREAD

**Issue by Vansh0134** [ThaUnknown/miru#438]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Miru currently doesnt support fedora 

### Proposed Solution

hey unknown, could you also support fedora/fedora based distros for miru

**Comment by ThaUnknown** [comment]
miru works on fedora, it distributes an appimage and deb, both of which u can install, if u want it the 9999th linux package manager PR it, and maintain that distribution, otherwise it will be removed
