### ISSUE TITLE
[Feature Request]:  Upgrade to latest Electron release 29.3.0 as of issue creation date

### ISSUE THREAD

**Issue by AkechiShiro** [ThaUnknown/miru#439]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

If there are no impacts for usability could the app be upgraded to the latest electron release as some security fixes have been made into it ? 
https://releases.electronjs.org/release/v29.3.0

The current release used is not too old but still is not the latest.

### Proposed Solution

Upgrade package.json files to use https://releases.electronjs.org/release/v29.3.0

**Comment by ThaUnknown** [comment]
there's no reason, we also run a custom compilation of electron

**Comment by AkechiShiro** [comment]
I believe new security fixes are implemented in the latest electron release, I don't think there is no reason to upgrade however I need to open a bug report on a specific graphical crash I've been encountering when hovering over specific parts of the app, this causes a white blank screen and crashes miru constantly and can be easily reproduced on my end.
