### ISSUE TITLE
[Bug]: Closing of curly brackets gets ignored when trying to create costum theme

### ISSUE THREAD

**Issue by yugo2911** [ThaUnknown/miru#440]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.0.5

### What operating system version are you using?

Windows

### Expected Behavior

Being able to open and close curly brackets when creating costum theme.

### Actual Behavior

Closing of curly brackets gets ignored.

### Screenshots

![Miru_jJSUsJjXfM](https://github.com/ThaUnknown/miru/assets/47824397/ab06683b-897f-4fd5-a5ec-e63129bcf648)

**Comment by ThaUnknown** [comment]
custom CSS pm;intentionally only supports variables

**Comment by yugo2911** [comment]
It would be nice if users could customize the interface to their liking

**Comment by ThaUnknown** [comment]
yes, thats what the variables is for

if you think some element is missing variables you can create a PR to fix it

**Comment by ThaUnknown** [comment]
made it more explicit that this only supports variables
https://github.com/ThaUnknown/miru/commit/963db909d879a5dad11b33c964b06caaf498fa66
