### ISSUE TITLE
[Bug]: Settings panel doesn't work and breaks entire UI

### ISSUE THREAD

**Issue by squiddingme** [ThaUnknown/miru#442]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.0.9

### What operating system version are you using?

Windows

### Expected Behavior

Upon clicking the settings button in Miru 5.0.9, it should open the settings panel. This works fine in 5.0.7.

### Actual Behavior

The Miru UI breaks, displaying only a blank screen. Clicking to return to any of the other screens (home, search etc) doesn't work anymore.

### Screenshots

![image](https://github.com/ThaUnknown/miru/assets/4538091/d0825a95-cea3-4c37-af70-e2f40b191a12)

**Comment by ThaUnknown** [comment]
open console via ctrl+shift+i and screenshot the most recent [lowest down] error, preferably entire window

**Comment by AdamH18** [comment]
For whatever reason the latest update logged me out of AniList, and that's when I noticed this problem too. It goes away when you log in.

![image](https://github.com/ThaUnknown/miru/assets/16923286/9421191f-dfaa-4b1d-91f9-b8f7f7f3f0c7)
