### ISSUE TITLE
[Bug]: Torrent Error, Failed to Fetch, on every anime

### ISSUE THREAD

**Issue by eduisreal** [ThaUnknown/miru#443]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

Last version I think, i down;loades the 5.0.10

### What operating system version are you using?

Windows

### Expected Behavior

Torrent error

### Actual Behavior

Just cant watch anything because of torrent error

### Screenshots

![imagem_2024-04-15_220902989](https://github.com/ThaUnknown/miru/assets/164369161/c36b42fe-5589-438f-833e-56b42a36f771)

**Comment by ThaUnknown** [comment]
this is likely an issue with your network/ISP blocking the download of .torrent files, funny.
