### ISSUE TITLE
[Bug]: EPERM: operation not permitted, mkdir "(any storage device I select)"

### ISSUE THREAD

**Issue by KeffiyehBaba** [ThaUnknown/miru#450]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.1.0

### What operating system version are you using?

Windows

### Expected Behavior

I can select a torrent to watch, it downloads, and plays normally.

### Actual Behavior

I select a torrent to watch, it starts to download and then the error message pops up saying "Torrent Error 'EPERM: operation not permitted, mkdir '(currently selected storage device)'". I have dealt with this before and simply changing the download location for torrents or restarting/redownloading the app solves the issue. None of those options are working now.

### Screenshots

![miru](https://github.com/ThaUnknown/miru/assets/168885880/2f60c134-346a-4a6f-87ff-c9a2965abbe9)

**Comment by ThaUnknown** [comment]
you selected a directory which has restricted access/permissions, either create a sub-directory and give every1 access, or run miru as admin [dont]
