### ISSUE TITLE
[Bug]: RAM usage skyrockets and app crashes due to OOM

### ISSUE THREAD

**Issue by kefiiris** [ThaUnknown/miru#452]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.1.0

### What operating system version are you using?

Linux

### Expected Behavior

Supposed to keep RAM usage as low as needed and not crash due to OOM.

### Actual Behavior

RAM Usage skyrockets gradually and the app eventually crashes due to OOM.

**Comment by ThaUnknown** [comment]
you likely restricted miru from writing data to disk

**Comment by kefiiris** [comment]
> you likely restricted miru from writing data to disk

Yeah that was it. I checked around in settings and configured some stuff up and the issue stopped occuring. Thank you.
