### ISSUE TITLE
[Bug]: Failed making request to anilist! Try again in a minute. 404-not found

### ISSUE THREAD

**Issue by AumTheBest1** [ThaUnknown/miru#453]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.1.0

### What operating system version are you using?

Windows

### Expected Behavior

It should automatically update the episode which i watched as done in anilist

### Actual Behavior

It doesnt do that and shows this error whenever i go to next episode
![image](https://github.com/ThaUnknown/miru/assets/63140083/77b38b31-2fa9-443f-94e4-ca9a6e61e050)

### Screenshots

![image](https://github.com/ThaUnknown/miru/assets/63140083/ffeeeb7e-5537-4401-853a-1891cf403d14)

**Comment by vvirtues** [comment]
same thing also with one piece
