### ISSUE TITLE
[Bug]: Default font doesn't support japanese characters

### ISSUE THREAD

**Issue by Lolirag** [ThaUnknown/miru#454]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.1.0

### What operating system version are you using?

Windows

### Expected Behavior

When inputting external subtitles, the Japanese Text would display properly.
(I expect Japanese to be supported, given the Preferred Subtitled Language setting.)

### Actual Behavior

Instead, all the characters are errors.

Having tested various different subtitles with various series, external subtitles of the romance language have no issue. Japanese however, does. 
Have also tested on other media players, and they expectedly display without issue.

### Screenshots

![Miru_FTQXrzABVE](https://github.com/ThaUnknown/miru/assets/114037793/84fc0ac4-e45a-46a3-a1d1-ece7cbc16381)
![Miru_i7G6vNyTP2](https://github.com/ThaUnknown/miru/assets/114037793/ca957dfe-f58f-4251-a25d-0ebed4de9fea)

**Comment by ThaUnknown** [comment]
the default fallback font in miru doesn't support japanese characters, you'll need to install a font on your PC that does, then set that as default fallback font in settings

**Comment by Lolirag** [comment]
It seems I'm retarded. Thanks.

**Comment by ThaUnknown** [comment]
nah, I considered making a font that supports jp sub

**Comment by dfireBird** [comment]
I tried changing the default subtitle font to 'Noto Sans CJK JP' but I get the error in screenshot. If you need any more info, I'll gladly help with that too.
![image](https://github.com/ThaUnknown/miru/assets/40687700/90bf5282-3a83-438a-8949-c756e5bc8c68)

**Comment by ThaUnknown** [comment]
huh, cool

**Comment by ThaUnknown** [comment]
@dfireBird this is fixed in 5.1.2 https://github.com/ThaUnknown/miru/commit/33f9124cc9b9d3831413a636b70dfc0bf66f0613

there's not an easy to fix this, however the solution is "use a fallback font which has japanese characters", but if the release includes a font, which doesnt support jp characters, then proceeds to create fonts which have jp chars, this wont work, so i'm gonna track this issue in https://github.com/ThaUnknown/miru/issues/329

**Comment by GioGioWasTaken** [comment]
Hello! 
sorry if i'm necro-ing this thread, but:

![image](https://github.com/user-attachments/assets/1ee3ddf3-b7bd-4aa0-ba45-6e143eee21f6)

There doesn't seem to be any option titled "fallback font". If you were referring to the top option here, I set it to a Japanese font so there shouldn't be an issue, yet i have the exact same issue as the one referred to in this thread when sideloading my subtitles via drag and drop.

My system is Arch Linux. I'm using the latest version of Miru, as available in the AUR under the name miru-bin. 

I hope I'm not being an idiot, if I am, truly sorry!
