### ISSUE TITLE
[Feature Request]: One Pace Implementation

### ISSUE THREAD

**Issue by iVolgin69** [ThaUnknown/miru#457]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

No One Pace ig

### Proposed Solution

add One Pace? xoxo

**Comment by ThaUnknown** [comment]
this is a perfect example of what to do to get banned from accessing this repository
