### ISSUE TITLE
[Bug]: App crashes on start

### ISSUE THREAD

**Issue by RickyWanga** [ThaUnknown/miru#459]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v.5.1.0

### What operating system version are you using?

Linux

### Expected Behavior

I received a notification that the app would be updated on exit, it should've updated and the next time I would've been using the latest version.

### Actual Behavior

It updated the app but then now it crashes on startup because it is unable to install the update I guess, I have all the right dependencies and also tried removing everything and installing various previous releases but none of them let me use the app, because as soon as I start up the app, it tries to update and then crashes.

### Screenshots

![Screenshot_20240615_200407](https://github.com/ThaUnknown/miru/assets/25136696/c6b2c5f4-85c7-4dfb-9b4e-8d702fdef60b)

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/miru/issues/436
