### ISSUE TITLE
[Bug]: Opening external player in Windows requires Running as Administrator

### ISSUE THREAD

**Issue by dragonfleas** [ThaUnknown/miru#460]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.1.4

### What operating system version are you using?

Windows

### Expected Behavior

I expect the executable to be invoked without the need to run as administrator, as long as I have proper permissions to launch it.

If this is intended behavior, do you think we could add a new note to the setting card in section in 
https://github.com/ThaUnknown/miru/blob/8902833ee3241db4b50c5be94d994d6cd01bb9fc/common/views/Settings/PlayerSettings.svelte#L152-L157
Like `Requires running as administrator on Windows`

If this is a bug, can you assign this to me? I'd like to fix it myself.

### Actual Behavior

Process is not invoked, there are no error messages or indications telling you that as well. Default player is black, content is loading in, but player (in this case mpv) is not launched.

### Screenshots

No screenshot needed for this.

**Comment by dragonfleas** [comment]
I'm going to test out using the electron native way of spawning a `child_process` instead of utilizing node's native `spawn` function. Could be some strange windows permission discrepancy between the two. I think `utilityProcess` is a 1:1 with node's spawn API so it should work.

**Comment by ThaUnknown** [comment]
administrator isnt needed for this tho?

**Comment by dragonfleas** [comment]
> administrator isnt needed for this tho?

This ended up being that I happened to select multiple torrents that's streams didn't complete and on the next launch as administrator it circumstantially finished the download. Disregard this issue, I'll close it. Whoops! lmao
