### ISSUE TITLE
[Feature Request]: Official Docker Image

### ISSUE THREAD

**Issue by Zenthae** [ThaUnknown/miru#464]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Would it be possible to have a Web only dockerised version of this beauty ?

### Proposed Solution

I don't know the codebase enough.

**Comment by ThaUnknown** [comment]
thats like asking for discord to run on docker, its unreasonable as hell, might make a webui for it tho one day
