### ISSUE TITLE
[Bug]: "Continue Watching" and "My List" tab not working as intended

### ISSUE THREAD

**Issue by koldbrew1** [ThaUnknown/miru#465]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v.5.1.8

### What operating system version are you using?

Windows

### Expected Behavior

The continue watching tab to finally work.

### Actual Behavior

I am fairly new to the app and I have used the v5.1.6 before but it never updated my _continue watching_ and _my list_ tabs. I waited for the next update hoping it would work but after trying to use it again today, it still didn't. I have also discovered that labeling an anime in anilist with _planning to watch_ makes it show up in the _my list_ tab. However, I still have no idea how to make the _continue watching_ tab work.

**Comment by ThaUnknown** [comment]
continue watching is anime you're watching that has new episodes available

**Comment by ThaUnknown** [comment]
it works as intended

**Comment by koldbrew1** [comment]
> continue watching is anime you're watching that has new episodes available

I didn't know that was the purpose of that tab. I thought its to keep track of which episode you last watched and recommends you the next one or the timestamp of where you left off. I recommend renaming the tab to something like _new episodes_ then.
