### ISSUE TITLE
[Bug]: AnimeTosho nuked, what now?

### ISSUE THREAD

**Issue by Hexality** [ThaUnknown/miru#466]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.1.8

### What operating system version are you using?

Linux

### Expected Behavior

Having things load.

### Actual Behavior

Miru basically turned into a tracking only service, with AnimeTosho being down after _some stuff happened_ (according [to this comment on r/animepiracy](https://www.reddit.com/r/animepiracy/comments/1dtm91e/comment/lbcw3su/)). Due to that, torrent can no longer be fetched, making the app basically useless.

### Screenshots

![image](https://github.com/ThaUnknown/miru/assets/17398632/2368ac88-8072-4d21-b68d-7dd775d011e2)

**Comment by ThaUnknown** [comment]
it has not been nuked, it will come back soon

**Comment by Sludging** [comment]
Is it possible to make a request (or to understand the effort required) for extending support for other trackers? 

From a short glance at the code it's currently pretty fixed in term of syntax to only work with AnimeTosho but I could have missed something or maybe I'm not aware of how extending the app could be achieved.
