### ISSUE TITLE
[Bug]: Could not connect to Torrent API!

### ISSUE THREAD

**Issue by Sweet-Harsh** [ThaUnknown/miru#467]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

I tryed different version, but could not get rid of problem

### What operating system version are you using?

Windows

### Expected Behavior

I really do not know what to do after following all the steps in Guide

### Actual Behavior

Could not connect to Torrent API!
This happens either because the API is down, or because your ISP blocks the API, the latter being more likely.
Most features of Miru will not function correctly without being able to connect to an API.
If you enable a VPN a restart might be required for it to take effect.
Visit this guide for a tutorial on how to bypass ISP blocks.

After I press Understood button, then home page will appere but cannot stream any anime
### Screenshots

![image](https://github.com/ThaUnknown/miru/assets/167020662/a847103b-bc22-4dd9-b133-3e28019f3f32)
![image](https://github.com/ThaUnknown/miru/assets/167020662/7d43e6e0-5a61-4a53-a1e5-6edfbd0686e9)
![image](https://github.com/ThaUnknown/miru/assets/167020662/2bb38ee5-9c11-45c0-8dab-0d1ece23891a)

**Comment by xi-ve** [comment]
The torrent API URL "https://feed.animetosho.org/" is currently down.

**Comment by Lolirag** [comment]
> The torrent API URL "https://feed.animetosho.org/" is currently down.
If we're allowed to share this information here, is anyone aware of any compatible alternatives?

**Comment by xi-ve** [comment]
> > The torrent API URL "https://feed.animetosho.org/" is currently down.
> 
> If we're allowed to share this information here, is anyone aware of any compatible alternatives?

You can set the DNS to resolve to the servers IP address instead. 
The domain of animetosho is currently suspended.

195.154.243.59    feed.animetosho.org

Add that to your host file in windows / linux.

Credits to Kayaaba from the Miru discord for the temporary solution. :+1:

**Comment by Sweet-Harsh** [comment]
The issue is sloved with a new update the next day. Thank you ThaUnknown and ohers for your help.
