### ISSUE TITLE
[Bug]: The sources on the Mac side will disappear

### ISSUE THREAD

**Issue by Argonautes0607** [ThaUnknown/miru#468]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.1.9

### What operating system version are you using?

MacOS

### Actual Behavior

When playing anime, it will prompt me to add extensions. I don't know what else to add, but restoring the initial settings will still be the same.
<img width="1209" alt="截屏2024-07-04 19 00 37" src="https://github.com/ThaUnknown/miru/assets/106745133/66c5765e-671d-491e-bc40-960207b57c57">
<img width="516" alt="截屏2024-07-04 19 07 18" src="https://github.com/ThaUnknown/miru/assets/106745133/fc9f5f77-bbed-4238-97e8-a251654c060d">

**Comment by ThaUnknown** [comment]
try accessing https://esm.sh/

**Comment by Argonautes0607** [comment]
Is this how it is set? It seems to be the same. New release can be played, but other releases cannot
<img width="1068" alt="截屏2024-07-04 19 17 02" src="https://github.com/ThaUnknown/miru/assets/106745133/1e07ec71-7686-40dd-9dd8-8c2695e46793">

**Comment by ThaUnknown** [comment]
in your browser, not in miru

**Comment by ThaUnknown** [comment]
this seems like a DNS issue
