### ISSUE TITLE
[Bug]: i can't stream One Piece

### ISSUE THREAD

**Issue by Anora8k6** [ThaUnknown/miru#469]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.1.10

### What operating system version are you using?

Windows

### Expected Behavior

I expected to open the page for One Piece and stream but

### Actual Behavior

So it's not showing any torrents for One Piece , and this error is shown, it's only a problem on streaming just one piece episodes as i've tried older one piece movies and different shows they have no issues

### Screenshots

![Screenshot 2024-07-04 184012](https://github.com/ThaUnknown/miru/assets/107633222/446cefdb-2172-485c-9cc4-98c84315539c)

**Comment by ThaUnknown** [comment]
that simply means there are no torrents for it, ep 163 was ages ago, you could try finding one manually
