### ISSUE TITLE
[Feature Request]: Blacklist specific animes in the 'New Releases' tab 

### ISSUE THREAD

**Issue by lv01-GreyCat** [ThaUnknown/miru#471]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

I do not care for some of the long running shows on the 'New Releases' page, or there is an anime from this season that I have tried but do not like and don't wish to watch anymore.  
Currently, I can't stop new episodes from appearing on the 'New Releases' page.

### Proposed Solution

Add a  right-click context menu on any of the new episode cards and on the anime cards, plus a button on the anime's page. They would allow to blacklist / un-blacklist an anime.  
If blacklisted an anime's new episodes would be filtered out of the 'New Releases' page.  

This is admittedly a small issue, and I would understand if it's not worth your time implementing.

**Comment by ThaUnknown** [comment]
this is intended behavior, new releases is a pre-configured RSS feed, if you don't like it, change it in the settings and make ur own rss feed via tosho/nyaa/ur own software which includes the shows and releasers you prefer
