### ISSUE TITLE
Add android app to other store

### ISSUE THREAD

**Issue by Kiriox94** [ThaUnknown/miru#472]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Hello, to protect my data I don't have a Google account and to download applications on my Android phone I go through alternative stores like f Droid or via the apk directly from the github, except that for your application I haven't found an alternative method, on the download page there is well marked apk but when I click it sends me back to the play store

### Proposed Solution

Add the apk in the releases or put it on an alternative store like f droid

**Comment by ThaUnknown** [comment]
get a google account?

**Comment by AdalynBlack** [comment]
In a similar vein, I'm trying to build the APK for android myself, and it appears that a couple of files are missing, namely `capacitor/android/gradlew`, `capacitor/android/build.gradle`, `capacitor/android/gradle/wrapper/gradle-wrapper.properties`, and `capacitor/android/app/src/main/assets/public/index.html`

Additionally, the docker commands used to build the node modules when running `pnpm build` appear to be outdated, mounting `app` directory without the proper flags for the docker container to actually run it

There may be other files missing, but I can't tell at this point without either obtaining the currently missing files, or attempting to recreate them myself
