### ISSUE TITLE
[Feature Request]: Clicking a show episode that I haven't watched should take me to the list of episodes for that show

### ISSUE THREAD

**Issue by kkarakk** [ThaUnknown/miru#473]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

When clicking a show card in the "New Releases" section, I am directed to the listed episode of the show -which starts playing immediately -instead of the first episode, even though I have not watched any episodes. As I am logged into AniList, it should be able to recognize that I have not started the first episode of the show.

This requires me to use the search functionality to locate the show and then manually select the first episode from the episode list. 
If I do not remember the name of the show, I have to return to the "New Releases" section and identify it again by its thumbnail or name.

### Proposed Solution

Clicking an "unwatched"/"untracked" show should take you directly to the list of episodes page instead of starting the episode directly.
Maybe add a setting to change this if it is intended behavior since this doesn't happen when clicking a show name. 

Additional Context:

This enhancement will improve user experience by reducing the number of steps needed to start watching a new show.
It will also help users who may not remember the name of the show they clicked on(like me).

**Comment by ThaUnknown** [comment]
this is intended behavior, new releases is a pre-configured RSS feed, if you don't like it, change it in the settings and make ur own rss feed via tosho/nyaa/ur own software

**Comment by kkarakk** [comment]
Seems like unintentional behavior from perspective of end user but alright
