### ISSUE TITLE
[Feature Request]: Better support for PT BR subtitles

### ISSUE THREAD

**Issue by mooncakke** [ThaUnknown/miru#476]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

The app itself is great, but in terms of subtitles it still leaves a little to be desired, I would like to know if there is any way to put subtitles in Brazilian Portuguese, I have already searched the app and couldn't find a solution 😥

### Proposed Solution

Subtitle alternatives in languages ​​other than English, preferably subtitles in Brazilian Portuguese 2

**Comment by ThaUnknown** [comment]
make an extension for it, or use multi-sub sources

**Comment by alvesprodigy** [comment]
> faça uma extensão para ele ou use fontes multi-sub

Make a tutorial there, brazilian and stupid bro

**Comment by ThaUnknown** [comment]
what else do you want, maybe a blowjob while I'm at it?
if you can't write code just search by "multi" on releases miru provides, if there's none, then there's likely none:
![image](https://github.com/ThaUnknown/miru/assets/6506529/0f7f68bb-0680-4309-b1bd-e01cc74b0ebb)

**Comment by mooncakke** [comment]
wow, how much ignorance and lack of education in these comments, look for a psychologist to treat whatever you have. There can be no doubt or request here, as you come with insults and xenophobia, regrettable.

**Comment by ThaUnknown** [comment]
honestly it's preferable if snowflakes like you didn't come back, you asked a question which was answered [3 times already](https://github.com/ThaUnknown/miru/issues?q=is%3Aissue+portuguese) then MANUALLY clicked "yes I looked for this problem already", if you're entitled enough to think you can waste other people's times like this, I suggest you re-evaluate your life decisions

**Comment by mooncakke** [comment]
Sometimes we end up letting something go unnoticed due to lack of attention or not understanding the subject very well, and then we look for support, even if it's something simple, anyway, I don't think that's a reason to be disrespectful to other people like that for free. on the internet or in real life, unfortunately there are people who only know how to be toxic on the internet, sorry to disturb your time or that of other people who commented here, it was just a silly doubt that could have been better evaluated if it weren't for the lack of education on the part of the human being.
