### ISSUE TITLE
[Bug]: KDE Connect weird interaction

### ISSUE THREAD

**Issue by JuanPardos** [ThaUnknown/miru#480]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [x] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

5.2.2

### What operating system version are you using?

Linux

### Expected Behavior

No android total system breakdown, I guess...

### Actual Behavior

This might sound funny or misplaced but I am having a weird bug between Miru and KDE Connect. The moment I start a stream in my Linux PC with KDE Connect and my Android phone paired, the later becomes almost unusable. The status bar takes like 10 sec to display, power off button 5 sec to react. It even starts to heat up (not kidding)...

Don't know what's going on but its 100% reproducible. **I don't have this issue with other video sources.**
Once I stop the stream everything returns to normal, phone feels responsive again like nothing happened.

PC:
- Arch Linux (up to date)
- miru-bin from AUR 5.2.2-1
- KDE Plasma 6.1.2-1
- KDE Connect 24.05.2-1

Mobile phone:
- POCO F5
- Xiaomi HyperOS (Android 14)
- KDE Connect 1.31 ?

I understand that this might be difficult to debug or KDE Connect related, if so I apologize.
I can live with that, but it's definitely a problem for me because I have both devices permanently paired.

**Comment by ThaUnknown** [comment]
do you launch miru on pc or android?

**Comment by JuanPardos** [comment]
PC. But I have the slowdown, heat etc issue on my mobile phone which is paired with KDE Connect (remote control, notifications, shared notifications, playback control...).
Note that this is the first time I face something like this, have no issue with other things like youtube, vlc etc.

**Comment by ThaUnknown** [comment]
it sounds like miru is putting high strain on your pc [duh] and KDE connect's shit implementation lags your phone since the stream cant keep up. anyways, kdeconnect seems like shitware, and its a stupidly niche issue which likely only occurs with ur linux setup, so i won't be pursuing this
