### ISSUE TITLE
[Bug]: Can't run/install after update

### ISSUE THREAD

**Issue by Bartek200219** [ThaUnknown/miru#484]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

5.2.3

### What operating system version are you using?

Windows

### Expected Behavior

Run normally

### Actual Behavior

Doesn't run, after uninstall installation doesn't even start portable doesn't work either

### Screenshots

![Miru_2024-07-14_17-08-07](https://github.com/user-attachments/assets/652bea08-209e-4bee-a11a-749a2120bd15)

**Comment by ThaUnknown** [comment]
likely update corrupted during pc restart, uninstall miru, clean out %appdata%/miru, feel free to back up ur settings since they will get wiped

**Comment by Bartek200219** [comment]
already uninstalled and installer doesn't launch/do anything

**Comment by ThaUnknown** [comment]
once again, clean out %appdata%/miru

**Comment by Bartek200219** [comment]
The folder doesn't exist, still the sam issue

**Comment by ThaUnknown** [comment]
well... that's odd... miru installs to `%appdata%/miru`, anyways, that error means something is killing the background thread, antivirus or other, or the thread is crashing before loading any code, which is unlikely?

**Comment by ThaUnknown** [comment]
I can't reproduce this issue

**Comment by Bartek200219** [comment]
Launched installer using cmd with arg /xd and installer popped up. I think without that it tried to search for existing installation but failed that's why it crashed

**Comment by ThaUnknown** [comment]
i'll chalk it up to corruption while downloading, cant do much about it
