### ISSUE TITLE
[Bug]: incorrect url encoding for external players

### ISSUE THREAD

**Issue by M0dius** [ThaUnknown/miru#486]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

5.2.3

### What operating system version are you using?

Windows

### Expected Behavior

Miru is supposed to play torrented video through an external player (when the setting is enabled and directory is set).

### Actual Behavior

Miru torrents video and it is visible in the torrent download location, but nothing is played (see attached images).

### Screenshots

![image_2024-07-24_235653592](https://github.com/user-attachments/assets/74aab739-45ba-43bc-8ada-9841031987c9)
![image_2024-07-24_235726154](https://github.com/user-attachments/assets/ede19093-d706-4585-980f-2f25a53609fc)

**Comment by M0dius** [comment]
The screenshots above are inconsistent with each other, my bad. Here's a better example:
![image_2024-07-25_000120824](https://github.com/user-attachments/assets/b3b53d48-8520-4b73-9bfa-e87f95be2832)
![image_2024-07-25_000129447](https://github.com/user-attachments/assets/ceeca2c0-f38a-48b3-8a5d-e5058a01ad91)

**Comment by ThaUnknown** [comment]
fixed in latest
