### ISSUE TITLE
[Bug]: Fetching Anime And Data NOt WOrking; Also Anilist connection not working

### ISSUE THREAD

**Issue by eddcm123** [ThaUnknown/miru#488]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

5.2.7

### What operating system version are you using?

Windows

### Expected Behavior

Anime being fetch and appearing on the app and watching series being there.

### Actual Behavior

Literally nothing there, just the error report
![Screenshot 2024-07-30 005822](https://github.com/user-attachments/assets/4aedb556-beb5-4287-bc85-bd6eb4babf3c)
![Screenshot 2024-07-30 005827](https://github.com/user-attachments/assets/aa63bf38-d119-44c9-8bba-71c2c5a5c537)
![Screenshot 2024-07-30 005807](https://github.com/user-attachments/assets/f50312d7-92f5-47ac-956b-09615b98c61a)

### Screenshots

![Screenshot 2024-07-30 005827](https://github.com/user-attachments/assets/ebe61ef4-1269-4645-8c7a-d9cb2d157dd7)
![Screenshot 2024-07-30 005822](https://github.com/user-attachments/assets/c98c336a-5213-4c7e-8b11-8bff68e0599c)
![Screenshot 2024-07-30 005807](https://github.com/user-attachments/assets/5bb9e846-6bff-4ef4-8df0-128eb6090d5e)

**Comment by Hexality** [comment]
anilist api is down.
