### ISSUE TITLE
[Bug]: Cannot read properties of null (reading 'data')

### ISSUE THREAD

**Issue by alinanonymous** [ThaUnknown/miru#489]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.2.7

### What operating system version are you using?

Windows

### Expected Behavior

Open Miru, home feed loads correctly

### Actual Behavior

Home menu loads incorrectly, showing "Ooops! Looks like something went wrong!. Cannot read properties of null (reading 'data')". Errors in top right say Miru is failing to make a request to anilist (403 - Forbidden) and that media for home feed cannot be loaded because it "Cannot read properties of null (reading 'data')."

I deleted the AppData folder (for both Miru and the updater) and reinstalled, but the issue persists. I double checked that it wasn't an issue with Windows Defender Firewall.

### Screenshots

Video: https://github.com/user-attachments/assets/e2ced61a-ce6a-45f9-a970-f5d7b7981089
![image](https://github.com/user-attachments/assets/2face49d-1ffe-4dfb-88db-ff36ea2569a3)

**Comment by Gwalover** [comment]
same bug for me :(

**Comment by pilar6195** [comment]
The AniList API, which this project relies on, is currently down due to backend issues on their part.
