### ISSUE TITLE
LMAO ??

### ISSUE THREAD

**Issue by 21R01A7263** [ThaUnknown/miru#490]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

5.2.7

### What operating system version are you using?

Windows

### Actual Behavior

There's actually, unironically two "New Releases" sections, right next to each other?? My mouse pointer precision is great thank you.

![image](https://github.com/user-attachments/assets/75c334fc-cffa-4d05-ab2d-51e595f24047)

I can enable BOTH the sections on my homepage and they show up frfr no cap?!! One truly cannot make this shit up

![image](https://github.com/user-attachments/assets/d437fa79-c9fb-4371-8e7b-4532a058bf2b)

And here I was, thinking, 2024 couldn't get any worse 🙄

**Comment by ThaUnknown** [comment]
you wanted to, it made two, just remove one of them
