### ISSUE TITLE
[Feature Request]: Ability to download episodes???

### ISSUE THREAD

**Issue by 21R01A7263** [ThaUnknown/miru#492]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Any release older than 2 seasons will face buffering, especially dub releases, due to low swarm

### Proposed Solution

Would be handy to download the episodes/releases with low seed count so one can avoid buffering

**Comment by ThaUnknown** [comment]
you download the episodes, from torrents, you're looking for the wrong software
