### ISSUE TITLE
[Feature Request]: mpv shader

### ISSUE THREAD

**Issue by shoraaa** [ThaUnknown/miru#494]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

mpv shader is not yet supported, and streaming anime to a resolution bigger than 1080p cause the image to be blurred.

### Proposed Solution

I would be great to have support for mpv's shader, such as upscaler like anime4k, etc.

**Comment by ThaUnknown** [comment]
miru adds deband from mpv, but adding universal support for mpv shaders isnt worth the time

**Comment by ThaUnknown** [comment]
you can use an external player if u want those shaders
