### ISSUE TITLE
[Bug]: App just hard crashed after updating (Windows)

### ISSUE THREAD

**Issue by Eichen97** [ThaUnknown/miru#495]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.2.15

### What operating system version are you using?

Windows

### Expected Behavior

The app opening and working as usual.

### Actual Behavior

Just got a notification telling me the app would update after closing it, did so so check out the changelog and now it crashes at start.

### Screenshots

![image](https://github.com/user-attachments/assets/984702a2-4cd3-497c-8784-2cee8bd5dab3)

**Comment by Eichen97** [comment]
killing the process from task manager let's the app open on the previous version again. but it shows once more the popup asking to update, and if you close the app, the error would pop up again.

![image](https://github.com/user-attachments/assets/44ba778c-fc15-42bf-bbdd-2f8f643dc626)

well, at least its an easy to replicate one.

**Comment by ThaUnknown** [comment]
update it via the update button on bottom left of screen, i'll fix this tmrw

**Comment by Eichen97** [comment]
ok, already checked #484
i was going to do as said there and wipe the whole app and download the new installer, but that worked.
thanks!

**Comment by ThaUnknown** [comment]
0ef55b1
