### ISSUE TITLE
[Feature Request]: Add a chat option

### ISSUE THREAD

**Issue by hlebushekhub** [ThaUnknown/miru#497]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

It would be cool to communicate with other users with the Watch Together function!

### Proposed Solution

Maybe something as Syncplay did with [their app](https://syncplay.pl/guide/client/)

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/miru/commit/67d19eb324dbd63c1c30d18fd99c70e574adff83
