### ISSUE TITLE
[Bug]: playback glitches

### ISSUE THREAD

**Issue by idklevi** [ThaUnknown/miru#499]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.2.16

### What operating system version are you using?

Windows

### Actual Behavior

using the latest version and currently facing playback glitches. 

### Screenshots

![Screenshot (1)](https://github.com/user-attachments/assets/9ee3eded-bfd5-4867-8d07-6a57f249b102)

**Comment by ThaUnknown** [comment]
looks like gpu issue

**Comment by idklevi** [comment]
> looks like gpu issue

I'm running the latest drivers on rtx 4070

**Comment by ThaUnknown** [comment]
it's possible windows is telling miru to use your iGPU not dGPU, in windows settigns app go to system, display, graphics and set miru to high performance
