### ISSUE TITLE
[ 2 Bugs]: Appimage/flatpak sometimes crashes when viewing video or using the detailed torrent selection UI 

### ISSUE THREAD

**Issue by Department-stack** [ThaUnknown/miru#500]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.2.16

### What operating system version are you using?

Linux

### Expected Behavior

Ideally these crashes shouldn't happen

### Actual Behavior

I have had this bug on my low end chromebook, sometimes the video will go white and the app will exit out, or completely reload. This happens on multiple desktop environments and even still on flatpak. Difficult to replicate but should be possible to do so.

Using the detailed "titlecard" during torrent selection crashes when scrolling. Easy to replicate

### Screenshots

None provided but here are some addtional system information:

Distribution: Fedora KDE 40

Desktop environment: COSMIC ALPHA

Kernel version: 6.9.11-200.fc40.x86_64

Processors: 2 × AMD A4-9120C RADEON R4, 5 COMPUTE CORES 2C+3G

Memory: 3.5 GiB of RAM

Graphics: AMD Radeon R3 Graphics

Laptop model: HP Chromebook 11A G8 EE

**Comment by ThaUnknown** [comment]
you're likely running out of memory for video/image decoding as you have an iGPU, use swap, if that doesn't fix it, it implies there's some GPU config issue with your linux distro, which I won't be fixing, fix your own distribution yourself

**Comment by ThaUnknown** [comment]
additionally flatpak is not supported, and miru isn't officially distributed on flatpak because of the many issues flatpak has

**Comment by Department-stack** [comment]
Got it, thanks for the helpful information ☺️

**Comment by Department-stack** [comment]
18:04:19.341 › null
18:04:19.346 › Uncaught TypeError: Failed to set the 'width' property on 'OffscreenCanvas': Value is not of type 'unsigned long'.
18:04:19.351 › Uncaught TypeError: Failed to set the 'width' property on 'OffscreenCanvas': Value is not of type 'unsigned long'.
[19155:1006/180504.719213:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133

**Comment by Department-stack** [comment]
latest appimage. on steam deck. with latest steamos version. i can semi-consistently reproduce this bug on multiple different linux machines 

Checking for update
22:34:27.077 › Update for version 5.5.6 is not available (latest version: 5.5.6, downgrade is disallowed).
22:34:27.081 › checkForUpdatesAndNotify called, downloadPromise is null
22:34:27.754 › JASSUB: setting total libass memory limits to: glyph=80000 MiB, bitmap cache=1024 MiB
22:34:27.755 › [object ProgressEvent]
22:34:52.828 › Uncaught (in promise) NotSupportedError: screen.orientation.lock() is not available on this device. 
( I got this when maximizing the application into fullscreen)
22:34:54.055 › Uncaught (in promise) NotSupportedError: screen.orientation.lock() is not available on this device. 
22:34:54.709 › Uncaught (in promise) NotSupportedError: screen.orientation.lock() is not available on this device.
22:34:55.104 › Uncaught (in promise) NotSupportedError: screen.orientation.lock() is not available on this device.
22:34:55.509 › Uncaught (in promise) NotSupportedError: screen.orientation.lock() is not available on this device.
22:34:56.825 › Uncaught (in promise) NotSupportedError: screen.orientation.lock() is not available on this device.
[6165:1016/223458.614090:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
22:35:11.527 › Uncaught (in promise) NotSupportedError: screen.orientation.lock() is not available on this device.
22:54:26.560 › Checking for update
22:54:27.286 › Update for version 5.5.6 is not available (latest version: 5.5.6, downgrade is disallowed).
22:54:27.287 › checkForUpdatesAndNotify called, downloadPromise is null
23:14:26.563 › Checking for update
23:14:27.335 › Update for version 5.5.6 is not available (latest version: 5.5.6, downgrade is disallowed).
23:14:27.336 › checkForUpdatesAndNotify called, downloadPromise is null
23:34:26.562 › Checking for update
23:34:27.290 › Update for version 5.5.6 is not available (latest version: 5.5.6, downgrade is disallowed).
23:34:27.291 › checkForUpdatesAndNotify called, downloadPromise is null
23:39:57.259 › JASSUB: setting total libass memory limits to: glyph=80000 MiB, bitmap cache=1024 MiB
23:39:57.260 › [object ProgressEvent]
23:54:26.561 › Checking for update
23:54:27.192 › Update for version 5.5.6 is not available (latest version: 5.5.6, downgrade is disallowed).
23:54:27.192 › checkForUpdatesAndNotify called, downloadPromise is null
00:04:38.169 › JASSUB: setting total libass memory limits to: glyph=80000 MiB, bitmap cache=1024 MiB
00:04:38.170 › [object ProgressEvent]
00:14:26.560 › Checking for update
00:14:27.184 › Update for version 5.5.6 is not available (latest version: 5.5.6, downgrade is disallowed).
00:14:27.185 › checkForUpdatesAndNotify called, downloadPromise is null
[6165:1017/003255.547366:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133 
(this happened when i finished watching a anime eposide, and chose to watch a different series. I selected a torrent using the detailed torrent selection ui. app went white and then the application crashed.)
[6165:1017/003300.162113:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[6165:1017/003301.001051:ERROR:command_buffer_proxy_impl.cc(131)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[6165:1017/003301.001300:ERROR:command_buffer_proxy_impl.cc(131)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[6165:1017/003301.002020:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[6165:1017/003301.723749:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[6165:1017/003302.539055:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[6165:1017/003303.450340:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[6165:1017/003304.079719:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[6165:1017/003304.782388:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[6165:1017/003305.424510:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[6165:1017/003305.424549:FATAL:gpu_data_manager_impl_private.cc(448)] GPU process isn't usable. Goodbye.


I think this should be investigated further

these are my miru settings

{"volume":1,"playerAutoplay":true,"playerPause":true,"playerAutocomplete":true,"playerDeband":false,"rssQuality":"720","rssFeedsNew":[["New Releases","SubsPlease"]],"rssAutoplay":false,"torrentSpeed":20,"torrentPersist":false,"torrentDHT":false,"torrentPeX":false,"torrentPort":0,"torrentStreamedDownload":true,"dhtPort":0,"missingFont":true,"maxConns":100,"subtitleRenderHeight":"720","subtitleLanguage":"eng","audioLanguage":"eng","enableDoH":false,"doHURL":"https://cloudflare-dns.com/dns-query","disableSubtitleBlur":false,"showDetailsInRPC":false,"smoothScroll":true,"cards":"full","expandingSidebar":true,"torrentPathNew":"/home/deck/Downloads/","font":null,"angle":"default","toshoURL":"https://feed.animetosho.org/","extensions":["@thaunknown/ani-resourced"],"sources":{"SeaDex":true,"AnimeTosho":true},"enableExternal":false,"playerPath":"","playerSeek":5,"playerSkip":false,"homeSections":["New Releases","Continue Watching","Sequels You Missed","Your List","Popular This Season","Trending Now","All Time Popular","Romance","Action","Adventure","Fantasy","Comedy"]}

i will add more additional information later

**Comment by Department-stack** [comment]
more detailed:

[11218:1017/012223.599149:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
01:22:23.686 ›   webtorrent:torrent [2d57573] [undefin] add peer %s +185ms  169.1.93.176:46331
01:22:23.687 ›   webtorrent:peer new %s Peer %s +224ms  utpOutgoing 169.1.93.176:46331
01:22:23.687 ›   webtorrent:torrent [2d57573] [undefin] _drain numConns %s maxConns %s +0ms  27 100
01:22:23.688 ›   webtorrent:torrent [2d57573] [undefin] drain (%s queued, %s/%s peers) +0ms  24 26 100
01:22:23.688 ›   webtorrent:torrent [2d57573] [undefin] %s connect attempt to %s +0ms  utpOutgoing 169.1.93.176:46331
01:22:23.703 ›   webtorrent:peer destroy %s %s (error: %s) +16ms  utpOutgoing 149.88.105.74:59198 connect timeout
01:22:23.703 ›   webtorrent:torrent [2d57573] [undefin] removePeer %s +16ms  149.88.105.74:59198
01:22:23.703 ›   webtorrent:torrent [2d57573] [undefin] _drain numConns %s maxConns %s +0ms  27 100
01:22:23.704 ›   webtorrent:torrent [2d57573] [undefin] drain (%s queued, %s/%s peers) +0ms  22 26 100
01:22:23.826 ›   webtorrent:peer destroy %s %s (error: %s) +124ms  utpOutgoing 204.8.98.25:4888 connect timeout
01:22:23.827 ›   webtorrent:torrent [2d57573] [undefin] removePeer %s +124ms  204.8.98.25:4888
01:22:23.827 ›   webtorrent:torrent [2d57573] [undefin] _drain numConns %s maxConns %s +0ms  27 100
01:22:23.828 ›   webtorrent:torrent [2d57573] [undefin] drain (%s queued, %s/%s peers) +0ms  21 26 100
01:22:23.868 ›   webtorrent:peer destroy %s %s (error: %s) +41ms  utpOutgoing 146.70.137.114:63851 connect timeout
01:22:23.868 ›   webtorrent:torrent [2d57573] [undefin] removePeer %s +41ms  146.70.137.114:63851
01:22:23.869 ›   webtorrent:torrent [2d57573] [undefin] _drain numConns %s maxConns %s +0ms  27 100
01:22:23.869 ›   webtorrent:torrent [2d57573] [undefin] drain (%s queued, %s/%s peers) +1ms  20 26 100
01:22:23.997 ›   webtorrent:torrent [2d57573] [undefin] add peer %s +129ms  87.101.92.171:38932
01:22:23.998 ›   webtorrent:peer new %s Peer %s +130ms  utpOutgoing 87.101.92.171:38932
01:22:23.998 ›   webtorrent:torrent [2d57573] [undefin] _drain numConns %s maxConns %s +0ms  27 100
01:22:23.998 ›   webtorrent:torrent [2d57573] [undefin] drain (%s queued, %s/%s peers) +0ms  22 26 100
01:22:23.998 ›   webtorrent:torrent [2d57573] [undefin] %s connect attempt to %s +0ms  utpOutgoing 87.101.92.171:38932
01:22:24.005 ›   webtorrent:torrent [2d57573] [undefin] conn %s closed: will re-add to queue in %sms (attempt %s) +7ms  149.88.105.74:59198 5000 2
01:22:24.005 ›   webtorrent:torrent [2d57573] [undefin] conn %s closed: will re-add to queue in %sms (attempt %s) +0ms  204.8.98.25:4888 5000 2
01:22:24.005 ›   webtorrent:torrent [2d57573] [undefin] conn %s closed: will re-add to queue in %sms (attempt %s) +0ms  146.70.137.114:63851 5000 2
01:22:24.024 ›   bittorrent-protocol [74c1065c] keep-alive +1s 
[11218:1017/012224.264125:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[11218:1017/012224.264164:FATAL:gpu_data_manager_impl_private.cc(448)] GPU process isn't usable. Goodbye.

**Comment by Department-stack** [comment]
@ThaUnknown

**Comment by ThaUnknown** [comment]
as mentioned before, this is an issue with ur gpu config, not miru, use --in-process gpu if ur external gpu process isnt configured correctly
