### ISSUE TITLE
[Feature Request]: Better performance for lower end cpu's

### ISSUE THREAD

**Issue by Department-stack** [ThaUnknown/miru#501]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

By far the biggest bottleneck for lower end devices. Using qbittorrent, 1080p video on vlc, & chrome at the same time still uses less cpu than miru. I understand that miru pretty much does everything that i described. But it does so at half the utilization. Maybe this is more of a bug report. If nothing can be done then oh well but it would nice for it to be more responsive.

### Proposed Solution

I really don't know the technicals but the torrenting process uses a lot more cpu and ram than qbittorrent. Actually optimizing this alone fixes the performance issue. I often just wait for the video to quit downloading so the video wont buffer or be coppy. (wifi speed isn't an issue here & some videos aren't as bad though) this could possibly be because of the format or how the video is encoded resulting in more resources being used. 

Additonal specs: 

Distribution: Fedora KDE 40

Desktop environment: COSMIC ALPHA

Kernel version: 6.9.11-200.fc40.x86_64

Processors: 2 × AMD A4-9120C RADEON R4, 5 COMPUTE CORES 2C+3G

Memory: 3.5 GiB of RAM

Graphics: AMD Radeon R3 Graphics

Network adapter: Qualcomm Wireless-AC 802.11a/b/g/n/ac (2x2) Wi-Fi and Bluetooth 4.2 Combo, non-vPro

Laptop model: HP Chromebook 11A G8 EE

**Comment by ThaUnknown** [comment]
![image](https://github.com/user-attachments/assets/7b6156af-c86d-49d1-897c-e6903855f245)

this sounds like an issue on your end, on windows miru uses less memory than chrome with only an empty tab open, on your device this would use roughly 20-30% cpu, which is fine, this looks like an issue with ur linux distro, which I won't be investigating, fix your own linux config yourself

**Comment by Department-stack** [comment]
I will look into it further
