### ISSUE TITLE
[Feature Request]: Completely disable Discord Rich Presence

### ISSUE THREAD

**Issue by BSoD38** [ThaUnknown/miru#502]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Hi, I've noticed that there is no way to completely disable Discord Rich Presence on Miru. I don't want to show this in my discord activity at all. The "Show details in discord rich presence" setting only disables which anime you are currently watching, but I just don't want to display anything at all. Miru isn't listed in the games list on Discord, do I don't think I can really disable it that way.

### Proposed Solution

Add a checkbox in the settings to completely disable Discord integration. When checked, it shouldn't display anything on my Discord profile.

**Comment by ThaUnknown** [comment]
duplicate issue

**Comment by BSoD38** [comment]
May I ask why this isn't planned? I find this to be very annoying. "Disable Discord RPC" is not a solution.

**Comment by Muril-o** [comment]
> May I ask why this isn't planned?

This is the only way miru uses to advertise itself.

> I find this to be very annoying.

Sure, you can always completely disable RPC in discord settings.

The solo dev of this spent hundreds of hours writing code for free so people like us can just click a few buttons, I personally find it hard to understand why people can't comply with this simple way of advertising, its not even invasive.

In any case, if you don't want to comply with the design choices or disable RPC in discord settings, fork and make your own changes, this is [free software](https://www.gnu.org/philosophy/free-sw.html) after all.

**Comment by BSoD38** [comment]
> I personally find it hard to understand why people can't comply with this simple way of advertising, its not even invasive.

You're taking this much too personally. I was genuinely asking a question on why this wasn't planned. Your first sentence as an answer was enough.

**Comment by Muril-o** [comment]
> You're taking this much too personally. I was genuinely asking a question on why this wasn't planned. Your first sentence as an answer was enough.

My apologies, I didn't mean to be rude and I could have phrased both solutions better without getting too personal and rationalizing about it, my bad.

**Comment by QuiteAFancyEmerald** [comment]
I see I apologize I should have read into it more.
