### ISSUE TITLE
[Bug]: can't stream "Attack on Tian Season 3 Episode 14"

### ISSUE THREAD

**Issue by SonaliBendre** [ThaUnknown/miru#503]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

latest

### What operating system version are you using?

Windows

### Actual Behavior

-

**Comment by ThaUnknown** [comment]
No response

**Comment by SonaliBendre** [comment]
@ThaUnknown I challenge you to try to stream AoT Season 3 Episode 14 

if you are able to play correct file, prove by uploading screenshot

**Comment by ThaUnknown** [comment]
if you can't put in the effort into making a proper response I won't put in any effort into replying to it, this isn't a product, it's my project that I make for myself, respond accordingly next time
