### ISSUE TITLE
[Bug]: miru playing wrong file

### ISSUE THREAD

**Issue by SonaliBendre** [ThaUnknown/miru#507]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

5.3.1

### What operating system version are you using?

Windows

### Expected Behavior

Play correct file

### Actual Behavior

I choosed to play AoT season 3 episode 13 but miru is playing AoT season 3 episode 1 file

**Comment by ThaUnknown** [comment]
pick a different torrent, duplicate issue
