### ISSUE TITLE
[Bug]: Wrong title Selected for the Monster Anime

### ISSUE THREAD

**Issue by PrimeTwister** [ThaUnknown/miru#508]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.3.1

### What operating system version are you using?

Windows

### Expected Behavior

Should stream the Monster Anime with the correct title (video file works fine)

### Actual Behavior

Puts on a random anime title and registers the wrong title on Anilist, not saving the title currently watching 

### Screenshots

![Error](https://github.com/user-attachments/assets/347dfaad-2ec6-4233-9f0a-3d34ebd3cb9f)

**Comment by ThaUnknown** [comment]
tracking as #257
