### ISSUE TITLE
[Bug]: updater fails on any version

### ISSUE THREAD

**Issue by phk-nord** [ThaUnknown/miru#512]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.4.1 Windows x64

### What operating system version are you using?

Windows

### Expected Behavior

Have the updater update miru without complications even if it's not installed in the standard directory.

### Actual Behavior

updater fails with the error 
> unable to remove old files

### Screenshots

I have miru installed on `E:\Program Files\Miru` Which seems to be a problem for the updater. If I donwload a new version of the installer it *can* correctly determine the custom installation directory. The build in miru debug logs don't show anything that would be helpful. I can provide an installation log although this also might not be too helpful.
[Installation_Log.txt](https://github.com/user-attachments/files/16739839/Installation_Log.txt)
I am only using miru since a week but not a single version was able to update itself hence I am opening this issue.

**Comment by ThaUnknown** [comment]
this sounds like a permission issue? maybe the folder you're installing miru in is restricted in some way, and since you're running the initial installer as admin it succeeds, but subsequent updates fail because the updater runs as user and the folder is restrcited?

**Comment by phk-nord** [comment]
You were right, I believe the root folder `Program Files` was created by another installer. Windows didn't even let me remove the "write protected" attribute. I could solve that issue now. Thanks for the pointer
