### ISSUE TITLE
[Feature Request]: Save .torrent file

### ISSUE THREAD

**Issue by flatigerest** [ThaUnknown/miru#513]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Not sure if miru uses magnets or actual .torrent files, but it would be handy if the .torrent files could be saved in some location so users can choose to continue seeding episodes after they have watched them.

### Proposed Solution

An option under Settings/Torrent/Client Settings where the user can choose a download location for the .torrent file.

**Comment by ThaUnknown** [comment]
A/B problem, what you want is to seed more, not to save .torrent files

**Comment by flatigerest** [comment]
> A/B problem, what you want is to seed more, not to save .torrent files

That's correct, my bad. Should I make a new feature request?

**Comment by ThaUnknown** [comment]
trackign as https://github.com/ThaUnknown/miru/issues/513

**Comment by ThaUnknown** [comment]
this is implemented in v6 under `hayase-cache` folder
