### ISSUE TITLE
[Feature Request]: Option to disable automatic updates

### ISSUE THREAD

**Issue by thegu5** [ThaUnknown/miru#515]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

By default, updates are automatically downloaded and installed without any prompting from the user. There are also some (temporary?) issues with automatic updates with Linux releases, as seen in #481 and #445.

### Proposed Solution

Add a setting that either stops update checking altogether, or has the user accept a prompt before downloading and installing.

**Comment by NotMugil** [comment]
+1

**Comment by nirmaleeswar30** [comment]
+1

**Comment by ThatOneCalculator** [comment]
+1 on this, please let us disable auto updates

**Comment by ThaUnknown** [comment]
no.

this would make sense for stable apps, but miru isn't stable, there are often cases where I push broken code, and I cannot allow people to run that no matter what. it happens more than it should because i develop this solo, so there's noone to verify the code, and it places a big workload on me

**Comment by ThatOneCalculator** [comment]
@ThaUnknown the only problem is that the auto-updater you implemented tries to run commands that *don't even exist* on my Linux distribution. Just let people override it while acknowledging that it may be a worse experience.

**Comment by ThaUnknown** [comment]
that's an issue with your distribution, or install method, not miru

**Comment by ThatOneCalculator** [comment]
That's not an issue with my distribution -- that's an issue with your packaging method. YOU recommend using `miru-bin` from the AUR on your readme, but because that uses the extracted `.deb` and you assume that anything installed from a `.deb` has `apt-get`, that's not my fault.

**Comment by ThaUnknown** [comment]
that was community contributed, I don't touch anythign linux because of people like you, if you believe it to be wrong you're free to fix it and submit a PR
