### ISSUE TITLE
[Bug]: Javasqript error on main process

### ISSUE THREAD

**Issue by qiura122** [ThaUnknown/miru#517]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.5.6

### What operating system version are you using?

Windows

### Actual Behavior

I just got updated to latest version then somehow the app can't be open and it says "A AavaScript error occurred"

### Screenshots

![Cuplikan layar 2024-08-30 003331](https://github.com/user-attachments/assets/da70403f-3304-43ee-a55e-c1e0e5814bcb)

**Comment by ThaUnknown** [comment]
uninstall miru, wipe %appdata%/miru and try again

**Comment by ThaUnknown** [comment]
happens when restarting miru too quickly

**Comment by ThaUnknown** [comment]
fixed
