### ISSUE TITLE
[Bug]: Unable to login to anilist on steamos

### ISSUE THREAD

**Issue by tomutoo** [ThaUnknown/miru#518]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.5.6

### What operating system version are you using?

Linux

### Expected Behavior

Upon clicking the login to anilist button was expecting it to put me through to firefox to login.

### Actual Behavior

When I do click the button, it throws me to the discover store to download Firefox despite it already being downloaded on my system. Attempting to delete and re download Firefox does not fix this issue either.

**Comment by tomutoo** [comment]
not sure if im stupid and this isnt a real issue, but would love some help :)

**Comment by GioGioWasTaken** [comment]
Does this issue occur when trying to press links outside of miru? say, on discord? 

If so, set your default browser. On my distro it's done using an environment variable. Check the relevant documentation for your distribution. 

If not, that's really weird lol.

**Comment by ThaUnknown** [comment]
this sounds like an issue with steamos, miru simply tells the OS to open an http link, and the OS handles it, sorry i cant help u here, try googling around for a fix

**Comment by Meiloorun** [comment]
Check what your default browser is set to in the settings. I think by default, the default browser is "Install Firefox" which sends you to Flathub to install it. This isn't for Miru but I had to change it off to the browser I was using, so you should probably be able to change it from "Install Firefox" to just "Firefox". Not sure why SteamOS doesn't change it automatically.
