### ISSUE TITLE
[Bug]: Continue Watching Page Not Showing Up and I Get a Javascript Error

### ISSUE THREAD

**Issue by theanimeenjoyer** [ThaUnknown/miru#519]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

5.5.6

### What operating system version are you using?

Windows

### Expected Behavior

After watching a show, the anime is supposed to show up in the "Continue Watching" tab.

### Actual Behavior

After an episode is played, it doesn't show up in the Continue Watching tab, it's not there.

### Screenshots

![image](https://github.com/user-attachments/assets/7c1237ea-ae35-4b47-a4d6-a4de6507e7cd)

![image](https://github.com/user-attachments/assets/e9ce61f6-2ebb-4968-8e2c-99f702d1af1b)

**Comment by theanimeenjoyer** [comment]
{
  "features": {
    "2d_canvas": "enabled",
    "canvas_oop_rasterization": "enabled_on",
    "direct_rendering_display_compositor": "disabled_off_ok",
    "gpu_compositing": "enabled",
    "multiple_raster_threads": "disabled_off",
    "opengl": "enabled_on",
    "rasterization": "enabled",
    "raw_draw": "disabled_off_ok",
    "skia_graphite": "disabled_off",
    "video_decode": "enabled",
    "video_encode": "enabled",
    "vulkan": "disabled_off",
    "webgl": "enabled",
    "webgl2": "enabled",
    "webgpu": "enabled"
  },
  "info": {
    "auxAttributes": {
      "amdSwitchable": false,
      "canSupportThreadedTextureMailbox": false,
      "displayType": "ANGLE_D3D11",
      "dx12FeatureLevel": "D3D 12.1",
      "glExtensions": "GL_AMD_performance_monitor GL_ANGLE_base_vertex_base_instance GL_ANGLE_base_vertex_base_instance_shader_builtin GL_ANGLE_client_arrays GL_ANGLE_depth_texture GL_ANGLE_framebuffer_blit GL_ANGLE_framebuffer_multisample GL_ANGLE_get_serialized_context_string GL_ANGLE_get_tex_level_parameter GL_ANGLE_instanced_arrays GL_ANGLE_lossy_etc_decode GL_ANGLE_memory_size GL_ANGLE_multi_draw GL_ANGLE_pack_reverse_row_order GL_ANGLE_polygon_mode GL_ANGLE_program_cache_control GL_ANGLE_provoking_vertex GL_ANGLE_request_extension GL_ANGLE_robust_client_memory GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ANGLE_texture_usage GL_ANGLE_translated_shader_source GL_APPLE_clip_distance GL_CHROMIUM_bind_generates_resource GL_CHROMIUM_bind_uniform_location GL_CHROMIUM_color_buffer_float_rgb GL_CHROMIUM_color_buffer_float_rgba GL_CHROMIUM_copy_compressed_texture GL_CHROMIUM_copy_texture GL_CHROMIUM_lose_context GL_CHROMIUM_sync_query GL_EXT_EGL_image_external_wrap_modes GL_EXT_base_instance GL_EXT_blend_func_extended GL_EXT_blend_minmax GL_EXT_clip_control GL_EXT_color_buffer_half_float GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_depth_clamp GL_EXT_discard_framebuffer GL_EXT_disjoint_timer_query GL_EXT_draw_buffers GL_EXT_draw_elements_base_vertex GL_EXT_float_blend GL_EXT_frag_depth GL_EXT_instanced_arrays GL_EXT_map_buffer_range GL_EXT_multi_draw_indirect GL_EXT_multisampled_render_to_texture GL_EXT_occlusion_query_boolean GL_EXT_polygon_offset_clamp GL_EXT_read_format_bgra GL_EXT_robustness GL_EXT_sRGB GL_EXT_shader_texture_lod GL_EXT_texture_border_clamp GL_EXT_texture_compression_bptc GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc_srgb GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_texture_mirror_clamp_to_edge GL_EXT_texture_norm16 GL_EXT_texture_rg GL_EXT_texture_storage GL_EXT_texture_type_2_10_10_10_REV GL_EXT_unpack_subimage GL_KHR_debug GL_KHR_parallel_shader_compile GL_NV_EGL_stream_consumer_external GL_NV_fence GL_NV_framebuffer_blit GL_NV_pack_subimage GL_NV_pixel_buffer_object GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_compressed_EAC_R11_signed_texture GL_OES_compressed_EAC_R11_unsigned_texture GL_OES_compressed_EAC_RG11_signed_texture GL_OES_compressed_EAC_RG11_unsigned_texture GL_OES_compressed_ETC2_RGB8_texture GL_OES_compressed_ETC2_RGBA8_texture GL_OES_compressed_ETC2_punchthroughA_RGBA8_texture GL_OES_compressed_ETC2_punchthroughA_sRGB8_alpha_texture GL_OES_compressed_ETC2_sRGB8_alpha8_texture GL_OES_compressed_ETC2_sRGB8_texture GL_OES_depth24 GL_OES_depth32 GL_OES_draw_elements_base_vertex GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_get_program_binary GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_surfaceless_context GL_OES_texture_border_clamp GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_array_object GL_WEBGL_video_texture ",
      "glImplementationParts": "(gl=egl-angle,angle=d3d11)",
      "glRenderer": "ANGLE (AMD, AMD Radeon(TM) Graphics (0x000015D8) Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.21034.37)",
      "glResetNotificationStrategy": 33362,
      "glVendor": "Google Inc. (AMD)",
      "glVersion": "OpenGL ES 2.0.0 (ANGLE 2.1.22481 git hash: f9bad5e27d61)",
      "glWsExtensions": "EGL_EXT_create_context_robustness EGL_ANGLE_d3d_share_handle_client_buffer EGL_ANGLE_d3d_texture_client_buffer EGL_ANGLE_surface_d3d_texture_2d_share_handle EGL_ANGLE_query_surface_pointer EGL_ANGLE_window_fixed_size EGL_ANGLE_keyed_mutex EGL_ANGLE_surface_orientation EGL_ANGLE_direct_composition EGL_NV_post_sub_buffer EGL_KHR_create_context EGL_KHR_image EGL_KHR_image_base EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_get_all_proc_addresses EGL_KHR_stream EGL_KHR_stream_consumer_gltexture EGL_NV_stream_consumer_gltexture_yuv EGL_ANGLE_stream_producer_d3d_texture EGL_ANGLE_create_context_webgl_compatibility EGL_CHROMIUM_create_context_bind_generates_resource EGL_CHROMIUM_sync_control EGL_EXT_pixel_format_float EGL_KHR_surfaceless_context EGL_ANGLE_display_texture_share_group EGL_ANGLE_display_semaphore_share_group EGL_ANGLE_create_context_client_arrays EGL_ANGLE_program_cache_control EGL_ANGLE_robust_resource_initialization EGL_ANGLE_create_context_extensions_enabled EGL_ANDROID_blob_cache EGL_ANDROID_recordable EGL_ANGLE_image_d3d11_texture EGL_ANGLE_create_context_backwards_compatible EGL_KHR_no_config_context EGL_KHR_create_context_no_error EGL_KHR_reusable_sync ",
      "glWsVendor": "Google Inc. (AMD)",
      "glWsVersion": "1.5 (ANGLE 2.1.22481 git hash: f9bad5e27d61)",
      "inProcessGpu": false,
      "initializationTime": 248.957,
      "isAsan": false,
      "isClangCoverage": false,
      "jpegDecodeAcceleratorSupported": false,
      "maxMsaaSamples": "8",
      "optimus": false,
      "overlayInfo": {
        "directComposition": true,
        "nv12OverlaySupport": "SCALING",
        "supportsOverlays": true,
        "yuy2OverlaySupport": "SOFTWARE"
      },
      "passthroughCmdDecoder": true,
      "pixelShaderVersion": "5.0",
      "sandboxed": false,
      "subpixelFontRendering": true,
      "supportsD3dSharedImages": true,
      "supportsDx12": true,
      "supportsVulkan": false,
      "targetCpuBits": 64,
      "vertexShaderVersion": "5.0",
      "videoDecodeAcceleratorSupportedProfile": {
        "encrypted_only": false,
        "maxResolutionHeight": 4096,
        "maxResolutionWidth": 2304,
        "minResolutionHeight": 64,
        "minResolutionWidth": 64,
        "profile": 17
      },
      "videoEncodeAcceleratorSupportedProfile": {
        "maxFramerateDenominator": 1,
        "maxFramerateNumerator": 30,
        "maxResolutionHeight": 1920,
        "maxResolutionWidth": 1088,
        "minResolutionHeight": 32,
        "minResolutionWidth": 32,
        "profile": 3
      },
      "visibilityCallbackCallCount": 0,
      "vulkanVersion": "Not supported"
    },
    "gpuDevice": [
      {
        "active": true,
        "cudaComputeCapabilityMajor": 0,
        "deviceId": 5592,
        "driverVendor": "AMD",
        "driverVersion": "27.20.21034.37",
        "gpuPreference": 0,
        "revision": 205,
        "subSysId": -2016538564,
        "vendorId": 4098
      },
      {
        "active": false,
        "cudaComputeCapabilityMajor": 0,
        "deviceId": 140,
        "driverVersion": "10.0.22621.3672",
        "gpuPreference": 0,
        "revision": 0,
        "subSysId": 0,
        "vendorId": 5140
      }
    ]
  },
  "cpu": {
    "model": "AMD Athlon Silver 3050U with Radeon Graphics   ",
    "speed": 2296
  },
  "ram": 3698143232,
  "appInfo": {
    "version": "5.5.6",
    "platform": "win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Miru/5.5.6 Chrome/122.0.6261.129 Electron/29.1.4 Safari/537.36",
    "support": {
      "offscreenRender": true,
      "update": true,
      "angle": true,
      "doh": true,
      "discord": true,
      "keybinds": true,
      "extensions": true,
      "isAndroid": false,
      "externalPlayer": true,
      "permamentNAT": true
    },
    "settings": {
      "volume": 1,
      "playerAutoplay": false,
      "playerPause": true,
      "playerAutocomplete": true,
      "playerDeband": false,
      "rssQuality": "1080",
      "rssFeedsNew": [
        [
          "New Releases (Subbed)",
          "SubsPlease"
        ],
        [
          "New Releases (Dubbed)",
          "Yameii [Dubbed]"
        ]
      ],
      "rssAutoplay": false,
      "torrentSpeed": 5,
      "torrentPersist": false,
      "torrentDHT": false,
      "torrentPeX": false,
      "torrentPort": 0,
      "torrentStreamedDownload": true,
      "dhtPort": 0,
      "missingFont": true,
      "maxConns": 50,
      "subtitleRenderHeight": "1080",
      "subtitleLanguage": "eng",
      "audioLanguage": "eng",
      "enableDoH": true,
      "doHURL": "https://cloudflare-dns.com/dns-query",
      "disableSubtitleBlur": false,
      "showDetailsInRPC": true,
      "smoothScroll": true,
      "cards": "small",
      "expandingSidebar": true,
      "angle": "default",
      "toshoURL": "https://feed.animetosho.org/",
      "extensions": [
        "anisearch"
      ],
      "sources": {
        "SeaDex": true,
        "AnimeTosho": true
      },
      "enableExternal": false,
      "playerPath": "",
      "playerSeek": 2,
      "playerSkip": false,
      "homeSections": [
        "Continue Watching",
        "New Releases (Dubbed)",
        "New Releases (Subbed)",
        "Popular This Season",
        "Trending Now",
        "Adventure",
        "Action",
        "Fantasy",
        "Romance"
      ]
    }
  }
}

from the debug settings...

**Comment by ThaUnknown** [comment]
for setting changes to take effect you need to restart the app
