### ISSUE TITLE
[Bug]: Remote control not working on android tv while watching fullscreen

### ISSUE THREAD

**Issue by Sheyk** [ThaUnknown/miru#521]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.3.4

### What operating system version are you using?

Android

### Expected Behavior

While watching a video on android tv (Nvidia Shield), I was expecting to be able to:
- press "back" to show the menu
- interact with the player icons

### Actual Behavior

The app is completely unresponsive to any button press on the remote while watching a video in fullscreen.

**Comment by ThaUnknown** [comment]
this is fixed in the upcoming version, no eta on release, im busy

**Comment by ThaUnknown** [comment]
@Sheyk this should be fixed in latest
