### ISSUE TITLE
[Bug]: Android - No torrent sources configured, add extensions in settings

### ISSUE THREAD

**Issue by ImGGAAVVIINN** [ThaUnknown/miru#524]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

5.3.4 Android aarch64

### What operating system version are you using?

Android

### Expected Behavior

Torrents should play on click

### Actual Behavior

Big red banner error when clicking on anime
"No torrent sources configured, add extensions in settings"

### Screenshots

![image](https://github.com/user-attachments/assets/88cabe1e-abae-4b99-8fbd-fefc6c539229)

**Comment by ThaUnknown** [comment]
that means you have no torrent sources configured, add extensions in setting, you can read more here https://miru.watch/extensions/

**Comment by ImGGAAVVIINN** [comment]
What extensions other than anise arch are working with miru right now?

**Comment by Meff1u** [comment]
> What extensions other than anise arch are working with miru right now?

nyaasearch, only one i found
