### ISSUE TITLE
[Bug]: miru android doesn't support sign/song subtitle

### ISSUE THREAD

**Issue by alexpandain** [ThaUnknown/miru#526]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.5.6

### What operating system version are you using?

Android

### Expected Behavior

Play  video with sign/song like Windows

### Actual Behavior

Video has subtitle but subtitle not showing

**Comment by ThaUnknown** [comment]
what anime, episode, release and timestamp?

**Comment by ThaUnknown** [comment]
no follow-up from OP
