### ISSUE TITLE
[Feature Request]: Continuation of the flathub package

### ISSUE THREAD

**Issue by Angxddeep** [ThaUnknown/miru#528]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

So, I have been using the flatpak version for quite a while, but I noticed that the Flatpak package hasn’t been updated in about 8 months. Miru is really a great app it's way I watch anime nowadays but after trying the latest AppImage with the latest features I really couldn't go back. Also, I could go about diminishing AppImage like it doesn't support automatic updates or doesn't create a desktop entry and runs with full system access and also built on a dependency that hasn't been updated since 2019. Anyway nowadays Flatpaks are becoming the way to distribute packages on Linux and with the app verification you can verify it and distribute to a much bigger crowd. Any chance you could look into it?. I know it's a bit big to ask as you have been working alone on the project, but TBH I would have made a PR if I knew how Flatpak are made. :) 

Thanks a lot for your hard work on the app!

### Proposed Solution

.

**Comment by Department-stack** [comment]
I would rather have the flatpak continued and the appimage discontinued myself
