### ISSUE TITLE
Windows protected your PC 

### ISSUE THREAD

**Issue by ViStatera** [ThaUnknown/miru#529]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

5.5.6

### What operating system version are you using?

Windows

### Expected Behavior

I thought there would be no problems to install the app

### Actual Behavior

When I try to install I see "Windows protected your PC ".Windows Defender doesn't let me use the app. Is it how it should be with every torrent including Miru or not?

**Comment by ThaUnknown** [comment]
yes, this message means "The author of this application doesn't pay Microsoft $100 per year, which means it's not safe" which is utter bullshit, because paying said $100 doesn't increase any security //rant

you can click more options and install anyways

**Comment by ViStatera** [comment]
Okay, I understand now. However it's interesting that I can't find any info about paying to Microsoft for security or I am not searching it the right way

**Comment by ThaUnknown** [comment]
https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/code-signing-cert-manage
