### ISSUE TITLE
[Bug]: How to fix fonts on Macos? Japanese Subtitles

### ISSUE THREAD

**Issue by k3rne1pan1c** [ThaUnknown/miru#530]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.5.6 Macos arm64

### What operating system version are you using?

MacOS

### Expected Behavior

I pick Japanese Subtitles and they show correctly

### Actual Behavior

<img width="1710" alt="Bildschirmfoto 2024-09-08 um 22 14 39" src="https://github.com/user-attachments/assets/8ceff74a-078d-42f5-a56d-07e2313d17f2">

Maybe there are fonts missing that support them? But how do I know which ones to pick? Because I can write Japanese on my laptop. So basic support for that is not the issue

**Comment by ThaUnknown** [comment]
this is the releaser's fault for not including a font which supports JP chars, you can go into settings, and change the fallback font to one which is on YOUR OS WHICH SUPPORTS JP CHARS, and restart miru, that might fix it, but this is the releaser's fault
