### ISSUE TITLE
[Bug]: when i scroll down the same anime thumbnails from the top of the list reappear

### ISSUE THREAD

**Issue by lHotaru** [ThaUnknown/miru#533]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

1.8.1

### What operating system version are you using?

Windows

### Expected Behavior

i excpected that it would show different anime's

### Actual Behavior

when it takes a second to load the anime's that load in are the same ones from the top

### Screenshots

![image](https://github.com/user-attachments/assets/e64d4e86-9e2f-4ac5-9077-1beb49e3ecf9)
![image](https://github.com/user-attachments/assets/02b3e6b5-96dd-4d7a-b454-b3d31a8302ac)
you can notice the scroll bar

**Comment by ThaUnknown** [comment]
this is a different miru, you're using the Chinese spyware, this is https://miru.watch

**Comment by lHotaru** [comment]
> this is a different miru, you're using the Chinese spyware, this is https://miru.watch

thanks alot man i was going crazy（づ￣3￣）づ╭❤～
