### ISSUE TITLE
[Bug]: Cant login to AniList on Android

### ISSUE THREAD

**Issue by ImDarkos** [ThaUnknown/miru#535]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v1.8.1

### What operating system version are you using?

Android

### Expected Behavior

Clicking on the Login Button on the Anilist tracker, login in and autorize.

### Actual Behavior

After login in with anilist it closses without giving me the option to authorize or decline miru access to anilist. I tried on a older phone with LineageOS as well and i have the same issue there. a friend of mine has the same issue as well

**Comment by ThaUnknown** [comment]
try going into app settings and enable open by default/allow app to open supported links

**Comment by ImDarkos** [comment]
![Screenshot_20240926_143809_Settings](https://github.com/user-attachments/assets/aa6caf85-819c-4dad-af82-65b03a27f2ef)
Went into my settings and checked. That was already activated. So i tried to disable, restarted the app tried. Same issue. Re-enabled, restarted the app and still the same behaviour.

**Comment by ThaUnknown** [comment]
thats the wrong miru, this is https://miru.watch, you got some china spyware
