### ISSUE TITLE
[Feature Request]: Fallback to another domain for torrents in case of down time.

### ISSUE THREAD

**Issue by Eichen97** [ThaUnknown/miru#539]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Animetosho RSS feed is currently down, so the app is currently unusable.

### Proposed Solution

fallback to https://www.erai-raws.info/feed/ or another domain/s instead for better stability.

**Comment by SahilBulatoo** [comment]
Were u able to fix it?

**Comment by ThaUnknown** [comment]
animetosho is only an extension, you can fix this by creating more extensions

**Comment by ThaUnknown** [comment]
erai raws Fred is just that, a feed, it doesn't offer an API or a reliable way for software to access their data
