### ISSUE TITLE
[Bug]: Miru fails to load after opening the application

### ISSUE THREAD

**Issue by Aayewsh** [ThaUnknown/miru#540]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.5.6

### What operating system version are you using?

Windows

### Expected Behavior

All the anime to show up under the "New Releases" section when starting the app. When you try to watch any episode, it loads up normally.

### Actual Behavior

I see a "Something went wrong" error after opening the app and none of the episodes load when trying to watch them. They throw a "torrent not found" error.

I'm attaching console screenshots below that may help with troubleshooting.

### Screenshots

![image](https://github.com/user-attachments/assets/3151fd8a-edeb-4822-9bbd-ec507e85a60e)
![image](https://github.com/user-attachments/assets/8d58d098-517f-4448-8184-5057354c51ab)

**Comment by Eichen97** [comment]
#539 Feature Request already psoted wabout it
#534 Another bug report mentioned before, at least this one has better screen captures, but still.

**Comment by ThaUnknown** [comment]
anisearch, aka an extension for animetosho is failing, because animetosho itself is dead, miru works fine, you can either add torrents manually by pasting magnet links to the app, or use a different extension if someone made one
