### ISSUE TITLE
[Feature Request]: Auto-Delete Completed Episodes

### ISSUE THREAD

**Issue by Nirioppai** [ThaUnknown/miru#543]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Many mobile users (could just be me) struggle with limited storage space when watching episodes of shows. After finishing an episode, they have to remember to manually delete it, which can be tedious and lead to clutter.

### Proposed Solution

Implementation of an auto-delete feature for episodes once they have been fully watched. This feature is inspired by the functionality available in Tachiyomi, which streamlines content management for users.

![image](https://github.com/user-attachments/assets/ea5cb6aa-7a2d-4505-b6c8-c7634b78a85e)

**Comment by ThaUnknown** [comment]
that's already done, it deletes completed torrents automatically
