### ISSUE TITLE
When watching foreign movies or anime, there are no subtitles

### ISSUE THREAD

**Issue by zerofen** [ThaUnknown/miru#548]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

在看日语动漫或者美剧的时候，有些没有字幕

### Proposed Solution

是否可以加一个字幕插件

**Comment by ThaUnknown** [comment]
English only
