### ISSUE TITLE
[Feature Request]: Support magnet urls for direct streaming

### ISSUE THREAD

**Issue by theincognito-inc** [ThaUnknown/miru#550]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Currently, there is no way (from what I can see) to stream using Miru, if you only have the magnet URL for it.

### Proposed Solution

Please add an option to stream by pasting the magnet URL, possibly on the "Search" Tab. 🙏🏼 

It doesn't have to be enabled by default - maybe enabled from "Settings" tab or something so that the users who don't care about this won't need to see it.

**Comment by ThaUnknown** [comment]
you can paste or drag/drop magnet links into miru and it will do its best to figure out what is being played

**Comment by theincognito-inc** [comment]
Haha. I am an idiot that I never thought of trying that. It works.

Thank you @ThaUnknown !

**Comment by ThaUnknown** [comment]
nah ur not, its a very poorly documented hidden feature, if you have an idea of how to prompt the user that this exists, feel free to suggest it
