### ISSUE TITLE
[Feature Request]: filter option

### ISSUE THREAD

**Issue by Sparky-temp** [ThaUnknown/miru#552]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

no way to search for anime in different language before selecting the torrent 

### Proposed Solution

add a filter option that allows you to look for if an anime has an dub and what languages its been dubbed in

**Comment by ThaUnknown** [comment]
there's not a way to do this, you could make an extension that targets specific releasers which have the language you're looking for, but i dont think this will ever be built into miru
