### ISSUE TITLE
[Bug]: New releases feed doesnt show up

### ISSUE THREAD

**Issue by Man-cubed** [ThaUnknown/miru#553]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.5..6

### What operating system version are you using?

Windows

### Expected Behavior

New releases should show up underneath its respective section.

### Actual Behavior

An error is shown in below screenshot. Uninstalling and reinstalling does not fix this.

### Screenshots

![UOZPjfXQr3](https://github.com/user-attachments/assets/b94efffb-bdd4-49bb-8dc1-7e7074a6f782)

**Comment by ThaUnknown** [comment]
try resetting settings to default in settings

**Comment by Man-cubed** [comment]
> try resetting settings to default in settings

THANK YOU IT WORKED LIKE A CHARM

**Comment by ThaUnknown** [comment]
this simply means u were fucking about in the settings and broke it yourself :)

**Comment by Man-cubed** [comment]
> this simply means u were fucking about in the settings and broke it yourself :)

yea lmao my bad
