### ISSUE TITLE
Warn: Do not install, infected my PC

### ISSUE THREAD

**Issue by Snowflakes-are-Snowflakes** [ThaUnknown/miru#559]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v2.0.1

### What operating system version are you using?

Windows

### Expected Behavior

Would let me pirate movies and shows

### Actual Behavior

PC would not boot after installing.

### Screenshots

![image](https://github.com/user-attachments/assets/95ea6367-adeb-4d2d-802f-f7e2e63c6562)

**Comment by ThaUnknown** [comment]
there's no Miru v2, you downloaded some virus or smth, miru's public versions started at v3

**Comment by ThaUnknown** [comment]
miru is for anime, not movies/shows, this is definetly the wrong app

**Comment by Snowflakes-are-Snowflakes** [comment]
be aware guys, the app IS a virus, do not install. I downloaded it from here.
