### ISSUE TITLE
[Bug]: When Miru is open, browsing internet is giving me cannot connect to server 

### ISSUE THREAD

**Issue by zr0fve** [ThaUnknown/miru#561]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

V5.5.6

### What operating system version are you using?

Windows

### Expected Behavior

Able to browse the internet while Miru is open.

### Actual Behavior

I cannot browse the internet when Miru is open. A lot of webpages just says cannot connect to server.

I'm not sure what's causing this. This only happens when Miru is open. I have been torrenting with qBitorrent and this doesn't happen with that. I have tried lowering the bandwidth to 2MB but still same issue.

### Screenshots

![image](https://github.com/user-attachments/assets/7b38b7f9-30cf-46ec-88fa-6e19765e6f5c)

**Comment by ThaUnknown** [comment]
this has been fixed, it means you're behind a CGNAT and cannot open ports

**Comment by zr0fve** [comment]
> this has been fixed, it means you're behind a CGNAT and cannot open ports

I am indeed behind a CGNAT! (I cant do anything about it because of ISP) Thank you!

**Comment by RnTor** [comment]
There's no fix?

**Comment by ThaUnknown** [comment]
yep, it means ur ISP is utter dogshit, or scamming you, but likely the prior
