### ISSUE TITLE
[Bug]: Crash when opening the search for some seconds

### ISSUE THREAD

**Issue by hardBSDk** [ThaUnknown/miru#564]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.5.6

### What operating system version are you using?

Linux

### Expected Behavior

Don't crash

### Actual Behavior

Crashes.

### Screenshots

Not possible.

**Comment by ThaUnknown** [comment]
fix ur gpu config or use --in-process-gpu

**Comment by hardBSDk** [comment]
@ThaUnknown Your solution doesn't makes sense because the program works.

But I forgot an important detail, it's the Flatpak version.
