### ISSUE TITLE
Miru app but in UWP

### ISSUE THREAD

**Issue by ParanoidHitman** [ThaUnknown/miru#570]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Just a small question, or suggestion if possible.

I would like to kindly suggest considering the availability of the Miru app on Xbox. (If possible)

Given that the Xbox (is a powerhouse beast in terms of performance) system is essentially a modified version of Windows 11 and supports various applications, it seems feasible to bring Miru to this platform.
Would it be possible to develop and launch the Miru app for Xbox?

Thanks

### Proposed Solution

Right know it’s possible to transform an install file in a UWP file that can be read by Xbox or Windows App Store and such.

[https://learn.microsoft.com/en-us/windows/uwp/porting/](url)

**Comment by ThaUnknown** [comment]
the only valid reason for this would be to run on xbox, however xbox doesnt come with win32 binaries, so it woulnd't run anyways, while this is possible, it won't work on xbox, and there's 0 reason to do it for windows
