### ISSUE TITLE
i accidently deleted my sources list. how to fix it?

### ISSUE THREAD

**Issue by nekohacker591** [ThaUnknown/miru#577]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

latest

### What operating system version are you using?

Windows

### Expected Behavior

torrents show up now they dont

### Actual Behavior

an error apon clicking on any anime

### Screenshots

![image](https://github.com/user-attachments/assets/d0c6f952-e279-4a6c-8f26-b2e0f83b3995)
![image](https://github.com/user-attachments/assets/65296b91-a647-4072-b414-97e2518d24c1)

**Comment by nekohacker591** [comment]
ok i figured it out but how to add new sources all the ones i tried just dont work

**Comment by nekohacker591** [comment]
their is like 0 documentation not even an api

**Comment by ThaUnknown** [comment]
reset settings to default
