### ISSUE TITLE
[Bug]: Video never plays

### ISSUE THREAD

**Issue by axiel7** [ThaUnknown/miru#578]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.5.6

### What operating system version are you using?

Windows

### Actual Behavior

Just installed the program in Windows 11 but video never plays. 
Already tried with various episodes with lots of seeders but it doesn't work.
I can download the actual torrent just fine using another client so it isn't an issue with my network.

Log file: [main.log](https://github.com/user-attachments/files/17609908/main.log)

**Comment by ThaUnknown** [comment]
you'd need to enable full debug in settings, reproduce the issue and send the logs again

**Comment by axiel7** [comment]
I already had the log level set to All.
Anyway I tried again and it's working now so it probably was an issue on my end (still no idea tho)
