### ISSUE TITLE
[Feature Request]: We need a Turkish option for Subtitles.

### ISSUE THREAD

**Issue by quirxsama** [ThaUnknown/miru#579]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

I am a Turk and I enjoy using Miru, but there is no Turkish option among all the options, it would be very nice if there was a Turkish option or a feature where we can import the subtitle files we want.

### Proposed Solution

* Adding Turkish Support
* Adding Importing subtitles files feature

**Comment by ThaUnknown** [comment]
miru is primarily english, u can add ur own subtitles to the player by pasting/drag dropping subtitle files into it
