### ISSUE TITLE
[Bug]: No torrent found for Dandadan Episode 1!  • No torrent sources configured. Add extensions in settings.

### ISSUE THREAD

**Issue by DusanKristus** [ThaUnknown/miru#582]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.5.9

### What operating system version are you using?

Android

### Actual Behavior

No torrent found for Dandadan Episode 1!

• No torrent sources configured. Add extensions in settings.

### Screenshots

![Screenshot_2024-11-07-15-33-34-21_8365ce5e19f7f00dd7d506a1fcdd696c](https://github.com/user-attachments/assets/2fb34c2a-7cac-442e-b5fb-235a7fccc42c)

**Comment by ThaUnknown** [comment]
https://miru.watch/extensions
