### ISSUE TITLE
[Bug]: i installed miru and it never works (faild to make a request to anilist)

### ISSUE THREAD

**Issue by SillyKoishi** [ThaUnknown/miru#583]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.5.6 x64

### What operating system version are you using?

Windows

### Expected Behavior

*that the web will function and i can see the animes*
*yet that never happened*
i tried installing and uninstalling it multiple times and didnt work

### Actual Behavior

the interface doesnt show anything
anilist doesnt work
*nothing works other then changing settings and going through offline things*

### Screenshots

![image](https://github.com/user-attachments/assets/88002712-9d15-463e-a38f-452873347d16)

https://github.com/user-attachments/assets/4d1b3522-8c27-41f1-9c4b-0fae4142ed9d

**Comment by mish20011** [comment]
same for me, its not working

**Comment by ThaUnknown** [comment]
says right there 
![image](https://github.com/user-attachments/assets/04c19fea-9d2e-4d59-ba05-66b05a7019f4)

**Comment by SillyKoishi** [comment]
> says right there ![image](https://private-user-images.githubusercontent.com/6506529/384691152-04c19fea-9d2e-4d59-ba05-66b05a7019f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNDQ1NjQsIm5iZiI6MTczMTI0NDI2NCwicGF0aCI6Ii82NTA2NTI5LzM4NDY5MTE1Mi0wNGMxOWZlYS05ZDJlLTRkNTktYmEwNS02NmIwNWE3MDE5ZjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTBUMTMxMTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2U0MTI3MjIzNWRjZDhkMDgzMDgzMmQzMjBmMjc2NDA5NmEyMTA4Yjk3OWNmZDg5MjZjOGNmODE5MzJhOThlMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.KvMZZYtzyZpF-BIdGvMM9LHz1sW8dEOz0eqeAIkq8AM)


![image](https://github.com/user-attachments/assets/69adfd94-f1ce-437f-92c3-92c2960e6d60)


i checked discord and the dev says that
it still doesnt work and im already planning on resetting my windows (it feels bloated)

so i just wait or what?

**Comment by gevezelain** [comment]
This is happening to me again after updating Miru to v5.5.8 🤔
