### ISSUE TITLE
[Bug]: AppImage is lacking executable permissions (+x) in the 5.5.7 release

### ISSUE THREAD

**Issue by tiritto** [ThaUnknown/miru#585]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.5.7

### What operating system version are you using?

Linux

### Expected Behavior

When launching the AppImage, the application should start normally after making only the AppImage itself executable with `chmod +x`.

### Actual Behavior

After making the AppImage executable, launching it results in a permission denied error similar to:
`/tmp/.mount_linux-JlAkdE/AppRun: line 43: /tmp/.mount_linux-JlAkdE/miru: Access denied`

Adding executable permission to the `miru` binary alone fixed the launching issue. However, comparing with the previous release's permissions, I noticed several other files are also missing +x flags that were present before:
— Chromium components (`chrome_crashpad_handler`, `chrome-sandbox`)
— Shared libraries (`libEGL.so`, `libffmpeg.so`, `libGLESv2.so`, `libvk_swiftshader.so`, `libvulkan.so.1`)

While these missing permissions don't seem to cause any issues on my system, they might be worth investigating as they differ from the previous release's (5.5.6) file permission setup.

This issue has been previously mentioned in #584, but its creator closed the issue.

**Comment by ThaUnknown** [comment]
try latest

**Comment by tiritto** [comment]
It works like a charm yet again.
Thank you!
