### ISSUE TITLE
[Feature Request]: Add a option to disable miru internal app updater

### ISSUE THREAD

**Issue by BlindAndInsane** [ThaUnknown/miru#588]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Miru currently auto downloads and try to install new update of miru by itself and in my case as i am using arch linux it is trying to use dpkg which is for debain family of distribution. This system of software management is ok in windows but for linux most distribution promote the use of package managers which keeps everything well managed and prevent breaking of the system. Miru is not respecting package manager and is trying to auto download and install new version of itself. 

In regards to [this](https://github.com/ThaUnknown/miru/issues/515#issuecomment-2483644863)
Thats the purpose of AUR and using rolling release distribution you can push updates whenever you want and can fix the bugs and when user updates their system or that app it will properly install the new version that you push.

Please add this feature as it will get rid of anoying auto updater and save me some bandwitdh by not downloading useless app bundle which is not even compatible with my distro. 

### Proposed Solution

Add a simple toggle in settings to disable this feature and it would be very helpful if u can make your updater opt-in when distributing it to AUR.

**Comment by ThaUnknown** [comment]
duplicate
