### ISSUE TITLE
[Feature Request]: HDMI/TypeC presentation mode on android phone

### ISSUE THREAD

**Issue by finch71** [ThaUnknown/miru#590]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

support HDMI/TypeC presentation mode on android phone and save battery by showing only black screen on the phone (only for control)

### Proposed Solution

https://stackoverflow.com/questions/54953778/displaying-video-on-secondary-screen-using-android-presentation-class

**Comment by ThaUnknown** [comment]
I think you're looking for android's own presentation mode or desktop mode.
