### ISSUE TITLE
[Feature Request]: Add option to hide "Video Codec Unsupported" message on start-up

### ISSUE THREAD

**Issue by Tiagoquix** [ThaUnknown/miru#595]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

When I open the app, I always get the "Video Codec Unsupported" message. This happens because the video isn't loaded yet, but it plays normally after being loaded (I don't have "persist files" enabled).

On Linux, using the Flatpak version (which is basically the AppImage if you read the Flatpak manifest). I have added a Flatpak override for Miru to use `/tmp/miru_anime_stream` and that is my custom directory for torrent downloads (without setting a custom directory, no videos play, but that's a Flatpak sandbox issue).

*You should really consider mantaining this as a Flatpak instead of an AppImage, but that's another topic.*

### Proposed Solution

Add option to hide this notification after starting the application because it always appears when the first episode (which is the last I was watching) is being loaded.

(ANGLE Backend is set to "Default".)

**Comment by ThaUnknown** [comment]
that error means something is fucked with ur Linux install, not miru, I recommend you investigate that
