### ISSUE TITLE
[Bug]: scrolling content is seems so hard and slow in the app, but everything is normal when outside 

### ISSUE THREAD

**Issue by mish20011** [ThaUnknown/miru#596]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.5.9

### What operating system version are you using?

Windows

### Expected Behavior

I expected inside the app to easily scroll through the anime list but I have to scroll 10 more times faster than normal (this is when I change the number of lines for vertical scrolling)

### Actual Behavior

scrolling in my browsers, and file managers and other apps seem to be okay, only in miru

### Screenshots

https://github.com/user-attachments/assets/ca26a85d-fba9-4175-a1cb-a7cb8cb8a0db

**Comment by CanRau** [comment]
Have to say the same is pretty annoying on the website miru.watch, the scroll-hijacking makes it pretty unpleasant to browse, at least to me, also most of the shortcuts/gestures I always use like swiping left right, cmd+up/down (to quickly go to top or bottom) work unreliable or not at all.

Also I'm on a M3 Macbook Air so the machine shouldn't be a bottleneck, I was so happy when I found here that I could disable "smooth scrolling" after disabling it feels much "smoother" to me 🤓 

Didn't wanna open a new issue for this even tho might've been "better" 🤔
