### ISSUE TITLE
[Bug]: Submodule not found

### ISSUE THREAD

**Issue by 2547techno** [ThaUnknown/miru#599]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.5.9

### What operating system version are you using?

Windows

### Expected Behavior

Submodule repo is available/public

### Actual Behavior

When cloning the repo with submodules, the electron-dist submodule fail to clone. It's source (https://github.com/hayase-app/electron-dist) 404s. If you own this repo can you make it public, if not can you push the copy you have locally to a new repo?

**Comment by ThaUnknown** [comment]
yes, install without the submodule
