### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Dt-sindome** [ThaUnknown/miru#601]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v1.8.1

### What operating system version are you using?

Android

### Expected Behavior

When I open a show to watch i expect something to show

### Actual Behavior

However, when I try to watch something and error comes up before the show can even start loading and I get stuck on a black screen.

### Screenshots

![Screenshot_20241213-185956](https://github.com/user-attachments/assets/8f248df5-af26-4ffa-b8fc-a703fbb2965a)

**Comment by ThaUnknown** [comment]
this is https://miru.watch, it's not the app you're running

**Comment by Dt-sindome** [comment]
> this is https://miru.watch, it's not the app you're running

I am using the app, I completely forgot there was an online version.
![Screenshot_20241215-192902~2](https://github.com/user-attachments/assets/2c2caa28-c7bd-4ef1-8b60-2cadfcbf9724)

**Comment by ThaUnknown** [comment]
this is again not the same app
