### ISSUE TITLE
Extract error

### ISSUE THREAD

**Issue by ThaRealJozef** [ThaUnknown/miru#96]
1st try when installing it gives me Extract: error writing to file Uninstall Miru.exe and pressing ok just stays like that, i had to exit the installing process.
2nd try gives me extract error writing to file C:\User\user\AppData\Local\Temp\nsu854F.tmp\nsis7z.dll, had to exit one more time.
3rd try gives me extract :error writing to file Uninstall Miru.exe
4rd try gives me extract error writing to file C:\User\user\AppData\Local\Temp\nsf70A.tmp\app-64.7z
5nd try: extract error writing to file C:\User\user\AppData\Local\Temp\nsu6821.tmp\app-64.7z
6th try : error writing to file C:\User\user\AppData\Local\Temp\nsv4F64.tmp\app-64.7z
7th try : error writing to file C:\User\user\AppData\Local\Temp\nst3F3E.tmp\app-64.7z
..... Many many errors
Finally not able to install given this errors.

**Comment by ThaUnknown** [comment]
make sure you're running windows 64bit and have enough drive space

invalid issue template

**Comment by ThaRealJozef** [comment]
i have 4 gb free and yes it's 64bit
